# Regularization : Ridge vs. Lasso 🥊🥊
Ridge and Lasso are two variations of the regularization technique. The difference comes from a slight change in the mathematical expression of the cost function used to train the model. In this exercise, these two regularization srtategies will be compared in order to analyze their respective influence on the model's coefficients. The effect of the regularization strength $\alpha$ will also be studied.

## Importing libraries and loading the dataset

1. Import the usual libraries. Don't forget to import scikit-learn's following model classes:
* LinearRegression
* Ridge
* Lasso

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import  StandardScaler
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV

2. Execute the following line of code to read the dataset directly from our S3

In [2]:
dataset = pd.read_csv("https://full-stack-bigdata-datasets.s3.eu-west-3.amazonaws.com/Machine+Learning+Supervis%C3%A9/R%C3%A9gression+r%C3%A9gularis%C3%A9es/gene+data/data_lasso.csv",)

In [3]:
dataset.head()

,Unnamed: 0.1,Unnamed: 0,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,...,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530,target
0,0,sample_0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,...,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.0,12.408154
1,1,sample_1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,...,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.0,13.414970
2,2,sample_2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,...,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.0,13.566183
3,3,sample_3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,...,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.0,12.943886
4,4,sample_4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,...,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.0,91.307146

3. The two first columns are useless, find a way to get rid of them.

In [4]:
dataset = dataset.iloc[:, 2:]
dataset.head()

,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,gene_9,...,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530,target
0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,0.0,...,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.0,12.408154
1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,0.0,...,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.0,13.414970
2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,0.0,...,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.0,13.566183
3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,0.0,...,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.0,12.943886
4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,0.0,...,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.0,91.307146

## Exploration

4. Print some information about the dataset. Do you notice something unusual ?

In [5]:
dataset.shape

(801, 20532)

5. Make sure there are no missing values at all in the whole dataset

In [6]:
dataset.isnull().values.any()

False

## Preparing the data for machine learning
6. Separate the target from the features

In [7]:
target = "target"

Y = dataset[target]
X = dataset[dataset.columns[dataset.columns != target]]
X

,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,gene_9,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.000000
1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.000000
2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.000000
3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.000000
4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,0.0,1.865642,2.718197,7.350099,10.006003,0.0,6.764792,0.496922,0.0,0.0,...,6.088133,9.118313,10.004852,4.484415,9.614701,12.031267,9.813063,10.092770,8.819269,0.000000
797,0.0,3.942955,4.453807,6.346597,10.056868,0.0,7.320331,0.000000,0.0,0.0,...,6.371876,9.623335,9.823921,6.555327,9.064002,11.633422,10.317266,8.745983,9.659081,0.000000
798,0.0,3.249582,3.707492,8.185901,9.504082,0.0,7.536589,1.811101,0.0,0.0,...,5.719386,8.610704,10.485517,3.589763,9.350636,12.180944,10.681194,9.466711,4.677458,0.586693
799,0.0,2.590339,2.787976,7.318624,9.987136,0.0,9.213464,0.000000,0.0,0.0,...,5.785237,8.605387,11.004677,4.745888,9.626383,11.198279,10.335513,10.400581,5.718751,0.000000
800,0.0,2.325242,3.805932,6.530246,9.560367,0.0,7.957027,0.000000,0.0,0.0,...,6.403075,8.594354,10.243079,9.139459,10.102934,11.641081,10.607358,9.844794,4.550716,0.000000

7. Make a train/test splitting

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

### Preprocessing
8. What preprocessings are necessary here ? Apply them to the features

In [9]:
pd.set_option('display.max_columns', None)
dataset.dtypes

dataset.dtypes.value_counts()

float64    20532
Name: count, dtype: int64

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_train

array([[-0.18260929,  1.90922841,  0.55666368, ...,  2.56930826,
        -0.08594483, -0.26295175],
       [-0.18260929,  0.83064273,  0.28377528, ..., -0.66063474,
         2.33028951, -0.26295175],
       [-0.18260929,  0.49373092,  0.78493894, ..., -0.19430024,
         1.20339421, -0.26295175],
       ...,
       [-0.18260929, -0.38215881, -0.42249159, ..., -0.53615319,
        -0.65695452, -0.26295175],
       [-0.18260929,  0.96610584,  0.61747234, ...,  0.80191873,
         0.4136774 , -0.26295175],
       [-0.18260929,  0.00581922, -0.54792011, ...,  1.07668602,
         0.68093856, -0.26295175]])

In [11]:
X_test = scaler.transform(X_test)
X_test

array([[-0.18260929,  0.2429336 ,  1.37848035, ...,  0.39936478,
        -1.16087917, -0.26295175],
       [-0.18260929,  0.70568734,  0.21899154, ...,  0.76452297,
        -0.07575806, -0.26295175],
       [-0.18260929,  1.20507988,  0.45969636, ..., -0.77359771,
        -0.48715095, -0.26295175],
       ...,
       [-0.18260929,  0.43581279,  1.02260814, ..., -1.17520777,
        -0.55258271, -0.26295175],
       [-0.18260929, -0.3833982 , -0.38468189, ...,  0.36282142,
        -0.01442762, -0.26295175],
       [-0.18260929,  0.14835308, -0.37323333, ..., -0.9080833 ,
        -0.06517458, -0.26295175]])

## Ridge
Let's focus on Ridge regularization. We'll train 3 Ridge regressors with different values of the strength $\alpha$, and analyze the performances as well as the influence on the model's coefficients.

9. Declare an instance of the Ridge class with $\alpha = 1$. Save this instance for later analysis into an object called `ridge1`. Train the model and display its R2-score on train and test sets.

In [12]:
ridge1 = Ridge()
ridge1.fit(X_train, Y_train)

print("R2 score on training set : ", ridge1.score(X_train, Y_train))
print("R2 score on test set : ", ridge1.score(X_test, Y_test))

R2 score on training set :  0.9999999996577973
R2 score on test set :  0.9836218646691628

10. Declare an instance of the Ridge class with $\alpha = 1000000$. Save this instance for later analysis into an object called `ridge2`. Train the model and display its R2-score on train and test sets.

In [13]:
ridge2 = Ridge(alpha=1000000)
ridge2.fit(X_train, Y_train)

print("R2 score on training set : ", ridge2.score(X_train, Y_train))
print("R2 score on test set : ", ridge2.score(X_test, Y_test))

R2 score on training set :  0.6456028421883675
R2 score on test set :  0.6210598969099537

11. Declare an instance of the Ridge class with $\alpha=100000000$. Save this instance for later analysis into an object called `ridge3`
. Train the model and display its R2-score on train and test sets.

In [14]:
ridge3 = Ridge(alpha=100000000)
ridge3.fit(X_train, Y_train)

print("R2 score on training set : ", ridge3.score(X_train, Y_train))
print("R2 score on test set : ", ridge3.score(X_test, Y_test))

R2 score on training set :  0.015667456835194216
R2 score on test set :  0.01493565740552194

12. How do the scores vary when alpha changes? Can you explain what's happening?

13. Extract the coefficients of each of the three Ridge models, and store them into a DataFrame

In [15]:
features = X.columns

ridge_coef = pd.DataFrame({
    "Feature": features,
    "Ridge1": ridge1.coef_,
    "Ridge2": ridge2.coef_,
    "Ridge3": ridge3.coef_
})

ridge_coef.head()

  Feature    Ridge1    Ridge2    Ridge3
0  gene_0 -0.008681 -0.001182 -0.000021
1  gene_1 -0.014291 -0.002421 -0.000029
2  gene_2 -0.010445 -0.003514 -0.000053
3  gene_3 -0.006097 -0.000736 -0.000008
4  gene_4  0.005259  0.004188  0.000077

14. Plot the coefficients of the three models in the same figure. What do you notice?

In [16]:
import plotly.express as px
custom_colors = {
    'Ridge1': "#40adb5",
    'Ridge2': "#3d7ca8",
    'Ridge3': "#0a3656",
}

fig = px.line(
    ridge_coef,
    x="Feature",
    y=["Ridge1", "Ridge2", "Ridge3"],
    title="Ridge Regression Coefficients",
    labels={"value": "Coefficient", "variable": "Ridge Regression Model"},
    color_discrete_map=custom_colors
)

fig.show()

## Lasso
Let's make the same study with Lasso regularization.

15. Declare an instance of the Lasso class with $\alpha = 1$. Save this instance for later analysis into an object called `lasso1`. Train the model and display its R2-score on train and test sets.

In [17]:
lasso1 = Lasso(alpha=1)
lasso1.fit(X_train, Y_train)

print("R2 score on training set : ", lasso1.score(X_train, Y_train))
print("R2 score on test set : ", lasso1.score(X_test, Y_test))

R2 score on training set :  0.9869991549190295
R2 score on test set :  0.9795379358283144

16. Declare an instance of the Lasso class with $\alpha = 30$. Save this instance for later analysis into an object called `lasso2`. Train the model and display its R2-score on train and test sets.

In [18]:
lasso2 = Lasso(alpha=30)
lasso2.fit(X_train, Y_train)

print("R2 score on training set : ", lasso2.score(X_train, Y_train))
print("R2 score on test set : ", lasso2.score(X_test, Y_test))

R2 score on training set :  0.2094242867325934
R2 score on test set :  0.2098146140156445

17. Declare an instance of the Lasso class with $\alpha = 100$. Save this instance for later analysis into an object called `lasso3`. Train the model and display its R2-score on train and test sets.

In [19]:
lasso3 = Lasso(alpha=100)
lasso3.fit(X_train, Y_train)

print("R2 score on training set : ", lasso3.score(X_train, Y_train))
print("R2 score on test set : ", lasso3.score(X_test, Y_test))

R2 score on training set :  0.0
R2 score on test set :  -1.619771758631927e-05

18. Plot the coefficients of the three models in the same figure. What do you notice?

In [20]:
features = X.columns

lasso_coef = pd.DataFrame({
    "Feature": features,
    "Lasso1": lasso1.coef_,
    "Lasso2": lasso2.coef_,
    "Lasso3": lasso3.coef_
})
lasso_coef.head()

  Feature  Lasso1  Lasso2  Lasso3
0  gene_0    -0.0    -0.0    -0.0
1  gene_1    -0.0    -0.0    -0.0
2  gene_2    -0.0    -0.0    -0.0
3  gene_3     0.0    -0.0    -0.0
4  gene_4     0.0     0.0     0.0

In [21]:
fig =  px.line(
    lasso_coef,
    x="Feature",
    y=["Lasso1", "Lasso2", "Lasso3"],
    title="Lasso Regression Coefficients",
    labels={"value": "Coefficient", "variable": "Lasso Regression Model"},
)

fig.show()

## Hyperparameter optimization
19. Use grid search to find the best value for $\alpha$, for Ridge and then for Lasso. You can test the following list of values:
* Ridge: $\alpha = $ [0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100]
* Lasso: $\alpha = $ [1, 2, 3, 5, 10, 20, 30]

In [22]:
ridge_params = {
    'alpha': [0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100],
}
ridge = Ridge()

ridge_grid_search = GridSearchCV(estimator=ridge, param_grid=ridge_params, cv=5, scoring='r2')

ridge_grid_search.fit(X_train, Y_train)

print("Meilleur alpha :", ridge_grid_search.best_params_)
print("Meilleur score R² :", ridge_grid_search.best_score_)

Meilleur alpha : {'alpha': 0.01}
Meilleur score R² : 0.9830659570819469

In [23]:
lasso_params = {
    'alpha': [1, 2, 3, 5, 10, 20, 30],
}
lasso = Lasso()
lasso_grid_search = GridSearchCV(estimator=lasso, param_grid=lasso_params, cv=5, scoring='r2')
lasso_grid_search.fit(X_train, Y_train)
print("Meilleur alpha :", lasso_grid_search.best_params_)
print("Meilleur score R² :", lasso_grid_search.best_score_)

Meilleur alpha : {'alpha': 1}
Meilleur score R² : 0.9808962374072732

### Comparing models
20. Display the scores on train set and test set for the best Ridge and for the best Lasso model.

In [24]:
ridge_best = Ridge(alpha=0.1)
ridge_best.fit(X_train, Y_train)
print("R2 score on training set with best alpha : ", ridge_best.score(X_train, Y_train))
print("R2 score on test set with best alpha : ", ridge_best.score(X_test, Y_test))

R2 score on training set with best alpha :  0.9999999999965764
R2 score on test set with best alpha :  0.983622342502

In [25]:
lasso_best = Lasso(alpha=1)
lasso_best.fit(X_train, Y_train)
print("R2 score on training set with best alpha : ", lasso_best.score(X_train, Y_train))
print("R2 score on test set with best alpha : ", lasso_best.score(X_test, Y_test))

R2 score on training set with best alpha :  0.9869991549190295
R2 score on test set with best alpha :  0.9795379358283144

21. Plot the coefficients of the best Ridge and best Lasso models in the same figure. If you had to deploy a model in production, which one would you choose and why?

In [26]:
features = X.columns
ridge_best_coef = pd.DataFrame({
    "Feature": features,
    "Best_Ridge": ridge_best.coef_,
    "Best_Lasso": lasso_best.coef_
})
ridge_best_coef.head()

  Feature  Best_Ridge  Best_Lasso
0  gene_0   -0.008682        -0.0
1  gene_1   -0.014297        -0.0
2  gene_2   -0.010446        -0.0
3  gene_3   -0.006097         0.0
4  gene_4    0.005259         0.0

In [27]:
fig = px.line(
    ridge_best_coef,
    x="Feature",
    y=["Best_Ridge", "Best_Lasso"],
    title="Best Ridge and Lasso Regression Coefficients",
    labels={"value": "Coefficient", "variable": "Regression Model"},
    color_discrete_map={"Best_Ridge": "#40adb5", "Best_Lasso": "#3d7ca8"}
)
fig.show()

## Using Lasso as an automated feature selection method
Let's focus on the best Lasso model. Only a few features have non-zero coefficients, which means that we could train a model by including only these features, and still get the same performances.

22. Extract the names of the features that have non-zero coefficients in Lasso.

In [28]:
mask = ridge_best_coef['Best_Lasso'] != 0
best_features = ridge_best_coef.loc[mask, 'Feature'].to_list()
best_features

['gene_221',
 'gene_357',
 'gene_747',
 'gene_864',
 'gene_1063',
 'gene_1384',
 'gene_2073',
 'gene_2655',
 'gene_2747',
 'gene_2910',
 'gene_3569',
 'gene_4481',
 'gene_4773',
 'gene_5027',
 'gene_5407',
 'gene_5523',
 'gene_5578',
 'gene_5815',
 'gene_5934',
 'gene_6611',
 'gene_6748',
 'gene_6795',
 'gene_6876',
 'gene_6940',
 'gene_7623',
 'gene_7964',
 'gene_8027',
 'gene_8032',
 'gene_8594',
 'gene_8598',
 'gene_8729',
 'gene_8739',
 'gene_9652',
 'gene_10106',
 'gene_10357',
 'gene_10548',
 'gene_10707',
 'gene_11346',
 'gene_11412',
 'gene_11920',
 'gene_12167',
 'gene_12194',
 'gene_12866',
 'gene_13103',
 'gene_13147',
 'gene_13928',
 'gene_14062',
 'gene_14092',
 'gene_15306',
 'gene_15589',
 'gene_15830',
 'gene_16215',
 'gene_16372',
 'gene_16385',
 'gene_16557',
 'gene_17012',
 'gene_17018',
 'gene_17317',
 'gene_17354',
 'gene_17801',
 'gene_17847',
 'gene_17892',
 'gene_17905',
 'gene_17947',
 'gene_18631',
 'gene_18746']

23. Filter the feature matrix X to keep only these features, make a new train/test splitting from this X matrix and do the preprocessing once again

In [29]:
X = X.loc[:, best_features]
X.head()

,gene_221,gene_357,gene_747,gene_864,gene_1063,gene_1384,gene_2073,gene_2655,gene_2747,gene_2910,gene_3569,gene_4481,gene_4773,gene_5027,gene_5407,gene_5523,gene_5578,gene_5815,gene_5934,gene_6611,gene_6748,gene_6795,gene_6876,gene_6940,gene_7623,gene_7964,gene_8027,gene_8032,gene_8594,gene_8598,gene_8729,gene_8739,gene_9652,gene_10106,gene_10357,gene_10548,gene_10707,gene_11346,gene_11412,gene_11920,gene_12167,gene_12194,gene_12866,gene_13103,gene_13147,gene_13928,gene_14062,gene_14092,gene_15306,gene_15589,gene_15830,gene_16215,gene_16372,gene_16385,gene_16557,gene_17012,gene_17018,gene_17317,gene_17354,gene_17801,gene_17847,gene_17892,gene_17905,gene_17947,gene_18631,gene_18746
0,10.007966,0.000000,9.467555,0.000000,5.634797,6.909077,7.025970,9.148459,3.877077,2.717803,8.282532,4.974043,9.840658,0.000000,7.974615,8.518295,2.185898,3.877077,8.338077,8.450894,8.835839,3.926037,8.440400,13.221398,5.663951,5.248778,0.000000,1.822037,1.010279,7.210184,5.323766,8.347608,5.748037,1.010279,3.340391,11.986820,3.266292,2.602077,8.514300,6.896841,6.403961,7.748327,6.915150,11.422175,4.801122,6.795105,9.373618,5.663951,9.456143,0.00000,8.003417,10.898541,10.314527,9.113101,9.968854,10.841863,3.105561,7.627724,10.543564,8.803453,3.105561,0.0,0.000000,12.365904,8.034441,7.689285
1,6.375557,0.000000,6.997394,1.004394,8.882967,6.058490,8.614231,8.858941,2.530820,0.000000,6.799851,2.530820,0.000000,0.323658,3.137061,7.717813,0.587845,3.866146,9.401078,6.178577,10.269092,5.815972,6.484409,7.993159,0.000000,3.890826,0.000000,1.004394,2.328951,2.762370,2.814879,4.768274,1.465034,0.000000,1.004394,9.550341,5.064008,4.293724,3.708540,0.000000,3.890826,8.309099,7.508571,1.813607,2.914488,5.095979,9.685443,3.841047,10.348341,0.00000,9.320507,10.983364,6.451617,9.542481,9.624850,10.189923,0.587845,5.330483,10.294173,5.374883,0.323658,0.0,0.000000,14.094201,7.101471,8.292989
2,7.716408,0.452595,6.179666,0.000000,5.213829,11.596180,7.202535,8.390565,0.452595,0.000000,9.650298,3.065210,10.485527,0.000000,4.947105,0.452595,0.000000,1.306846,8.649289,3.186960,10.629065,4.306933,3.352236,13.047345,1.306846,1.074163,3.634977,4.981168,0.000000,3.677147,1.683023,7.060091,2.533663,1.839758,3.000252,11.916812,2.866690,11.369221,4.009723,8.497401,5.094422,7.468746,3.244187,0.000000,1.507160,6.464881,8.848247,5.726766,9.644994,0.00000,8.504736,10.389717,9.306825,11.194683,9.898288,9.708642,3.500522,2.337254,10.946307,1.074163,3.065210,0.0,0.000000,11.461280,6.365222,10.833428
3,8.309085,0.000000,9.121088,4.737725,5.535459,12.718734,8.331741,9.807848,2.175652,1.267356,8.110885,4.321690,10.071087,0.000000,7.073392,8.906247,0.000000,4.598014,8.806218,5.942700,9.199147,4.489235,5.967242,13.604530,0.000000,2.650029,1.039419,1.267356,0.434882,7.226961,2.650029,7.809479,2.566840,4.679497,5.134369,12.555325,6.002820,5.524474,6.007245,7.992321,5.883750,6.434378,6.253292,6.589990,3.127534,3.573556,9.367646,6.343552,11.908640,0.00000,8.914687,10.184020,14.117408,10.302433,9.347533,10.865068,2.728704,5.866458,10.183586,5.785961,5.060251,0.0,0.000000,13.686227,7.092112,9.562801
4,3.370332,3.208502,11.227267,0.000000,7.181162,3.335812,9.977938,9.898096,8.711374,10.517246,11.873982,0.649386,0.000000,2.396187,12.870781,2.678342,6.416654,8.837760,9.111107,3.452793,6.741925,4.836651,13.636772,9.304625,5.024776,0.000000,10.271988,8.453908,7.408185,10.982102,7.912446,9.180951,10.828644,0.000000,1.435949,4.461804,1.942120,2.544139,0.889707,1.711142,4.345574,6.783470,10.565407,3.525831,2.801097,4.283751,9.063794,14.189315,9.379807,14.97592,10.729952,8.747129,6.291349,10.597187,9.745926,11.752414,7.939432,9.407247,9.273817,1.435949,6.322429,0.0,12.010059,9.842449,9.854462,14.439409

In [30]:
# Divide dataset Train set & Test set 
print("Dividing into train and test sets...")
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print("...Done.")
print()

Dividing into train and test sets...
...Done.

In [31]:
# Create scaler for numeric features
scaler = StandardScaler()

# Preprocessings on train set
print("Performing preprocessings on train set...")
print(X_train.head())
X_train = scaler.fit_transform(X_train)
print('...Done.')
print(X_train[0:5]) # MUST use this syntax because X_train is a numpy array and not a pandas DataFrame anymore
print()

# Preprocessings on test set
print("Performing preprocessings on test set...")
print(X_test.head()) 
X_test = scaler.transform(X_test) # Don't fit again !!
print('...Done.')
print(X_test[0:5,:]) # MUST use this syntax because X_test is a numpy array and not a pandas DataFrame anymore
print()

Performing preprocessings on train set...
      gene_221   gene_357   gene_747  gene_864  gene_1063  gene_1384  \
364   9.598170   0.000000   7.659989  2.125056   8.459862   6.481825
458   9.221942   0.000000   9.757558  1.594978   8.673161   5.130033
76    6.082534  10.392221  10.898480  0.000000   7.825843   5.664523
64   12.108841   0.444349   8.225516  0.783582   6.487625   7.464913
638   5.269875  10.237043  12.303344  0.000000   6.024218   3.375470

     gene_2073  gene_2655  gene_2747  gene_2910  gene_3569  gene_4481  \
364   6.615035   9.405637   3.269856   0.000000  10.862041   8.628675
458   6.724500   8.778718   2.951644   0.000000  10.361856   1.747473
76    9.570061   9.050831   6.818557   5.426466  11.128014   0.000000
64    7.161112   9.186951   2.508251   1.058109  10.101529   5.559856
638   8.899227  10.065632  11.303256   5.792980  11.749015   0.333996

     gene_4773  gene_5027  gene_5407  gene_5523  gene_5578  gene_5815  \
364   0.000000   0.565890  10.411204   9.201869   2.651545   4.032965
458   9.137355   0.000000   9.187387  10.616126   0.742955   1.885379
76    0.000000   3.747420  12.312157   2.280273   5.367773   9.625915
64    9.743123   0.444349   7.580892   8.675858   0.444349   3.913416
638   0.000000   2.805602  12.606852   3.301149   4.143402  11.646887

     gene_5934  gene_6611  gene_6748  gene_6795  gene_6876  gene_6940  \
364   9.523968   4.468160   8.602172   0.971295   5.419091  12.699221
458  11.524263   6.691967  10.409433   5.984373   6.856152  11.249599
76    8.425925   4.619108   7.167268   6.487470  14.025122   7.876720
64    8.990864   7.426097  11.120413   2.203890   7.097937  11.601372
638   7.794377   4.414075   6.866203   2.909293  14.193964   7.967514

     gene_7623  gene_7964  gene_8027  gene_8032  gene_8594  gene_8598  \
364   0.000000  13.232343   1.546561   7.351770   4.032965   9.980325
458   0.000000  12.029467   2.127006   6.644191   4.184082   6.677804
76    5.382671   2.716376   8.260284   7.386380   8.434833   9.994155
64    0.000000   9.254114   1.958175   1.958175   0.000000   5.866762
638   4.940035   0.000000   7.677452   6.959747   5.680234  10.591681

     gene_8729  gene_8739  gene_9652  gene_10106  gene_10357  gene_10548  \
364   4.115241  10.352529   3.701294    6.769097    2.856787   12.401983
458   6.729090   8.755215   1.747473    2.514854    0.742955   11.800160
76    7.860851   9.261291  10.345926    0.000000    1.192762    8.981570
64    5.624575   8.304621   4.590117    1.058109    1.288595   12.843085
638   9.238550   9.594386  10.193414    0.000000    0.333996    8.453653

     gene_10707  gene_11346  gene_11412  gene_11920  gene_12167  gene_12194  \
364    2.651545    7.347524    3.531918    0.000000    4.898131    7.884787
458    3.294400    4.014052    3.013123    6.330702    2.887428    7.392833
76     2.402258    4.075481    1.440686    1.440686    4.893285    5.412016
64     3.594262    4.406006    3.375554    6.813294    2.973354    6.995620
638    2.329812    0.333996    0.605020    0.000000    3.480213    7.061722

     gene_12866  gene_13103  gene_13147  gene_13928  gene_14062  gene_14092  \
364    7.560715    8.112158    5.031232    8.178242    8.664977    6.914050
458    7.321712    4.157100    4.821807    7.037239    9.169777    7.931795
76     9.927772    2.619084    1.440686    3.920760    9.505651   12.485532
64     7.827629    7.542328    3.375554    3.159597    9.732763   10.073793
638    8.611877    0.000000    2.909293    2.805602    8.416738   13.388179

     gene_15306  gene_15589  gene_15830  gene_16215  gene_16372  gene_16385  \
364   10.474426    0.000000   10.934642    9.242476   10.684792    9.047129
458   10.941767    0.000000   10.621072    7.854127   13.314484    8.686525
76     9.522927   13.841810   10.649463    9.292855    3.440766   10.637594
64    11.702428    0.444349    8.838161   10.296205   13.553125    9.910470
638    9.064172    6.320699   10.571819    8.027801    3.096684    9.977995

     gene_16557  gene_17012  gene_17018  gene_17317  gene_17354  gene_17801  \
364    9.747841   11.680984    1.766171    7.902267   10.498580    8.297563
458    9.974013   11.095351    7.191474    6.796208    9.938793    5.517156
76    10.295161   11.178783    4.147038    8.898483    9.478543    1.192762
64    10.190615   11.131587    5.944872    6.315358    9.852433    6.577551
638   10.194055   11.610093    4.641899   10.746044    8.939588    0.000000

     gene_17847  gene_17892  gene_17905  gene_17947  gene_18631  gene_18746
364    2.949404         0.0    4.371043   15.436341    8.551358    8.903599
458    1.424438         0.0    4.968699   12.982331    9.098880    8.434199
76     7.833997         0.0   11.253883   10.707566    9.738781   13.425570
64     3.689713         0.0    0.000000   13.312344    5.384088    7.607819
638    7.151696         0.0    6.218421   10.154704    9.153995   11.830733
...Done.
[[ 0.92491279 -0.71109384 -1.33278237  0.06998231  0.94434149  0.08458301
  -1.265205    0.12422346 -0.49566864 -0.76500185  0.64240781  1.92605334
  -0.96268059 -0.80706168  0.39741874  1.39897484 -0.04439636 -0.91642602
  -0.11648056 -0.71095563 -0.12796472 -1.28897461 -0.85443414  1.19282614
  -1.16259893  1.62390189 -0.70899199  0.87815149  0.28060995  0.94143388
  -0.79709989  1.64987321 -0.41625844  2.55196244  0.70376393  1.03409235
  -0.33023975  0.5753063   0.31347946 -1.00907543  0.00750293  0.80711811
  -0.33993624  1.14634959  0.30710126  2.15182358 -0.91043589 -0.68274758
   0.1040995  -0.67639707  1.10622301  0.02358693  0.67240857 -0.74538962
  -0.49179327  0.5566136  -1.00023781  0.17297272  1.03529885  1.03474029
  -0.62818505 -0.08071537  0.22402833  2.15541773  0.3192084  -0.378237  ]
 [ 0.76464402 -0.71109384 -0.03889303 -0.12700068  1.09032813 -0.50968127
  -1.17412523 -0.82487453 -0.59006953 -0.76500185  0.31429661 -0.71692563
   0.91769039 -1.1115359  -0.04000096  1.88059021 -0.71811293 -1.78550631
   1.3225791   0.26960813  0.96685732  0.81231759 -0.45944758  0.63207043
  -1.16259893  1.35937823 -0.52721114  0.60993489  0.33365724 -0.39947515
   0.47126317  0.25167964 -0.90560691  0.5179801  -0.50169769  0.77314239
   0.17715712 -0.19465422  0.03041885  0.91281558 -1.20774186  0.44442061
  -0.45651343  0.01260974  0.20317633  1.43268038 -0.17201493 -0.33385497
   0.52196947 -0.67639707  0.78367381 -1.21804102  1.35481014 -1.05110186
   0.02045136 -0.30146141  0.95278021 -0.32952925  0.32037943  0.21120533
  -1.17890853 -0.08071537  0.36143295  0.6402681   0.64300566 -0.55519799]
 [-0.57270929  1.9126419   0.6648867  -0.7197133   0.51040405 -0.27471314
   1.19350668 -0.41292049  0.55708918  0.67121113  0.81688087 -1.38810712
  -0.96268059  0.90474555  1.07686206 -0.95812629  0.91440926  1.34691695
  -0.90643853 -0.6443967  -0.99721617  1.02319696  1.51099553 -0.67265736
   1.12819257 -0.68865679  1.3935791   0.89127093  1.82581682  0.94704928
   1.02044689  0.69466861  1.24793766 -0.68438888 -0.24518451 -0.44899438
  -0.52699882 -0.18046531 -0.82752054 -0.57170806  0.00457382 -1.01595248
   0.81462894 -0.42827133 -1.47467021 -0.53155336  0.31930039  1.22720901
  -0.74667802  1.80969927  0.81287759  0.06864192 -1.20740683  0.6029705
   0.74779938 -0.17921565 -0.14316564  0.62557185 -0.26741841 -1.06964657
   1.13582822 -0.08071537  1.80643354 -0.76421195  1.02143566  1.32651903]
 [ 1.99443131 -0.59890854 -0.98393597 -0.42852493 -0.40550377  0.51676043
  -0.81084517 -0.20684701 -0.72160641 -0.48495414  0.14352737  0.74736025
   1.042351   -0.87245601 -0.61419835  1.21984553 -0.82351826 -0.96480475
  -0.50000791  0.59331491  1.39756199 -0.77231749 -0.39299103  0.7681461
  -1.16259893  0.74905252 -0.58008492 -1.16635826 -1.13509932 -0.72877922
  -0.06470006 -0.14274362 -0.19364632 -0.17849996 -0.19053379  1.22535335
   0.41383405 -0.10412121  0.22816543  1.05932212 -1.15580902  0.15157256
  -0.20974542  0.98300449 -0.51451207 -1.01129425  0.6515193   0.40044216
   1.20211062 -0.59658854 -1.05029282  0.9659569   1.41673721 -0.01346854
   0.51102012 -0.24836798  0.50402464 -0.5479882   0.21008636  0.52528617
  -0.36083127 -0.08071537 -0.78090006  0.84402438 -1.5538762  -0.86673835]
 [-0.9188934   1.87346388  1.53147921 -0.7197133  -0.72267027 -1.28100829
   0.63534349  1.12339398  1.88752037  0.76821579  1.22424524 -1.25982361
  -0.96268059  0.39800503  1.18219258 -0.61047435  0.4822164   2.16475949
  -1.36078926 -0.73480385 -1.1795981  -0.47663934  1.55740295 -0.63753523
   0.9398129  -1.28601317  1.21105043  0.72955039  0.85885817  1.18966025
   1.6889717   0.98624023  1.20973997 -0.68438888 -0.73491584 -0.67789839
  -0.58417936 -1.04466808 -1.28346974 -1.00907543 -0.84946936  0.20030681
   0.17278268 -1.17904679 -0.7458892  -1.23440778 -1.27355883  1.53664465
  -1.15687135  0.45884954  0.73301041 -1.06272067 -1.29669584  0.04377765
   0.51881156  0.45274374  0.03497587  1.46495156 -0.95573288 -1.42293351
   0.88942343 -0.08071537  0.64875131 -1.10555881  0.67560042  0.72527508]]

Performing preprocessings on test set...
      gene_221   gene_357   gene_747  gene_864  gene_1063  gene_1384  \
8     4.265669   2.707635  10.468665  0.000000   6.461674   3.994381
253   4.000550  10.630395  12.430233  0.000000   5.729501   5.221862
85   10.487106   0.000000  10.039933  5.046417   8.366134   8.626472
406   7.607789   0.000000   9.433414  0.000000   5.834249   0.000000
14    2.314465   2.671429  11.433278  0.000000   5.229584   1.052485

     gene_2073  gene_2655  gene_2747  gene_2910  gene_3569  gene_4481  \
8     8.689631  10.184789   5.164094   6.916226  10.300067   1.252839
253   9.742018   9.596193   9.331951   4.548258  11.917984   0.000000
85    6.844235   9.190807   4.867170   1.347325   9.875325   5.666953
406   8.256808   9.525947  10.747220   7.956852  10.022423   0.000000
14    9.644110   9.343774  11.253487   2.499399  10.825611   0.779134

     gene_4773  gene_5027  gene_5407  gene_5523  gene_5578  gene_5815  \
8      0.00000   3.259333  12.194458   0.635336   5.023934   6.899611
253    0.00000   4.510443  13.379297   5.397878   4.690328  10.808948
85    10.12918   0.000000   6.819783   7.191543   0.471031   2.763730
406    0.00000   3.305474   7.643293   0.000000   7.360856   0.000000
14     0.00000   3.028711  13.150088   2.405039   4.345822   8.424763

     gene_5934  gene_6611  gene_6748  gene_6795  gene_6876  gene_6940  \
8     8.378347   2.984699   8.834793   1.913148  11.602439   6.328969
253   7.558604   4.260011   5.536037   0.000000  14.125906   7.900221
85    9.846150   7.683928  10.084224   4.039489   9.379086  10.455019
406   9.554057   1.609140   6.522250   0.000000  10.442332   4.230595
14    6.524612   2.671429   8.781209   8.913497  14.308474   6.381088

     gene_7623  gene_7964  gene_8027  gene_8032  gene_8594  gene_8598  \
8     5.427841   0.000000   8.138400   6.996547   7.513672   9.551474
253   5.478438   0.000000   9.999154   6.707511   6.682222  11.605484
85    4.105695   7.985899   0.000000   0.825541   0.000000   7.651052
406   0.000000   0.000000   8.921770   8.591922  10.700570  10.171827
14    3.719545   1.480369   0.779134   6.896671   4.703915  10.560457

     gene_8729  gene_8739  gene_9652  gene_10106  gene_10357  gene_10548  \
8    11.749006   9.325263   6.824131    1.074848    3.657446    5.822773
253   9.174616   8.735221  11.258654    0.000000    0.000000    8.994580
85    6.537481   7.989082   1.729705    3.413120    3.059338   12.175219
406   6.264491  10.116240   8.639684    0.000000    1.900838    2.970081
14    7.172077   9.816667  11.780249    0.000000    0.000000    3.795912

     gene_10707  gene_11346  gene_11412  gene_11920  gene_12167  gene_12194  \
8      3.082175    0.352307    3.525042    0.871765    4.694674    5.291836
253    4.348409    5.334361    1.774545    3.244065    5.418446    5.458717
85     3.820424    5.504668    6.066589    7.996841    7.744921    7.117259
406    2.838387    0.000000    1.243182    0.751549    2.143361    4.471903
14     0.441483    1.052485    4.371008    0.000000    3.415083    6.997123

     gene_12866  gene_13103  gene_13147  gene_13928  gene_14062  gene_14092  \
8      6.510642   10.332305    2.110864    4.091217    9.504994   12.501949
253    8.113893    3.333409    2.937081    4.165848    8.129572   12.709588
85     6.418797   11.754654    2.391520    5.467384    9.967226    6.784844
406   13.527868    5.527208    1.900838    5.726619    9.844001    9.917224
14     6.765124    1.052485    2.405039    2.587965    7.846393   11.766380

     gene_15306  gene_15589  gene_15830  gene_16215  gene_16372  gene_16385  \
8     10.997871    0.352307   11.246770    9.262748    4.114442   13.534789
253    9.535120   10.551708    9.806828    8.452340    3.572393   11.252920
85    10.957566    0.000000    9.107424   10.158231   13.228273    8.895227
406    7.519762    3.806128   10.055242   11.939645    3.090752   13.323139
14     7.631388    7.350418   11.227869    8.485113    0.779134   10.359233

     gene_16557  gene_17012  gene_17018  gene_17317  gene_17354  gene_17801  \
8     10.039920   13.387748   11.818279   10.651473    9.011440    0.000000
253    9.911188   12.909422    4.819653    9.925629    9.136332    0.682843
85     9.907000   10.983386    0.000000    8.340589   10.110653    8.727172
406   10.261331   10.999746   10.718833    5.295745    8.690696    0.000000
14    11.053654   11.037279    4.444018   10.534225    8.438230    0.441483

     gene_17847  gene_17892  gene_17905  gene_17947  gene_18631  gene_18746
8      6.729526         0.0    7.579829    9.945131    8.720234   13.449303
253    9.018350         0.0    5.047988   10.348352    9.635154   13.046208
85     5.063175         0.0    0.825541   12.577658    5.917897    9.310561
406    8.746870         0.0    0.751549    7.546385    6.838889   12.614595
14     3.903376         0.0    2.671429    8.433757    8.400512   13.493805
...Done.
[[-1.34667383e+00 -2.74941136e-02  3.99754162e-01 -7.19713302e-01
  -4.23264804e-01 -1.00892787e+00  4.60950481e-01  1.30378672e+00
   6.62762647e-02  1.06550316e+00  2.73763878e-01 -9.06907975e-01
  -9.62680585e-01  6.42132710e-01  1.03479395e+00 -1.51829808e+00
   7.93036977e-01  2.43641993e-01 -9.40667362e-01 -1.36507175e+00
   1.29552367e-02 -8.94185652e-01  8.45103645e-01 -1.27137206e+00
   1.14741634e+00 -1.28601317e+00  1.35540786e+00  7.43499873e-01
   1.50245793e+00  7.67309054e-01  2.90716345e+00  7.50665611e-01
   3.65878713e-01 -1.70496799e-01  1.16035835e+00 -1.81864447e+00
   9.65022983e-03 -1.04043876e+00  3.09727635e-01 -7.44422791e-01
  -1.15463954e-01 -1.10455642e+00 -8.52123832e-01  1.78276744e+00
  -1.14210131e+00 -4.24118673e-01  3.18339225e-01  1.23283678e+00
   5.72134939e-01 -6.13120081e-01  1.42728959e+00  4.17162427e-02
  -1.03258884e+00  3.05914753e+00  1.69719690e-01  3.05738227e+00
   2.61835236e+00  1.42198641e+00 -8.63969084e-01 -1.42293351e+00
   7.36961369e-01 -8.07153721e-02  9.61746976e-01 -1.23495324e+00
   4.19079367e-01  1.33546640e+00]
 [-1.45961183e+00  1.97277389e+00  1.60975083e+00 -7.19713302e-01
  -9.24381199e-01 -4.69312306e-01  1.33658283e+00  4.12708115e-01
   1.30271311e+00  4.38777344e-01  1.33508559e+00 -1.38810712e+00
  -9.62680585e-01  1.31528666e+00  1.45828194e+00  1.03552299e-01
   6.75276753e-01  1.82566413e+00 -1.53040959e+00 -8.02736728e-01
  -1.98540009e+00 -1.69610477e+00  1.53869661e+00 -6.63566393e-01
   1.16894982e+00 -1.28601317e+00  1.93814990e+00  6.33937181e-01
   1.21059033e+00  1.60129045e+00  1.65794776e+00  2.34178226e-01
   1.47653698e+00 -6.84388875e-01 -9.25384873e-01 -4.43353437e-01
   1.00907289e+00  1.10308854e-01 -6.45363692e-01 -2.42336823e-02
   3.21975291e-01 -9.81522008e-01 -7.01158188e-02 -2.23505956e-01
  -7.32099888e-01 -3.77081253e-01 -1.69362609e+00  1.30401731e+00
  -7.35775623e-01  1.21877150e+00 -5.38865387e-02 -6.83047122e-01
  -1.17324997e+00  1.12462981e+00 -1.21836718e-01  2.35653472e+00
   9.89644316e-02  1.09222221e+00 -7.04465207e-01 -1.22068073e+00
   1.56354357e+00 -8.07153721e-02  3.79661862e-01 -9.85997241e-01
   9.60151727e-01  1.18350196e+00]
 [ 1.30359005e+00 -7.11093838e-01  1.35290530e-01  1.15559417e+00
   8.80192069e-01  1.02739575e+00 -1.07450061e+00 -2.01008927e-01
  -2.18093449e-02 -4.08407640e-01 -4.85786739e-03  7.88494690e-01
   1.12179748e+00 -1.11153590e+00 -8.86235637e-01  7.14372293e-01
  -8.14099629e-01 -1.43005709e+00  1.15305131e-01  7.07002716e-01
   7.69848395e-01 -2.90388289e-03  2.33999050e-01  3.24703648e-01
   5.84728993e-01  4.70160124e-01 -1.19333646e+00 -1.59569702e+00
  -1.13509932e+00 -4.31147414e-03  3.78285156e-01 -4.18947036e-01
  -9.10057113e-01  9.47447009e-01  8.19273573e-01  9.35767554e-01
   5.92340899e-01  1.49646153e-01  1.69642510e+00  1.41862637e+00
   1.72806873e+00  2.41251522e-01 -8.96922618e-01  2.19049178e+00
  -1.00282866e+00  4.43242280e-01  9.94492205e-01 -7.27040616e-01
   5.36096811e-01 -6.76397068e-01 -7.73319260e-01  8.42564059e-01
   1.33243849e+00 -8.74169141e-01 -1.31321718e-01 -4.65514110e-01
  -1.63602979e+00  3.72110415e-01  5.39866509e-01  1.16198710e+00
   1.35178442e-01 -8.07153721e-02 -5.91103252e-01  3.90415929e-01
  -1.23818796e+00 -2.24814835e-01]
 [ 7.70324001e-02 -7.11093838e-01 -2.38841802e-01 -7.19713302e-01
  -8.52689607e-01 -2.76490608e+00  1.00822365e-01  3.06362162e-01
   1.72256666e+00  1.34092392e+00  9.16354107e-02 -1.38810712e+00
  -9.62680585e-01  6.66959039e-01 -5.91894565e-01 -1.73465749e+00
   1.61795090e+00 -2.54847743e+00 -9.48333344e-02 -1.97160938e+00
  -1.38796152e+00 -1.69610477e+00  5.26239848e-01 -2.08308410e+00
  -1.16259893e+00 -1.28601317e+00  1.60073977e+00  1.34824694e+00
   2.62116847e+00  1.01918866e+00  2.45817752e-01  1.44303988e+00
   8.20597058e-01 -6.84388875e-01  1.58611996e-01 -3.05556837e+00
  -1.82768071e-01 -1.12181401e+00 -9.35281486e-01 -7.80918095e-01
  -1.65744701e+00 -1.70905852e+00  2.57062602e+00  4.05358923e-01
  -1.24632481e+00  6.06631114e-01  8.14238664e-01  3.46768800e-01
  -2.53779618e+00  7.21303528e-03  2.01640474e-01  2.43571733e+00
  -1.29823511e+00  2.87971542e+00  6.71180926e-01 -4.41542069e-01
   2.22257021e+00 -1.01121652e+00 -1.27359920e+00 -1.42293351e+00
   1.46550172e+00 -8.07153721e-02 -6.08114449e-01 -2.71598148e+00
  -6.93524923e-01  1.02078627e+00]
 [-2.17786571e+00 -3.66350742e-02  9.94777261e-01 -7.19713302e-01
  -1.26653609e+00 -2.30222069e+00  1.25511941e+00  3.05686694e-02
   1.87275602e+00 -1.03490302e-01  6.18510528e-01 -1.08885216e+00
  -9.62680585e-01  5.18047540e-01  1.37635759e+00 -9.15638123e-01
   5.53669168e-01  8.60837128e-01 -2.27428810e+00 -1.50320453e+00
  -1.95057427e-02  2.04009536e+00  1.58887683e+00 -1.25121110e+00
   4.20388823e-01 -9.60466386e-01 -9.49331195e-01  7.05640829e-01
   5.16136406e-01  1.17698239e+00  6.86221368e-01  1.18081149e+00
   1.60717401e+00 -6.84388875e-01 -9.25384873e-01 -2.69748878e+00
  -2.07461277e+00 -8.78712464e-01  7.71296799e-01 -1.00907543e+00
  -8.88833652e-01  1.52680532e-01 -7.27997028e-01 -8.77345828e-01
  -9.96119974e-01 -1.37157859e+00 -2.10785914e+00  9.80676702e-01
  -2.43798640e+00  6.43794908e-01  1.40784664e+00 -6.53737846e-01
  -1.89809703e+00  3.66982716e-01  2.46566734e+00 -3.86548519e-01
  -3.62579436e-02  1.36871844e+00 -1.59603048e+00 -1.29216953e+00
  -2.83669434e-01 -8.07153721e-02 -1.66722829e-01 -2.16810260e+00
   2.29999921e-01  1.35224338e+00]]

24. Train a NON-regularized linear regression and evaluate the performances. What do you think of the result?

In [33]:
# Train linear regression (no regularization)
print("Train model...")
regressor = LinearRegression()
regressor.fit(X_train, Y_train)
print("...Done.")

Train model...
...Done.

In [34]:
# Print R^2 scores
print("R2 score on training set : ", regressor.score(X_train, Y_train))
print("R2 score on test set : ", regressor.score(X_test, Y_test))

R2 score on training set :  0.9910017735998236
R2 score on test set :  0.989466602650973