In [6]:
import pandas as pd
import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [7]:
df = pd.read_csv("data/speed_dating_data.csv", encoding='latin1')
pd.set_option('display.max_columns', None)
df.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [8]:
df.describe(include='all')

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8315,8296.000000,4914,3133,3583,8315.000000,8299.000000,8299.000000,8299,7314,4279,8299.000000,8281.000000,8299.000000,8289,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,259,NaN,241,68,115,NaN,NaN,NaN,269,409,261,NaN,NaN,NaN,367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Business,NaN,UC Berkeley,"1,400.00","26,908.00",NaN,NaN,NaN,New York,0,"55,080.00",NaN,NaN,NaN,Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,521,NaN,107,403,241,NaN,NaN,NaN,522,355,124,NaN,NaN,NaN,202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,NaN,7.662488,NaN,NaN,NaN,2.757186,3.784793,3.651645,NaN,NaN,NaN,2.122063,5.006762,2.158091,NaN,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,NaN,3.758935,NaN,NaN,NaN,1.230905,2.845708,2.805237,NaN,NaN,NaN,1.407181,1.444531,1.105246,NaN,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,NaN,1.000000,NaN,NaN,NaN,1.000000,0.000000,1.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,NaN,5.000000,NaN,NaN,NaN,2.000000,1.000000,1.000000,NaN,NaN,NaN,1.000000,4.000000,1.000000,NaN,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,NaN,8.000000,NaN,NaN,NaN,2.000000,3.000000,3.000000,NaN,NaN,NaN,2.000000,5.000000,2.000000,NaN,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,NaN,10.000000,NaN,NaN,NaN,4.000000,6.000000,6.000000,NaN,NaN,NaN,2.000000,6.000000,3.000000,NaN,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,NaN,18.000000,NaN,NaN,NaN,6.000000,10.000000,10.000000,NaN,NaN,NaN,6.000000,7.000000,7.000000,NaN,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [9]:
df.shape

(8378, 195)

In [10]:
# precent of missing values
df_missing_values = df.isna().sum() / len(df) * 100
df_missing_values_sort = df_missing_values[df_missing_values >= 50].sort_values(ascending=False).reset_index()
df_missing_values_sort.columns = ['col_name', 'percent_missing']

In [11]:
fig = px.scatter(df_missing_values.values)
fig.update_layout(
    title='Percentage of Missing Values in Each Column',
    xaxis_title='Row Index',
    yaxis_title='% Missing Value',
    showlegend=False,
)
fig.show()

In [12]:
def color_code(percent):
    if percent > 70:
        return '#FB2C36'
    elif percent > 50:
        return '#FE9A00'
    else:
        return '#7CCF00'

df_missing_values_sort['color'] = df_missing_values_sort['percent_missing'].apply(color_code)

fig = px.bar(
    df_missing_values_sort,
    x='col_name',
    y='percent_missing',
    color='color',
    color_discrete_map='identity',
    title='Percent of Missing Values in Each Column'
)

fig.update_layout(
    xaxis_title='Column',
    yaxis_title='Percent Missing',
    xaxis_tickangle=-45
)

fig.show()

In [13]:
# Columns name and type
df_type = df.dtypes.reset_index().rename(columns={"index": "c_name", 0: "type"})
pd.set_option('display.max_rows', 200)
df_type

       c_name     type
0         iid    int64
1          id  float64
2      gender    int64
3         idg    int64
4      condtn    int64
5        wave    int64
6       round    int64
7    position    int64
8    positin1  float64
9       order    int64
10    partner    int64
11        pid  float64
12      match    int64
13   int_corr  float64
14   samerace    int64
15      age_o  float64
16     race_o  float64
17   pf_o_att  float64
18   pf_o_sin  float64
19   pf_o_int  float64
20   pf_o_fun  float64
21   pf_o_amb  float64
22   pf_o_sha  float64
23      dec_o    int64
24     attr_o  float64
25     sinc_o  float64
26    intel_o  float64
27      fun_o  float64
28      amb_o  float64
29     shar_o  float64
30     like_o  float64
31     prob_o  float64
32      met_o  float64
33        age  float64
34      field   object
35   field_cd  float64
36   undergra   object
37     mn_sat   object
38    tuition   object
39       race  float64
40    imprace  float64
41   imprelig  float64
42       from   object
43    zipcode   object
44     income   object
45       goal  float64
46       date  float64
47     go_out  float64
48     career   object
49   career_c  float64
50     sports  float64
51   tvsports  float64
52   exercise  float64
53     dining  float64
54    museums  float64
55        art  float64
56     hiking  float64
57     gaming  float64
58   clubbing  float64
59    reading  float64
60         tv  float64
61    theater  float64
62     movies  float64
63   concerts  float64
64      music  float64
65   shopping  float64
66       yoga  float64
67   exphappy  float64
68     expnum  float64
69    attr1_1  float64
70    sinc1_1  float64
71   intel1_1  float64
72     fun1_1  float64
73     amb1_1  float64
74    shar1_1  float64
75    attr4_1  float64
76    sinc4_1  float64
77   intel4_1  float64
78     fun4_1  float64
79     amb4_1  float64
80    shar4_1  float64
81    attr2_1  float64
82    sinc2_1  float64
83   intel2_1  float64
84     fun2_1  float64
85     amb2_1  float64
86    shar2_1  float64
87    attr3_1  float64
88    sinc3_1  float64
89     fun3_1  float64
90   intel3_1  float64
91     amb3_1  float64
92    attr5_1  float64
93    sinc5_1  float64
94   intel5_1  float64
95     fun5_1  float64
96     amb5_1  float64
97        dec    int64
98       attr  float64
99       sinc  float64
100     intel  float64
101       fun  float64
102       amb  float64
103      shar  float64
104      like  float64
105      prob  float64
106       met  float64
107  match_es  float64
108   attr1_s  float64
109   sinc1_s  float64
110  intel1_s  float64
111    fun1_s  float64
112    amb1_s  float64
113   shar1_s  float64
114   attr3_s  float64
115   sinc3_s  float64
116  intel3_s  float64
117    fun3_s  float64
118    amb3_s  float64
119   satis_2  float64
120    length  float64
121  numdat_2  float64
122   attr7_2  float64
123   sinc7_2  float64
124  intel7_2  float64
125    fun7_2  float64
126    amb7_2  float64
127   shar7_2  float64
128   attr1_2  float64
129   sinc1_2  float64
130  intel1_2  float64
131    fun1_2  float64
132    amb1_2  float64
133   shar1_2  float64
134   attr4_2  float64
135   sinc4_2  float64
136  intel4_2  float64
137    fun4_2  float64
138    amb4_2  float64
139   shar4_2  float64
140   attr2_2  float64
141   sinc2_2  float64
142  intel2_2  float64
143    fun2_2  float64
144    amb2_2  float64
145   shar2_2  float64
146   attr3_2  float64
147   sinc3_2  float64
148  intel3_2  float64
149    fun3_2  float64
150    amb3_2  float64
151   attr5_2  float64
152   sinc5_2  float64
153  intel5_2  float64
154    fun5_2  float64
155    amb5_2  float64
156  you_call  float64
157  them_cal  float64
158    date_3  float64
159  numdat_3  float64
160  num_in_3  float64
161   attr1_3  float64
162   sinc1_3  float64
163  intel1_3  float64
164    fun1_3  float64
165    amb1_3  float64
166   shar1_3  float64
167   attr7_3  float64
168   sinc7_3  float64
169  intel7_3  float64
170    fun7_3  float64
171    amb7_3  float64
172   shar7_3  float64
173   attr4_3  float64
174   sinc4_3  float64
175  intel4_3  float64
176    fun4_3  float64
177    amb4_3  float64
178   shar4_3  float64
179   attr2_3  float64
180   sinc2_3  float64
181  intel2_3  float64
182    fun2_3  float64
183    amb2_3  float64
184   shar2_3  float64
185   attr3_3  float64
186   sinc3_3  float64
187  intel3_3  float64
188    fun3_3  float64
189    amb3_3  float64
190   attr5_3  float64
191   sinc5_3  float64
192  intel5_3  float64
193    fun5_3  float64
194    amb5_3  float64

In [14]:
# renaming my column name for better understanding
renames = {
    'condtn'    : 'nbr_of_partner',
    'field_cd' : 'field_c' #because carreer code is career_c 
}

# Apply the renames
df.rename(columns=renames, inplace=True)

In [15]:
# Fill data if I can 
# Apply a wave id to the only one missing NaN => df[df['iid'] == 552]
df['id'] = df['id'].fillna(22)

# num_in_3 92% missing values but th evalues is "if yes, how many?" than if no value that will say 0
df['num_in_3'] = df['num_in_3'].fillna(0)

In [16]:
# Columns to convert to Int64
col_to_convert_to_int = [
    'positin1', 
    'pid', 
    'age_o', 
    'age'
]

# Convertion apply to be an int
df['id'] = df['id'].astype(int)
df['num_in_3'] = df['num_in_3'].astype(int)
df[col_to_convert_to_int] = df[col_to_convert_to_int].astype('Int64')

In [17]:
# Mapping dictionnaires
gender_mapping = {0: 'Female', 1 : 'Male'}

wave_date_mapping = {
    1: '2002-10-16',
    2: '2002-10-23',
    3: '2002-11-12',
    4: '2002-11-12',
    5: '2002-11-20',
    6: '2003-03-26',
    7: '2003-03-26',
    8: '2003-04-02',
    9: '2003-04-02',
    10: '2003-09-24'
}

race_mapping = {
    1 : 'Black/African American',
    2 : 'European/Caucasian-American',
    3 : 'Latino/Hispanic American',
    4 : 'Asian/Pacific Islander/Asian-American',
    5 : 'Native American',
    6 : 'Other'
}

frequency_maping = {
    1 : 'Several times a week',
    2 : 'Twice a week',
    3 : 'Once a week',
    4 : 'Twice a month',
    5 : 'Once a month',
    6 : 'Several times a year',
    7 : 'Almost never'
}

# Apply mapping and category type
df['gender'] = df['gender'].map(gender_mapping).astype('category')
df['race_o'] = df['race_o'].map(race_mapping).astype('category')
df['race'] = df['race'].map(race_mapping).astype('category')
df['go_out'] = df['go_out'].map(frequency_maping).astype('category')
df['date'] = df['date'].map(frequency_maping).astype('category')
df['wave_date'] = df['wave'].map(wave_date_mapping)

# Apply dateTime to date column
df['wave_date'] = pd.to_datetime(df['wave_date'])

# Apply category type
df['field'] = df['field'].astype('category')

In [18]:
# Drop columns with more than 50% missing values
df = df.drop(df_missing_values[df_missing_values >= 50].index, axis=1)
df.shape

(8378, 137)

In [19]:
df.sample(15)

,iid,id,gender,idg,nbr_of_partner,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_c,undergra,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,satis_2,length,numdat_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,wave_date
8324,550,20,Male,40,2,21,22,8,20,11,13,521,1,-0.06,1,26,European/Caucasian-American,10.00,30.00,20.00,15.00,15.00,10.00,1,8.0,8.0,9.0,9.0,9.0,7.0,7.0,6.0,2.0,30,MBA,8.0,Oxford,European/Caucasian-American,5.0,6.0,UK,NaN,NaN,2.0,Twice a month,Several times a week,Finance,7.0,5.0,3.0,5.0,9.0,7.0,8.0,3.0,3.0,8.0,8.0,3.0,7.0,7.0,4.0,6.0,6.0,3.0,7.0,30.00,3.00,30.00,30.00,3.00,4.00,30.0,3.0,30.0,30.0,3.0,4.0,20.00,3.00,30.00,30.00,13.00,4.00,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,1,6.0,6.0,6.0,6.0,5.0,5.0,6.0,6.0,0.0,6.0,8.0,3.0,3.0,60.00,5.00,10.00,10.00,10.00,5.00,70.0,5.0,5.0,10.0,5.0,5.0,70.00,5.00,5.00,10.00,5.00,5.00,7.0,4.0,6.0,7.0,7.0,7.0,4.0,6.0,7.0,7.0,NaT
277,25,5,Female,9,2,2,16,12,<NA>,16,14,53,0,0.11,1,28,European/Caucasian-American,40.00,15.00,20.00,10.00,5.00,10.00,1,9.0,8.0,8.0,8.0,8.0,7.0,8.0,8.0,2.0,25,Social Work,11.0,NaN,European/Caucasian-American,10.0,2.0,Iowa,"52,803","23,152.00",1.0,Once a month,Twice a week,Social Worker,9.0,7.0,4.0,7.0,7.0,6.0,3.0,5.0,6.0,8.0,9.0,9.0,7.0,10.0,6.0,8.0,8.0,4.0,5.0,20.00,20.00,15.00,15.00,15.00,15.00,NaN,NaN,NaN,NaN,NaN,NaN,30.00,15.00,10.00,20.00,10.00,15.00,7.0,9.0,7.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,0,7.0,8.0,9.0,7.0,8.0,5.0,7.0,7.0,2.0,0.0,3.0,1.0,2.0,35.00,15.00,10.00,15.00,10.00,15.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,8.0,8.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,2002-10-23
2155,158,1,Male,2,2,7,16,14,9,6,4,145,0,0.42,1,24,European/Caucasian-American,11.36,18.18,22.73,18.18,11.36,18.18,0,7.0,10.0,10.0,7.0,9.0,8.0,8.0,5.0,2.0,23,physics (astrophysics),10.0,NaN,European/Caucasian-American,3.0,4.0,NYC (Staten Island),"10,301","37,248.00",4.0,Several times a year,Twice a week,"physicist, probably academia",2.0,2.0,4.0,4.0,6.0,7.0,4.0,7.0,7.0,6.0,8.0,6.0,5.0,8.0,4.0,9.0,5.0,1.0,7.0,19.05,19.05,19.05,19.05,9.52,14.29,9.0,7.0,6.0,7.0,4.0,8.0,15.22,19.57,19.57,19.57,8.70,17.39,7.0,9.0,7.0,9.0,6.0,NaN,NaN,NaN,NaN,NaN,1,9.0,8.0,9.0,7.0,7.0,8.0,9.0,6.0,0.0,4.0,8.0,1.0,2.0,17.78,20.00,20.00,17.78,11.11,13.33,9.0,8.0,6.0,7.0,5.0,7.0,15.22,19.57,19.57,17.39,10.87,17.39,6.0,9.0,9.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,2003-03-26
7068,478,14,Female,26,2,19,15,2,2,8,13,493,0,-0.05,0,20,Asian/Pacific Islander/Asian-American,30.00,10.00,10.00,30.00,10.00,10.00,1,8.0,10.0,10.0,9.0,10.0,9.0,9.0,6.0,2.0,26,International Affairs,13.0,University of Vermont,European/Caucasian-American,4.0,4.0,Washington DC,"5,401",NaN,1.0,Twice a month,Several times a week,Finance/Economics,7.0,9.0,7.0,9.0,7.0,7.0,9.0,9.0,3.0,3.0,8.0,4.0,7.0,9.0,8.0,9.0,4.0,6.0,4.0,20.00,20.00,10.00,20.00,10.00,20.00,20.0,10.0,10.0,10.0,20.0,30.0,30.00,20.00,10.00,10.00,10.00,20.00,7.0,8.0,9.0,8.0,7.0,8.0,7.0,8.0,9.0,6.0,0,9.0,9.0,9.0,9.0,10.0,9.0,9.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
163,17,7,Male,14,1,1,10,6,<NA>,10,4,4,0,0.35,1,23,European/Caucasian-American,20.00,20.00,20.00,20.00,10.00,10.00,0,7.0,10.0,10.0,7.0,10.0,5.0,5.0,1.0,2.0,30,political science,13.0,NaN,European/Caucasian-American,1.0,1.0,"Georgia, USA","30,677","38,548.00",3.0,Once a week,Twice a week,academics or journalism,2.0,8.0,2.0,9.0,7.0,7.0,5.0,4.0,2.0,6.0,4.0,2.0,7.0,9.0,7.0,7.0,2.0,2.0,4.0,35.00,15.00,25.00,10.00,5.00,10.00,NaN,NaN,NaN,NaN,NaN,NaN,25.00,20.00,20.00,20.00,10.00,5.00,7.0,7.0,6.0,8.0,4.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,3.0,5.0,6.0,5.0,6.0,4.0,2.0,1.0,5.0,3.0,2.0,30.00,16.67,20.00,20.00,6.67,6.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,5.0,7.0,NaN,NaN,NaN,NaN,NaN,2002-10-16
528,41,2,Male,4,2,2,19,13,<NA>,18,6,26,0,-0.05,0,23,European/Caucasian-American,20.00,20.00,20.00,15.00,15.00,10.00,0,2.0,5.0,5.0,3.0,5.0,2.0,2.0,2.0,2.0,30,law,1.0,NaN,Asian/Pacific Islander/Asian-American,1.0,1.0,China,"10,027",NaN,2.0,Several times a year,Once a month,law,1.0,5.0,5.0,6.0,5.0,5.0,5.0,5.0,10.0,5.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,1.0,7.0,30.00,20.00,10.00,30.00,0.00,10.00,NaN,NaN,NaN,NaN,NaN,NaN,40.00,30.00,0.00,30.00,0.00,0.00,5.0,7.0,5.0,8.0,5.0,NaN,NaN,NaN,NaN,NaN,1,5.0,5.0,5.0,5.0,5.0,NaN,5.0,NaN,2.0,NaN,5.0,3.0,3.0,50.00,10.00,10.00,10.00,10.00,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,2002-10-23
3310,229,16,Male,32,2,9,20,5,6,20,3,196,0,-0.40,0,25,Asian/Pacific Islander/Asian-American,17.65,17.65,17.65,15.69,15.69,15.69,0,3.0,3.0,5.0,3.0,6.0,NaN,3.0,5.0,2.0,28,biomedicine,10.0,NaN,European/Caucasian-American,7.0,1.0,New York,"11,354","30,146.00",1.0,Several times a year,Once a week,CEO in For Profit Biomedical Organization,7.0,8.0,5.0,7.0,7.0,1.0,1.0,5.0,3.0,3.0,8.0,5.0,1.0,5.0,2.0,6.0,1.0,1.0,3.0,21.43,16.67,21.43,16.67,11.90,11.90,10.0,4.0,4.0,10.0,1.0,1.0,15.22,19.57,15.22,17.39,21.74,10.87,8.0,7.0,5.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,0,6.0,7.0,8.0,2.0,1.0,1.0,3.0,2.0,2.0,6.0,4.0,1.0,3.0,22.73,15.91,22.73,15.91,11.36,11.36,10.0,5.0,5.0,10.0,5.0,5.0,17.78,11.11,17.78,20.00,22.22,11.11,8.0,8.0,10.0,5.0,10.0,NaN,NaN,NaN,NaN,NaN,2003-04-02
4562,301,8,Female,15,2,12,14,3,3,5,13,320,0,0.63,1,36,European/Caucasian-American,20.00,16.00,16.00,16.00,16.00,16.00,0,7.0,8.0,9.0,2.0,9.0,NaN,5.0,1.0,2.0,34,bilingual education,9.0,university of pennsylvania,European/Caucasian-American,3.0,8.0,"Washington, DC","8,540",NaN,2.0,Twice a month,Several times a week,professor of education,2.0,5.0,3.0,9.0,10.0,7.0,8.0,5.0,1.0,5.0,9.0,5.0,9.0,10.0,9.0,9.0,5.0,9.0,2.0,20.00,20.00,20.00,20.00,10.00,10.00,40.0,5.0,20.0,20.0,10.0,5.0,40.00,5.00,20.00,20.00,10.00,5.00,9.0,9.0,8.0,9.0,8.0,8.0,9.0,9.0,8.0,9.0,0,5.0,6.0,10.0,4.0,10.0,5.0,5.0,5.0,0.0,4.0,8.0,3.0,3.0,17.00,15.00,18.00,25.00,10.00,15.00,25.0,15.0,10.0,20.0,10.0,20.0,25.00,15.00,10.00,20.00,10.00,20.00,8.0,8.0,8.0,8.0,8.0,7.0,7.0,7.0,7.0,7.0,NaT
649,47,8,Male,16,2,2,19,19,<NA>,10,13,33,0,-0.18,1,30,European/Caucasian-American,30.00,20.00,30.00,10.00,0.00,10.00,0,4.0,5.0,6.0,7.0,7.0,4.0,6.0,2.0,2.0,30,Finance&Economics,8.0,NaN,European/Caucasian-American,2.0,2.0,Italy,100,NaN,1.0,Several times a year,Several times a week,Academic,2.0,6.0,7.0,2.0,8.0,7.0,6.0,3.0,7.0,4.0,7.0,4.0,5.0,8.0,8.0,7.0,2.0,1.0,8.0,20.00,20.00,25.00,25.00,5.00,5.00,NaN,NaN,NaN,NaN,NaN,NaN,25.00,20.00,20.00,15.00,15.00,5.00,8.0,7.0,9.0,9.0,3.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,6.0,6.0,3.0,6.0,6.0,2.0,5.0,5.0,3.0,2.0,30.00,20.00,20.00,20.00,0.00,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,7.0,7.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,2002-10-23
4394,291,19,Male,38,2,11,21,11,11,2,6,257,0,0.30,0,24,European/Caucasian-American,22.00,14.00,30.00,10.00,14.00,10.00,0,5.0,7.0,9.0,8.0,10.0,2.0,5.0,0.0,2.0,27,medicine and biochemistry,10.0,Harvard,Asian/Pacific Islander/Asian-American,5.0,5.0,New Jersey,"7,936",NaN,1.0,Once a week,Twice a week,doctor and entrepreneur,4.0,9.0,7.0,7.0,7.0,7.0,7.0,5.0,6.0,5.0,7.0,5.0,6.0,7.0,5.0,8.0,5.0,5.0,6.0,20.00,20.00,15.00,15.00,12.00,18.00,30.0,10.0,10.0,20.0,10.0,20.0,30.00,15.00,20.00,20.00,5.00,10.00,6.0,9.0,7.0,9.0,9.0,6.0,9.0,9.0,7.0,8.0,1,6.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,0.0,5.0,6.0,3.0,1.0,25.00,15.00,15.00,15.00,15.00,15.00,30.0,10.0,10.0,20.0,10.0,20.0,20.00,20.00,20.00,15.00,15.00,10.00,7.0,9.0,9.0,7.0,9.0,7.0,9.0,9.0,7.0,9.0,NaT
4102,277,5,Male,10,2,11,21,1,1,1,8,259,1,0.24,1,25,European/Caucasian-American,15.00,18.00,19.00,19.00,17.00,12.00,1,7.0,3.0,10.0,10.0,7.0,7.0,8.0,10.0,1.0,25,Genetics & Development,10.0,RPI,European/Caucasian-American,1.0,1.0,Connecticut,"6,098",NaN,1.0,Almost never,Once a month,Professor,2.0,10.0,6.0,10.0,5.0,8.0,8.0,10.0,5.0,3.0,8.0,2.0,7.0,8.0,6.0,6.0,1.0,2.0,5.0,60.00,20.00,0.00,20.00,0.00,0.00,40.0,10.0,10.0,20.0,10.0,10.0,50.00,0.00,0.00,0.00,50.00,0.00,4.0,8.0,8.0,8.0,5.0,4.0,8.0,8.0,8.0,5.0,1,8.0,8.0,8.0,9.0,NaN,NaN,9.0,10.0,1.0,2.0,6.0,1.0,2.0,60.00,10.00,0.00,20.00,0.00,10.00,50.0,0.0,0.0,30.0,0.0,20.0,50.00,0.00,0.00,0.00,50.00,0.00,4.0,8.0,8.0,8.0,5.0,4.0,8.0,8.0,8.0,5.0,NaT
803,55,16,Male,32,2,2,19,17,<NA>,13,15,35,0,0.33,0,25,European/Caucasian-American,20.00,23.00,23.00,22.00,7.00,5.00,0,6.0,8.0,8.0,8.0,8.0,6.0,8.0,8.0,2.0,23,LAW,1.0,NaN,Black/African American,1.0,1.0,California,"91,730","39,919.00",6.0,Twice a month,Twice a week,LAWYER,1.0,10.0,8.0,4.0,5.0,5.0,4.0,1.0,6.0,10.0,9.0,7.0,5.0,10.0,7.0,10.0,5.0,1.0,7.0,20.00,25.00,25.00,10.00,10.00,10.00,NaN,NaN,NaN,NaN,NaN,NaN,20.00,20.00,20.00,10.00,20.00,10.00,6.0,10.0,10.0,9.0,10.0,NaN,NaN,NaN,NaN,NaN,1,8.0,8.0,8.0,9.0,9.0,8.0,8.0,5.0,2.0,2.0,8.0,1.0,3.0,20.00,20.00,20.00,20.00,10.00,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,10.0,9.0,9.0,10.0,NaN,NaN,NaN,NaN,NaN,2002-10-23
6936,470,5,Female,9,2,19,15,13,14,14,1,481,0,0.67,0,23,European/Caucasian-American,25.00,20.00,15.00,20.00,5.00,15.00,0,7.0,7.0,8.0,5.0,7.0,1.0,4.0,1.0,2.0,29,medicine,4.0,harvard,Asian/Pacific Islander/Asian-American,1.0,1.0,south carolina,"29,571","18,619.00",1.0,Twice a month,Twice a week,medicine,4.0,1.0,1.0,1.0,10.0,10.0,10.0,2.0,1.0,3.0,10.0,5.0,10.0,10.0,6.0,6.0,10.0,1.0,4.0,10.00,20.00,25.00,25.00,10.00,10.00,40.0,10.0,20.0,10.0,10.0,10.0,60.00,10.00,10.00,10.00,5.00,5.00,4.0,9.0,5.0,8.0,6.0,4.0,9.0,8.0,5.0,6.0,0,3.0,4.0,5.0,4.0,2.0,3.0,4.0,3.0,0.0,4.0,2.0,3.0,2.0,20.00,15.00,30.00,20.00,10.00,5.00,50.0,10.0,10.0,10.0,10.0,10.0,60.00,10.00,5.00,15.00,5.00,5.00,4.0,7.0,7.0,7.0,9.0,3.0,9.0,9.0,2.0,8.0,NaT
6738,447,8,Male,16,2,17,11,4,1,3,5,434,1,0.13,0,27,European/Caucasian-American,30.00,15.00,15.00,30.00,0.00,10.00,1,10.0,10.0,10.0,10.0,10.0,9.0,10.0,10.0,1.0,26,Public Policy,13.0,University of Delhi,Asian/Pacific Islander/Asian-American,1.0,1.0,India,"110,003",NaN,1.0,Almost never,Twice a week,Public Finance,7.0,7.0,5.0,6.0,8.0,3.0,2.0,6.0,2.0,5.0,6.0,3.0,4.0,8.0,4.0,9.0,2.0,4.0,3.0,15.00,30.00,25.00,20.00,0.00,10.00,25.0,20.0,20.0,20.0,0.0,15.0,20.00,20.00,15.00,25.00,10.00,10.00,6.0,10.0,6.0,7.0,4.0,6.0,7.0,7.0,5.0,9.0,1,9.0,8.0,8.0,8.0,6.0,6.0,8.0,7.0,1.0,1.0,3.0,1.0,2.0,25.00,30.00,20.00,15.00,0.00,10.00,30.0,25.0,15.0,20.0,5.0,5.0,25.00,20.00,20.00,20.00,5.00,10.00,5.0,6.0,6.0,7.0,6.0,6.0,7.0,6.0,5.0,6.0,NaT
7097,480,16,Female,30,2,19,15,11,12,9,12,492,1,0.54,0,30,Other,30.00,0.00,30.00,30.00,10.00,0.00,1,10.0,10.0,10.0,8.0,8.0,2.0,1.0,1.0,2.0,26,Urban Planning,5.0,Sarah Lawrence College,European/Caucasian-American,4.0,6.0,New Jersey,"7,076",NaN,1.0,Twice a month,Several times a week,Planning,5.0,7.0,1.0,8.0,9.0,9.0,9.0,3.0,1.0,6.0,10.0,3.0,3.0,4.0,4.0,4.0,5.0,7.0,4.0,16.00,18.00,18.00,20.00,12.00,16.00,20.0,14.0,16.0,20.0,12.0,18.0,18.00,15.00,16.00,20.00,15.00,16.00,8.0,9.0,10.0,8.0,7.0,8.0,10.0,8.0,9.0,7.0,1,7.0,7.0,9.0,9.0,8.0,8.0,NaN,NaN,0.0,6.0,4.0,3.0,3.0,17.00,13.00,19.00,20.00,12.00,29.00,16.0,16.0,17.0,22.0,18.0,21.0,16.00,20.00,13.00,21.00,8.00,20.00,7.0,8.0,8.0,9.0,7.0,7.0,8.0,8.0,10.0,7.0,NaT

In [20]:
df_group_gender_age = round(df.groupby('gender')['age'].mean(), 2)
df_group_gender_age

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_39682/2284217189.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

gender
Female    26.11
Male      26.61
Name: age, dtype: Float64

In [21]:
#df['gender'].value_counts()
df_group_test = df.groupby(['id', 'gender']).size().reset_index(name='count')
df_group_test['percent'] = df_group_test.groupby('id')['count'].transform(lambda x: round(100 * x / x.sum(), 2))

fig = px.bar(
    x= df_group_test['id'],
    y= df_group_test['percent'],
    color = df_group_test['gender'],
    title = 'Gender Distribution by Waves (%)',
)
fig.update_layout(
    xaxis_title='ID',
    yaxis_title='Percent',
    barmode='group',
)

fig.add_shape(
    type='line',
    x0=0,
    x1=1,
    y0=50,
    y1=50,
    line=dict(color='black', dash='dash'),
    xref='paper',
    yref='y'
)

fig.show()

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_39682/3264820357.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [22]:
age_gender_counts = df.groupby(['age', 'gender']).size().reset_index(name='count')
age_gender_counts['percent'] = age_gender_counts.groupby('age')['count'].transform(lambda x: 100 * x / x.sum())

fig = px.bar(
    age_gender_counts,
    x='age',
    y='percent',
    color='gender',
    title='Gender distribution by age (%)',
    labels={'percent': 'Percentage', 'age': 'Age', 'gender': 'Gender'}
)

fig.show()

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_39682/591650264.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [23]:
df_goal_gender = df.groupby(['gender', 'goal']).size().unstack(level=0)
df_goal_gender

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_39682/1331287222.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

gender  Female  Male
goal
1.0       1687  1739
2.0       1647  1365
3.0        197   434
4.0        129   172
5.0        276   234
6.0        189   230

In [24]:
# Assign the reel name to the goal labels 
goal_labels = df_goal_gender.index.map({
    1: "Fun night out",
    2: "Meet new people",
    3: "Say I did it",
    4: "Get a date",
    5: "Other",
    6: "Serious relationship"
})

# Configure the subplots as pie charts
fig = make_subplots(rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'domain'}]],
                    subplot_titles=['Female', 'Male'])

fig.add_trace(
    go.Pie(
        labels=goal_labels,
        values=df_goal_gender['Female'],
        name="Female"
    ),
    row=1, col=1
)

fig.add_trace(
    go.Pie(
        labels=goal_labels,
        values=df_goal_gender['Male'],
        name="Male"
    ),
    row=1, col=2
)

fig.update_layout(
    title_text="Primary goals for event – by gender"
)

fig.show()

In [25]:
df_race_relig_gender = df.groupby(['gender', 'imprace', 'imprelig']).size().unstack()
df_race_relig_gender

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_39682/3618983576.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

imprelig        1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0   10.0
gender imprace
Female 0.0         8     0     0     0     0     0     0     0     0     0
       1.0       618    84   111    65   137    58    34     0     7    75
       2.0       145   203    32   110    10    14    27    22     0     0
       3.0        70    46   179     0    27    42     0    24    20    42
       4.0        50    19     0    46    37    34     0    70     0    20
       5.0        26    82    16     0    82    39    47    59     0     0
       6.0        25    30    39    16    21    27     0    18    32     0
       7.0        14     0    28    38    10    18    18    26     7     0
       8.0        55     0    56    28    62    25    54    53    44    49
       9.0        34     0    22     0    38    62    32    38    27    41
       10.0       24    34     0    20    19     0    10     0    31    63
Male   0.0         0     0     0     0     0     0     0     0     0     0
       1.0      1320    21    93    52    49    28     0    30    16     0
       2.0        65   105    80    14    21    54    19    15     0    18
       3.0       156   102    93    64    41    18    37    22     0     0
       4.0        38    10    35    30     0    38    63     0    20     0
       5.0        84     0    28     0    70    59    32     0    14    19
       6.0        60    36    20     0    15    99    16    70     0     0
       7.0       195    34    55    20    28     0    38    14     0     0
       8.0        45    28    42    21     0     0     0    56    45     0
       9.0         0    29     0     0    20    46    20     0     0     0
       10.0        0     0     0     0    10     0    20     0    19     0

In [26]:
df_race_relig_gender_reset = df_race_relig_gender.reset_index().melt(
    id_vars=['gender', 'imprace'],
    var_name='imprelig',
    value_name='count'
)

fig = px.density_heatmap(
    df_race_relig_gender_reset,
    x='imprelig',
    y='imprace',
    z='count',
    facet_col='gender',      
    color_continuous_scale='Viridis',
    title="Importance of Race vs Religion by Gender"
)
fig.show()

## 1. What are the least desirable attributes in a male partner? Does this differ for female partners?

In [27]:
# get a DataFrame whit all the attributs
df_attributes = df.loc[:, df.columns.str.contains('attr|sinc|fun|intel|amb|shar', regex=True)].copy()
df_attributes['gender'] = df['gender']
df_attributes['wave'] = df['wave']
df_attributes

,pf_o_fun,pf_o_amb,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,attr,sinc,intel,fun,amb,shar,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,gender,wave
0,20.0,0.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,6.0,9.0,7.0,7.0,6.0,5.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
1,40.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,7.0,8.0,7.0,8.0,5.0,6.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
2,18.0,14.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,5.0,8.0,9.0,8.0,5.0,7.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
3,40.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,7.0,6.0,8.0,7.0,6.0,8.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
4,10.0,10.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,5.0,6.0,7.0,7.0,6.0,6.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,20.0,10.0,10.0,5.0,3.0,2.0,6.0,5.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,3.0,5.0,5.0,5.0,NaN,NaN,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21
8374,5.0,10.0,6.0,3.0,7.0,3.0,7.0,2.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,4.0,6.0,8.0,4.0,4.0,NaN,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21
8375,10.0,10.0,2.0,1.0,2.0,2.0,2.0,1.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,4.0,7.0,8.0,8.0,8.0,NaN,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21
8376,10.0,10.0,5.0,7.0,5.0,5.0,3.0,6.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,4.0,6.0,5.0,4.0,NaN,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21
8377,15.0,5.0,8.0,8.0,7.0,7.0,7.0,7.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,3.0,7.0,6.0,4.0,8.0,1.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21

In [ ]:
df_attributes[df_attributes['wave'].isin([6,7,8,9])].sample(10)

,pf_o_fun,pf_o_amb,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,attr,sinc,intel,fun,amb,shar,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,gender,wave
2539,14.29,20.41,4.0,6.0,7.0,7.0,6.0,7.0,16.98,16.98,18.87,16.98,13.21,16.98,10.0,6.0,6.0,10.0,2.0,5.0,15.09,18.87,15.09,18.87,18.87,13.21,8.0,9.0,7.0,10.0,7.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN,10.0,5.0,NaN,NaN,16.98,16.98,18.87,16.98,13.21,16.98,10.0,8.0,7.0,9.0,6.0,7.0,18.75,18.75,14.58,18.75,12.50,16.67,8.0,9.0,10.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN,Male,8
3268,16.00,18.00,10.0,8.0,7.0,7.0,9.0,6.0,20.00,16.00,18.00,16.00,16.00,14.00,10.0,8.0,8.0,8.0,6.0,8.0,15.69,15.69,17.65,15.69,17.65,17.65,7.0,10.0,8.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,4.0,6.0,6.0,5.0,5.0,5.0,19.61,17.65,17.65,15.69,15.69,13.73,10.0,9.0,8.0,10.0,7.0,7.0,18.00,18.00,16.00,16.00,16.00,16.00,7.0,9.0,10.0,8.0,10.0,NaN,NaN,NaN,NaN,NaN,Male,9
3097,20.00,18.00,7.0,5.0,10.0,7.0,10.0,NaN,20.51,5.13,23.08,12.82,17.95,20.51,10.0,5.0,2.0,4.0,2.0,4.0,17.39,19.57,15.22,19.57,15.22,13.04,7.0,6.0,3.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,6.0,6.0,8.0,6.0,6.0,6.0,20.00,5.00,22.50,12.50,20.00,20.00,10.0,5.0,4.0,6.0,4.0,4.0,17.95,17.95,17.95,20.51,12.82,12.82,7.0,4.0,10.0,3.0,10.0,NaN,NaN,NaN,NaN,NaN,Male,9
2954,16.67,14.81,10.0,10.0,10.0,10.0,10.0,10.0,16.36,16.36,18.18,18.18,16.36,14.55,8.0,8.0,10.0,10.0,8.0,7.0,16.00,16.00,18.00,20.00,14.00,16.00,7.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,6.0,10.0,10.0,6.0,10.0,10.0,14.81,14.81,18.52,18.52,16.67,16.67,8.0,8.0,9.0,10.0,9.0,9.0,18.00,16.00,16.00,18.00,16.00,16.00,9.0,9.0,10.0,9.0,10.0,NaN,NaN,NaN,NaN,NaN,Female,9
2365,18.00,16.00,4.0,7.0,9.0,4.0,6.0,3.0,19.57,10.87,19.57,19.57,19.57,10.87,9.0,8.0,8.0,8.0,8.0,5.0,15.22,15.22,19.57,19.57,19.57,10.87,10.0,10.0,10.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,5.0,6.0,7.0,9.0,7.0,4.0,20.41,12.24,16.33,18.37,14.29,18.37,9.0,7.0,8.0,9.0,9.0,7.0,15.38,15.38,17.31,17.31,19.23,15.38,10.0,10.0,10.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,Male,7
2036,18.60,13.95,6.0,7.0,7.0,7.0,6.0,7.0,12.00,20.00,20.00,20.00,14.00,14.00,7.0,7.0,6.0,5.0,5.0,5.0,25.00,15.00,15.00,15.00,15.00,15.00,7.0,9.0,8.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN,5.0,6.0,9.0,6.0,9.0,3.0,14.00,18.00,18.00,18.00,16.00,16.00,9.0,4.0,4.0,7.0,7.0,7.0,23.81,11.90,14.29,16.67,16.67,16.67,6.0,9.0,9.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,Female,7
2992,12.82,17.95,6.0,6.0,6.0,5.0,6.0,5.0,15.52,17.24,17.24,17.24,17.24,15.52,9.0,10.0,10.0,10.0,10.0,9.0,18.18,18.18,16.36,18.18,14.55,14.55,8.0,10.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,7.0,8.0,9.0,6.0,9.0,5.0,16.36,18.18,18.18,16.36,16.36,14.55,9.0,10.0,9.0,9.0,9.0,9.0,19.61,15.69,15.69,17.65,15.69,15.69,8.0,10.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,Female,9
1924,18.60,13.95,5.0,7.0,7.0,5.0,7.0,3.0,8.33,20.83,20.83,14.58,16.67,18.75,5.0,8.0,9.0,8.0,9.0,10.0,17.86,16.07,17.86,16.07,14.29,17.86,7.0,10.0,7.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,5.0,5.0,9.0,6.0,7.0,8.0,13.73,17.65,17.65,15.69,17.65,17.65,7.0,9.0,9.0,8.0,9.0,9.0,16.67,16.67,16.67,18.52,14.81,16.67,6.0,6.0,7.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,7
2253,18.00,16.00,6.0,8.0,8.0,6.0,6.0,5.0,20.51,23.08,20.51,17.95,2.56,15.38,8.0,5.0,5.0,5.0,5.0,5.0,21.88,15.63,15.63,15.63,15.63,15.63,7.0,9.0,6.0,9.0,4.0,NaN,NaN,NaN,NaN,NaN,9.0,6.0,6.0,8.0,6.0,5.0,19.51,21.95,21.95,17.07,7.32,12.20,9.0,7.0,7.0,8.0,6.0,7.0,16.67,16.67,16.67,16.67,16.67,16.67,8.0,9.0,9.0,6.0,3.0,NaN,NaN,NaN,NaN,NaN,Male,7
1916,17.39,13.04,3.0,6.0,6.0,2.0,7.0,2.0,8.33,20.83,20.83,14.58,16.67,18.75,5.0,8.0,9.0,8.0,9.0,10.0,17.86,16.07,17.86,16.07,14.29,17.86,7.0,10.0,7.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,6.0,7.0,9.0,8.0,9.0,NaN,13.73,17.65,17.65,15.69,17.65,17.65,7.0,9.0,9.0,8.0,9.0,9.0,16.67,16.67,16.67,18.52,14.81,16.67,6.0,6.0,7.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,7

In [32]:
df_attributes[df_attributes['wave'].isin([6,7,8,9])].describe(include='all')

,pf_o_fun,pf_o_amb,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,attr,sinc,intel,fun,amb,shar,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,gender,wave
count,1557.000000,1557.000000,1554.000000,1538.000000,1532.000000,1507.000000,1434.000000,1340.000000,1557.000000,1557.00000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,0.0,0.0,0.0,0.0,0.0,1554.000000,1538.000000,1532.000000,1507.000000,1434.000000,1340.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,0.0,0.0,0.0,0.0,0.0,1562,1562.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Female,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,781,NaN
mean,17.910328,14.733789,6.309524,7.302341,7.519909,6.508295,6.962343,5.694776,16.158304,17.82194,18.990886,17.910328,14.733789,14.386532,8.638407,7.030829,6.872832,8.077714,6.414258,6.886962,19.315883,16.208324,15.823237,18.738163,14.857514,15.060745,7.431599,8.433526,7.833012,8.705202,7.856776,NaN,NaN,NaN,NaN,NaN,6.309524,7.302341,7.519909,6.508295,6.962343,5.694776,17.452725,17.358670,18.793813,17.344857,14.653126,14.399599,8.641631,7.002861,6.840486,8.083691,6.424177,7.183834,18.878026,16.213083,16.328262,17.912690,15.261631,15.407124,7.603720,8.135193,8.707439,7.674535,7.752504,NaN,NaN,NaN,NaN,NaN,NaN,8.120359
std,2.440198,4.180549,1.921448,1.568313,1.481465,1.869701,1.712800,2.010830,3.515382,2.75362,1.993004,2.440198,4.180549,3.946962,1.141478,1.730291,1.789146,1.384266,2.281281,1.918672,4.463158,3.150199,2.793401,2.929037,3.784809,2.940706,1.261952,1.314437,1.481372,1.057379,1.707209,NaN,NaN,NaN,NaN,NaN,1.921448,1.568313,1.481465,1.869701,1.712800,2.010830,2.960726,2.871105,2.037290,2.323435,3.709466,3.377109,1.047018,1.641880,1.514764,1.084546,1.938471,1.282489,3.853213,2.608627,2.685546,2.320384,3.054924,2.219990,1.247606,1.316012,1.032522,1.584398,1.740578,NaN,NaN,NaN,NaN,NaN,NaN,0.976788
min,12.500000,2.330000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,6.670000,5.13000,14.710000,12.500000,2.330000,2.270000,5.000000,3.000000,2.000000,4.000000,1.000000,1.000000,9.090000,6.900000,7.140000,11.900000,2.780000,2.630000,4.000000,5.000000,3.000000,5.000000,2.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,10.000000,5.000000,13.950000,11.110000,2.500000,4.760000,6.000000,2.000000,2.000000,5.000000,2.000000,4.000000,11.540000,7.690000,10.810000,7.690000,4.350000,7.690000,4.000000,4.000000,6.000000,3.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,6.000000
25%,16.670000,13.040000,5.000000,6.000000,7.000000,5.000000,6.000000,4.000000,14.290000,16.67000,17.390000,16.670000,13.040000,12.500000,8.000000,6.000000,6.000000,7.000000,5.000000,6.000000,15.690000,14.630000,14.290000,16.670000,13.640000,13.040000,7.000000,8.000000,7.000000,8.000000,7.000000,NaN,NaN,NaN,NaN,NaN,5.000000,6.000000,7.000000,5.000000,6.000000,4.000000,15.380000,16.070000,17.390000,15.690000,12.770000,12.960000,8.000000,6.000000,6.000000,7.000000,5.000000,6.000000,16.670000,14.290000,14.890000,16.670000,13.950000,13.950000,7.000000,7.000000,8.000000,7.000000,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,7.000000
50%,17.950000,15.690000,6.000000,7.000000,8.000000,7.000000,7.000000,6.000000,16.000000,17.78000,18.870000,17.950000,15.690000,14.890000,9.000000,7.000000,7.000000,8.000000,7.000000,7.000000,18.870000,16.280000,15.690000,18.420000,15.220000,15.560000,7.000000,9.000000,8.000000,9.000000,8.000000,NaN,NaN,NaN,NaN,NaN,6.000000,7.000000,8.000000,7.000000,7.000000,6.000000,16.670000,17.650000,18.520000,17.780000,15.380000,14.580000,9.000000,7.000000,7.000000,8.000000,7.000000,7.000000,18.750000,16.330000,16.220000,18.000000,15.560000,15.790000,7.000000,8.000000,9.000000,8.000000,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,9.000000
75%,19.230000,17.780000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,18.000000,19.44000,20.000000,19.230000,17.780000,17.070000,10.000000,8.000000,8.000000,9.000000,8.000000,8.000000,22.500000,18.420000,18.000000,20.000000,17.310000,17.020000,8.000000,10.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,NaN,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,19.050000,19.150000,20.000000,18.750000,16.670000,16.670000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,20.510000,18.180000,17.370000,18.920000,16.950000,16.670000,8.000000,9.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,9.000000
max,27.780000,20.590000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,27.780000,23.81000,23.810000,27.780000,20.590000,23.810000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,31.250000,23.260000,21.050000,31.250000,24.140000,22.220000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,26.320000,23.810000,25.000000,25.000000,22.220000,22.500000,10.000000,10.000000,10.000000,10.000000,9.000000,10.000000,38.460000,20.510000,30.770000,24.390000,22.220000,20.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,9.000000

In [49]:
df_poeple_like = df[['wave', 'gender', 'attr1_1', 'sinc1_1', 'fun1_1', 'intel1_1', 'amb1_1', 'shar1_1']]
df_poeple_like.sample(25)

      wave  gender  attr1_1  sinc1_1  fun1_1  intel1_1  amb1_1  shar1_1
2146     7  Female    14.29    16.33   18.37     16.33   18.37    16.33
7640    21  Female    40.00     5.00   15.00     30.00    5.00     5.00
2227     7    Male    15.22    15.22   17.39     19.57   13.04    19.57
4512    12  Female    10.00    30.00   10.00     20.00   15.00    15.00
7785    21  Female    10.00    10.00   20.00     30.00   10.00    15.00
7119    19    Male    20.00    10.00   20.00     22.00   15.00    13.00
5263    14  Female    20.00    10.00   20.00     20.00   20.00    10.00
2876     9  Female    17.31    13.46   19.23     17.31   19.23    13.46
979      3    Male    30.00    10.00   30.00     20.00    0.00    10.00
7026    19  Female    20.00    20.00   15.00     20.00   15.00    10.00
643      2    Male    20.00    20.00   25.00     25.00    5.00     5.00
7967    21    Male    30.00    30.00    5.00     30.00    2.00     3.00
3274     9    Male    20.00    16.00   16.00     18.00   16.00    14.00
6289    15    Male    20.00    10.00   20.00     20.00   10.00    20.00
6309    15    Male    20.00    15.00   20.00     20.00   10.00    15.00
4442    11    Male    23.00    18.00   18.00     21.00   10.00    10.00
4841    12    Male    30.00    15.00   20.00     15.00   10.00    10.00
5566    14    Male    50.00    10.00   10.00     10.00   10.00    10.00
2878     9  Female    17.31    13.46   19.23     17.31   19.23    13.46
3708    11  Female     7.00    35.00   20.00     20.00    5.00    13.00
6760    17    Male    55.00     2.00   40.00      1.00    1.00     1.00
1509     4    Male    40.00     5.00   10.00     20.00   10.00    15.00
5648    14    Male    50.00    10.00   10.00     10.00    5.00    15.00
5322    14  Female    15.00    20.00   20.00     20.00   20.00     5.00
8099    21    Male    20.00    15.00   20.00     20.00   15.00    10.00

In [90]:
# Check the data for the wave 6,7,8,9, to unifomize the data BUT I think the data is already uniform
df_poeple_like['total'] = df_poeple_like[['attr1_1', 'sinc1_1', 'fun1_1', 'intel1_1', 'amb1_1', 'shar1_1']].sum(axis=1)
df_poeple_like.sample(20)

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_39682/2444841550.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,wave,gender,attr1_1,sinc1_1,fun1_1,intel1_1,amb1_1,shar1_1,total
5697,14,Male,30.00,10.00,20.00,15.00,15.00,10.00,100.00
1596,4,Male,10.00,20.00,20.00,35.00,0.00,15.00,100.00
565,2,Male,25.00,35.00,10.00,30.00,0.00,0.00,100.00
6063,15,Female,20.00,20.00,10.00,20.00,10.00,20.00,100.00
4208,11,Male,25.00,15.00,20.00,20.00,10.00,10.00,100.00
4569,12,Female,50.00,5.00,10.00,20.00,5.00,10.00,100.00
782,2,Male,40.00,20.00,20.00,20.00,0.00,0.00,100.00
171,1,Male,33.33,11.11,11.11,11.11,11.11,22.22,99.99
530,2,Male,30.00,20.00,30.00,10.00,0.00,10.00,100.00
2705,9,Female,15.38,19.23,19.23,17.31,9.62,19.23,100.00
6817,18,Female,25.00,20.00,10.00,15.00,15.00,15.00,100.00
7495,21,Female,20.00,20.00,20.00,20.00,5.00,15.00,100.00
476,2,Female,50.00,10.00,10.00,20.00,10.00,0.00,100.00
8151,21,Male,25.00,15.00,20.00,20.00,10.00,10.00,100.00
1471,4,Male,40.00,8.00,12.00,10.00,10.00,20.00,100.00
4312,11,Male,35.00,40.00,5.00,5.00,7.00,8.00,100.00
4822,12,Male,20.00,16.00,16.00,16.00,16.00,16.00,100.00
1827,5,Male,80.00,10.00,NaN,10.00,NaN,NaN,100.00
4470,12,Female,10.00,18.00,16.00,20.00,16.00,20.00,100.00
6026,15,Female,8.00,20.00,25.00,25.00,12.00,10.00,100.00

In [84]:
df_poeple_like_mean = df_poeple_like.groupby('gender').mean(numeric_only=True)

df_poeple_like_mean_chart = df_poeple_like_mean[['attr1_1', 'sinc1_1', 'fun1_1', 'intel1_1', 'amb1_1', 'shar1_1']].round(2)
# renaming my column name for better understanding
renames = {
    'attr1_1'   : 'Attractiveness',
    'sinc1_1'   : 'Sincerity',
    'fun1_1'    : 'Fun',
    'intel1_1'  : 'Intelligence',
    'amb1_1'    : 'Ambition',
    'shar1_1'   : 'Shared interests',
}

# Apply the renames
df_poeple_like_mean_chart.rename(columns=renames, inplace=True)
df_poeple_like_mean_chart = df_poeple_like_mean_chart.reset_index().melt(id_vars='gender', var_name='variable', value_name='value')
df_poeple_like_mean_chart

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_39682/578323942.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

    gender          variable  value
0   Female    Attractiveness  18.06
1     Male    Attractiveness  26.92
2   Female         Sincerity  18.31
3     Male         Sincerity  16.50
4   Female               Fun  17.15
5     Male               Fun  17.76
6   Female      Intelligence  21.00
7     Male      Intelligence  19.54
8   Female          Ambition  12.83
9     Male          Ambition   8.55
10  Female  Shared interests  12.70
11    Male  Shared interests  11.00

In [88]:
fig = px.bar(
    df_poeple_like_mean_chart,
    x='value',
    y='variable',
    color='gender',
    barmode='group',
    title='Mean score of each attribute by gender'
)
fig.show()

## 2. How important do people think attractiveness is in potential mate selection vs. its real impact?