# Speed Dating Data Analysis
## 1. Introduction

**Goal:** \
Analyze a dataset from speed dating events to identify factors influencing first and second date decisions.

**Objectives:**
1. Clean data to ensure quality
2. Understand the general structure of the dataset
3. Perform targeted analysis on specific questions
4. Synthesize results clearly and visually

In [1]:
import pandas as pd
import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
df = pd.read_csv("data/speed_dating_data.csv", encoding='latin1')
pd.set_option('display.max_columns', None)
df.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [3]:
df.describe(include='all')

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8315,8296.000000,4914,3133,3583,8315.000000,8299.000000,8299.000000,8299,7314,4279,8299.000000,8281.000000,8299.000000,8289,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,259,NaN,241,68,115,NaN,NaN,NaN,269,409,261,NaN,NaN,NaN,367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Business,NaN,UC Berkeley,"1,400.00","26,908.00",NaN,NaN,NaN,New York,0,"55,080.00",NaN,NaN,NaN,Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,521,NaN,107,403,241,NaN,NaN,NaN,522,355,124,NaN,NaN,NaN,202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,NaN,7.662488,NaN,NaN,NaN,2.757186,3.784793,3.651645,NaN,NaN,NaN,2.122063,5.006762,2.158091,NaN,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,NaN,3.758935,NaN,NaN,NaN,1.230905,2.845708,2.805237,NaN,NaN,NaN,1.407181,1.444531,1.105246,NaN,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,NaN,1.000000,NaN,NaN,NaN,1.000000,0.000000,1.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,NaN,5.000000,NaN,NaN,NaN,2.000000,1.000000,1.000000,NaN,NaN,NaN,1.000000,4.000000,1.000000,NaN,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,NaN,8.000000,NaN,NaN,NaN,2.000000,3.000000,3.000000,NaN,NaN,NaN,2.000000,5.000000,2.000000,NaN,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,NaN,10.000000,NaN,NaN,NaN,4.000000,6.000000,6.000000,NaN,NaN,NaN,2.000000,6.000000,3.000000,NaN,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,NaN,18.000000,NaN,NaN,NaN,6.000000,10.000000,10.000000,NaN,NaN,NaN,6.000000,7.000000,7.000000,NaN,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [4]:
df.shape

(8378, 195)

## 2. Cleaning and Data Preparation
**Goal:** \
Ensure that data is consistent, usable and ready for analysis.

**Actions:**
* Rename columns for greater clarity.
* Correct of score scales for waves 6,7,8,9 (multiplication by 10).
* Standardize of column types (float, int, category)
* Remove or analyze of columns containing too many missing values
* Filter of columns relevant to the study

**Why:** \
Clean data guarantees reliable analysis results

In [5]:
# precent of missing values
df_missing_values = df.isna().sum() / len(df) * 100
df_missing_values_sort = df_missing_values[df_missing_values >= 50].sort_values(ascending=False).reset_index()
df_missing_values_sort.columns = ['col_name', 'percent_missing']
df_missing_values_sort['percent_missing'] = df_missing_values_sort['percent_missing'].round(2)
df_missing_values_sort

    col_name  percent_missing
0   num_in_3            92.03
1   numdat_3            82.14
2     expnum            78.52
3     amb7_2            76.67
4    sinc7_2            76.67
5    shar7_2            76.44
6   intel7_2            76.32
7    attr7_2            76.32
8     fun7_2            76.32
9   intel7_3            75.94
10    fun7_3            75.94
11    amb7_3            75.94
12   shar7_3            75.94
13   sinc7_3            75.94
14    amb5_3            75.94
15   attr7_3            75.94
16   shar2_3            75.94
17    fun5_3            75.94
18  intel5_3            75.94
19   sinc5_3            75.94
20   attr5_3            75.94
21   attr4_3            64.68
22   sinc4_3            64.68
23   shar4_3            64.68
24   attr2_3            64.68
25  intel4_3            64.68
26    fun4_3            64.68
27    amb4_3            64.68
28    fun2_3            64.68
29  intel2_3            64.68
30   sinc2_3            64.68
31    amb2_3            64.68
32    mn_sat            62.60
33   tuition            57.23
34   shar1_3            52.57
35  you_call            52.57
36    amb3_3            52.57
37    fun3_3            52.57
38  intel3_3            52.57
39   sinc3_3            52.57
40   attr3_3            52.57
41    amb1_3            52.57
42   attr1_3            52.57
43    date_3            52.57
44    fun1_3            52.57
45  intel1_3            52.57
46  them_cal            52.57
47   sinc1_3            52.57
48    fun3_s            52.26
49    amb3_s            52.26
50   sinc3_s            52.26
51  intel3_s            52.26
52   attr3_s            52.26
53    amb1_s            51.11
54   shar1_s            51.11
55    fun1_s            51.11
56  intel1_s            51.11
57   sinc1_s            51.11
58   attr1_s            51.11

In [6]:
fig = px.scatter(df_missing_values.values)
fig.update_layout(
    title='Percentage of Missing Values in Each Column (by index)',
    xaxis_title='Row Index',
    yaxis_title='% Missing Value',
    showlegend=False,
)
fig.show()

![Percentage of Missing Values in Each Column (by index)](../speed_dating__tinder/charts_as_png/2a_percentage_of_missing_values_in_each_column__by_index.png)

In [7]:
def color_code(percent):
    if percent > 70:
        return '#FB2C36'
    elif percent > 50:
        return '#FE9A00'
    else:
        return '#7CCF00'

df_missing_values_sort['color'] = df_missing_values_sort['percent_missing'].apply(color_code)

fig = px.bar(
    df_missing_values_sort,
    x='col_name',
    y='percent_missing',
    color='color',
    color_discrete_map='identity',
    title='Percentage of missing values in each column (by name)',
)

fig.update_layout(
    xaxis_title='Column',
    yaxis_title='Percentage Missing',
    xaxis_tickangle=-45
)

fig.show()

![Percentage of missing values in each column (by name)](../speed_dating__tinder/charts_as_png/2b_percentage_of_missing_values_in_each_column_by__name.png)

In [8]:
# All columns name and type
df_type = df.dtypes.reset_index().rename(columns={"index": "c_name", 0: "type"})
pd.set_option('display.max_rows', 200)
df_type

       c_name     type
0         iid    int64
1          id  float64
2      gender    int64
3         idg    int64
4      condtn    int64
5        wave    int64
6       round    int64
7    position    int64
8    positin1  float64
9       order    int64
10    partner    int64
11        pid  float64
12      match    int64
13   int_corr  float64
14   samerace    int64
15      age_o  float64
16     race_o  float64
17   pf_o_att  float64
18   pf_o_sin  float64
19   pf_o_int  float64
20   pf_o_fun  float64
21   pf_o_amb  float64
22   pf_o_sha  float64
23      dec_o    int64
24     attr_o  float64
25     sinc_o  float64
26    intel_o  float64
27      fun_o  float64
28      amb_o  float64
29     shar_o  float64
30     like_o  float64
31     prob_o  float64
32      met_o  float64
33        age  float64
34      field   object
35   field_cd  float64
36   undergra   object
37     mn_sat   object
38    tuition   object
39       race  float64
40    imprace  float64
41   imprelig  float64
42       from   object
43    zipcode   object
44     income   object
45       goal  float64
46       date  float64
47     go_out  float64
48     career   object
49   career_c  float64
50     sports  float64
51   tvsports  float64
52   exercise  float64
53     dining  float64
54    museums  float64
55        art  float64
56     hiking  float64
57     gaming  float64
58   clubbing  float64
59    reading  float64
60         tv  float64
61    theater  float64
62     movies  float64
63   concerts  float64
64      music  float64
65   shopping  float64
66       yoga  float64
67   exphappy  float64
68     expnum  float64
69    attr1_1  float64
70    sinc1_1  float64
71   intel1_1  float64
72     fun1_1  float64
73     amb1_1  float64
74    shar1_1  float64
75    attr4_1  float64
76    sinc4_1  float64
77   intel4_1  float64
78     fun4_1  float64
79     amb4_1  float64
80    shar4_1  float64
81    attr2_1  float64
82    sinc2_1  float64
83   intel2_1  float64
84     fun2_1  float64
85     amb2_1  float64
86    shar2_1  float64
87    attr3_1  float64
88    sinc3_1  float64
89     fun3_1  float64
90   intel3_1  float64
91     amb3_1  float64
92    attr5_1  float64
93    sinc5_1  float64
94   intel5_1  float64
95     fun5_1  float64
96     amb5_1  float64
97        dec    int64
98       attr  float64
99       sinc  float64
100     intel  float64
101       fun  float64
102       amb  float64
103      shar  float64
104      like  float64
105      prob  float64
106       met  float64
107  match_es  float64
108   attr1_s  float64
109   sinc1_s  float64
110  intel1_s  float64
111    fun1_s  float64
112    amb1_s  float64
113   shar1_s  float64
114   attr3_s  float64
115   sinc3_s  float64
116  intel3_s  float64
117    fun3_s  float64
118    amb3_s  float64
119   satis_2  float64
120    length  float64
121  numdat_2  float64
122   attr7_2  float64
123   sinc7_2  float64
124  intel7_2  float64
125    fun7_2  float64
126    amb7_2  float64
127   shar7_2  float64
128   attr1_2  float64
129   sinc1_2  float64
130  intel1_2  float64
131    fun1_2  float64
132    amb1_2  float64
133   shar1_2  float64
134   attr4_2  float64
135   sinc4_2  float64
136  intel4_2  float64
137    fun4_2  float64
138    amb4_2  float64
139   shar4_2  float64
140   attr2_2  float64
141   sinc2_2  float64
142  intel2_2  float64
143    fun2_2  float64
144    amb2_2  float64
145   shar2_2  float64
146   attr3_2  float64
147   sinc3_2  float64
148  intel3_2  float64
149    fun3_2  float64
150    amb3_2  float64
151   attr5_2  float64
152   sinc5_2  float64
153  intel5_2  float64
154    fun5_2  float64
155    amb5_2  float64
156  you_call  float64
157  them_cal  float64
158    date_3  float64
159  numdat_3  float64
160  num_in_3  float64
161   attr1_3  float64
162   sinc1_3  float64
163  intel1_3  float64
164    fun1_3  float64
165    amb1_3  float64
166   shar1_3  float64
167   attr7_3  float64
168   sinc7_3  float64
169  intel7_3  float64
170    fun7_3  float64
171    amb7_3  float64
172   shar7_3  float64
173   attr4_3  float64
174   sinc4_3  float64
175  intel4_3  float64
176    fun4_3  float64
177    amb4_3  float64
178   shar4_3  float64
179   attr2_3  float64
180   sinc2_3  float64
181  intel2_3  float64
182    fun2_3  float64
183    amb2_3  float64
184   shar2_3  float64
185   attr3_3  float64
186   sinc3_3  float64
187  intel3_3  float64
188    fun3_3  float64
189    amb3_3  float64
190   attr5_3  float64
191   sinc5_3  float64
192  intel5_3  float64
193    fun5_3  float64
194    amb5_3  float64

In [9]:
# renaming my column name for better understanding
renames = {
    'condtn'    : 'nbr_of_partner',
    'field_cd' : 'field_c' #because carreer code is career_c 
}

# Apply the renames
df.rename(columns=renames, inplace=True)

In [10]:
# Fill data if I can 
# Apply a wave id to the only one missing NaN => df[df['iid'] == 552]
df['id'] = df['id'].fillna(22)

# num_in_3 92% missing values but the values is "if yes, how many?" than if no value that will say 0
df['num_in_3'] = df['num_in_3'].fillna(0)

In [11]:
# Columns to convert to Int64
col_to_convert_to_int = [
    'positin1', 
    'pid', 
    'age_o', 
    'age'
]

# Convertion apply to be an int
df['id'] = df['id'].astype(int)
df['num_in_3'] = df['num_in_3'].astype(int)
df[col_to_convert_to_int] = df[col_to_convert_to_int].astype('Int64')

In [12]:
# Mapping dictionnaires
gender_mapping = {0: 'Female', 1 : 'Male'}

wave_date_mapping = {
    1: '2002-10-16',
    2: '2002-10-23',
    3: '2002-11-12',
    4: '2002-11-12',
    5: '2002-11-20',
    6: '2003-03-26',
    7: '2003-03-26',
    8: '2003-04-02',
    9: '2003-04-02',
    10: '2003-09-24'
}

race_mapping = {
    1 : 'Black/African American',
    2 : 'European/Caucasian-American',
    3 : 'Latino/Hispanic American',
    4 : 'Asian/Pacific Islander/Asian-American',
    5 : 'Native American',
    6 : 'Other'
}

frequency_maping = {
    1 : 'Several times a week',
    2 : 'Twice a week',
    3 : 'Once a week',
    4 : 'Twice a month',
    5 : 'Once a month',
    6 : 'Several times a year',
    7 : 'Almost never'
}

# Apply mapping and category type
df['gender'] = df['gender'].map(gender_mapping).astype('category')
df['race_o'] = df['race_o'].map(race_mapping).astype('category')
df['race'] = df['race'].map(race_mapping).astype('category')
df['go_out'] = df['go_out'].map(frequency_maping).astype('category')
df['date'] = df['date'].map(frequency_maping).astype('category')
df['wave_date'] = df['wave'].map(wave_date_mapping)

# Apply dateTime to date column
df['wave_date'] = pd.to_datetime(df['wave_date'])

# Apply category type
df['field'] = df['field'].astype('category')

In [13]:
# Drop columns with more than 50% missing values
df = df.drop(df_missing_values[df_missing_values >= 50].index, axis=1)
df.shape

(8378, 137)

In [14]:
df.sample(15)

,iid,id,gender,idg,nbr_of_partner,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_c,undergra,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,satis_2,length,numdat_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,wave_date
2007,148,7,Female,13,2,7,16,2,2,3,16,173,0,-0.34,0,22,European/Caucasian-American,18.37,18.37,20.41,20.41,16.33,6.12,0,5.0,8.0,5.0,7.0,6.0,5.0,5.0,4.0,2.0,27,Business,8.0,NaN,Asian/Pacific Islander/Asian-American,7.0,4.0,"Cherry Hill, NJ","8,034",NaN,5.0,Twice a month,Several times a week,Business,7.0,7.0,4.0,6.0,9.0,9.0,9.0,5.0,2.0,1.0,10.0,10.0,9.0,9.0,5.0,7.0,9.0,7.0,5.0,15.09,16.98,16.98,18.87,18.87,13.21,9.0,9.0,9.0,9.0,9.0,9.0,23.81,16.67,14.29,23.81,9.52,11.90,8.0,9.0,9.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN,0,7.0,9.0,9.0,5.0,8.0,2.0,7.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-03-26
6015,393,15,Female,29,2,15,19,3,3,15,6,402,0,-0.18,0,29,Asian/Pacific Islander/Asian-American,25.00,20.00,15.00,25.00,10.00,5.00,0,6.0,8.0,6.0,6.0,6.0,6.0,4.0,6.0,2.0,22,Writing: Literary Nonfiction,6.0,Smith College,European/Caucasian-American,4.0,8.0,Long Island,"11,733","65,693.00",1.0,Almost never,Several times a week,Writing or Editorial,6.0,3.0,2.0,3.0,5.0,9.0,9.0,4.0,3.0,4.0,9.0,6.0,7.0,8.0,7.0,7.0,5.0,4.0,6.0,8.00,20.00,25.00,25.00,12.00,10.00,10.0,20.0,25.0,20.0,15.0,10.0,18.00,18.00,18.00,18.00,5.00,13.00,7.0,9.0,8.0,8.0,8.0,7.0,8.0,8.0,8.0,8.0,0,6.0,8.0,7.0,6.0,7.0,6.0,6.0,5.0,2.0,2.5,7.0,1.0,3.0,12.00,20.00,20.00,20.00,8.00,20.00,17.0,17.0,17.0,17.0,15.0,17.0,25.00,15.00,20.00,15.00,10.00,15.00,7.0,8.0,8.0,8.0,7.0,7.0,9.0,9.0,8.0,7.0,NaT
6185,402,6,Male,12,2,15,18,9,8,2,10,388,0,0.17,0,24,European/Caucasian-American,22.00,17.00,15.00,15.00,15.00,16.00,0,3.0,8.0,8.0,8.0,8.0,7.0,2.0,2.0,2.0,29,Mathematics,2.0,University of Illinois/Champaign,Asian/Pacific Islander/Asian-American,1.0,1.0,Korea,NaN,NaN,3.0,Twice a month,Twice a week,Financial Mathematics-Investment Bank or Hedge...,7.0,10.0,2.0,6.0,9.0,6.0,6.0,9.0,7.0,4.0,3.0,3.0,5.0,8.0,4.0,4.0,6.0,9.0,6.0,25.00,20.00,15.00,25.00,10.00,5.00,10.0,25.0,10.0,20.0,10.0,25.0,25.00,20.00,10.00,20.00,10.00,15.00,6.0,8.0,7.0,10.0,9.0,7.0,10.0,10.0,8.0,9.0,1,7.0,7.0,5.0,7.0,5.0,7.0,6.0,4.0,2.0,1.0,7.0,1.0,3.0,15.00,25.00,20.00,15.00,15.00,10.00,30.0,15.0,10.0,20.0,5.0,20.0,30.00,20.00,10.00,20.00,5.00,15.00,6.0,7.0,10.0,7.0,9.0,6.0,8.0,10.0,6.0,9.0,NaT
2079,153,12,Female,23,2,7,16,11,11,16,8,165,0,0.51,0,30,European/Caucasian-American,16.67,12.50,20.83,18.75,12.50,18.75,0,7.0,8.0,8.0,6.0,7.0,5.0,5.0,5.0,2.0,28,Modern Chinese Literature,7.0,NaN,Asian/Pacific Islander/Asian-American,1.0,1.0,China,"136,300",NaN,2.0,Several times a year,Once a week,professor,2.0,8.0,5.0,7.0,7.0,7.0,6.0,6.0,5.0,7.0,10.0,6.0,7.0,9.0,7.0,7.0,8.0,5.0,6.0,9.76,19.51,19.51,14.63,19.51,17.07,7.0,8.0,8.0,8.0,8.0,7.0,23.53,17.65,14.71,14.71,14.71,14.71,7.0,7.0,6.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,0,5.0,5.0,5.0,5.0,NaN,6.0,5.0,5.0,0.0,4.0,5.0,1.0,3.0,13.95,16.28,18.60,16.28,18.60,16.28,7.0,7.0,8.0,7.0,8.0,7.0,20.51,17.95,15.38,15.38,15.38,15.38,7.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,2003-03-26
6745,448,9,Male,18,2,17,11,9,7,3,2,431,1,0.03,0,27,Asian/Pacific Islander/Asian-American,15.00,15.00,25.00,15.00,15.00,15.00,1,9.0,8.0,9.0,9.0,5.0,2.0,6.0,4.0,2.0,22,Law/Business,1.0,Yale,European/Caucasian-American,1.0,1.0,New York City,"10,021","55,080.00",1.0,Twice a week,Several times a week,Business Management,7.0,3.0,2.0,4.0,9.0,8.0,9.0,3.0,5.0,9.0,7.0,3.0,6.0,7.0,6.0,10.0,6.0,5.0,3.0,25.00,15.00,25.00,25.00,5.00,5.00,30.0,20.0,15.0,20.0,0.0,15.0,15.00,15.00,25.00,17.00,18.00,10.00,8.0,9.0,8.0,9.0,10.0,8.0,7.0,9.0,8.0,8.0,1,5.0,6.0,8.0,4.0,8.0,4.0,6.0,3.0,2.0,4.0,6.0,3.0,3.0,30.00,10.00,25.00,20.00,5.00,10.00,35.0,10.0,15.0,25.0,0.0,15.0,15.00,15.00,20.00,20.00,20.00,10.00,9.0,9.0,9.0,9.0,9.0,8.0,7.0,9.0,8.0,9.0,NaT
8134,541,11,Male,22,2,21,22,3,1,3,21,529,0,-0.14,1,22,Asian/Pacific Islander/Asian-American,10.00,25.00,25.00,10.00,10.00,20.00,1,5.0,7.0,6.0,6.0,5.0,8.0,7.0,7.0,2.0,23,Industrial Engineering/Operations Research,5.0,University of Toronto,Asian/Pacific Islander/Asian-American,2.0,2.0,Indonesia,"10,024",NaN,3.0,Almost never,Once a week,Entrepreneur,7.0,10.0,10.0,7.0,8.0,3.0,5.0,4.0,3.0,8.0,3.0,10.0,5.0,10.0,10.0,9.0,9.0,3.0,7.0,40.00,30.00,0.00,20.00,0.00,10.00,30.0,20.0,0.0,30.0,0.0,20.0,10.00,25.00,25.00,20.00,10.00,10.00,8.0,9.0,9.0,9.0,8.0,9.0,10.0,10.0,10.0,8.0,0,3.0,8.0,8.0,7.0,8.0,8.0,6.0,5.0,0.0,1.0,3.0,1.0,3.0,50.00,20.00,0.00,15.00,0.00,15.00,20.0,20.0,20.0,20.0,20.0,20.0,60.00,0.00,10.00,20.00,0.00,10.00,5.0,8.0,10.0,10.0,8.0,5.0,8.0,10.0,8.0,8.0,NaT
2609,194,1,Female,1,2,9,20,2,2,20,2,215,0,0.74,0,26,Asian/Pacific Islander/Asian-American,14.89,19.15,21.28,19.15,14.89,10.64,0,3.0,4.0,4.0,3.0,3.0,4.0,2.0,6.0,2.0,24,Clinical Psychology,3.0,NaN,European/Caucasian-American,9.0,9.0,New York,"11,803","65,708.00",3.0,Once a week,Twice a week,Psychologist,3.0,8.0,6.0,6.0,9.0,6.0,6.0,4.0,8.0,7.0,9.0,9.0,6.0,9.0,5.0,7.0,9.0,4.0,7.0,16.00,16.00,20.00,16.00,18.00,14.00,10.0,7.0,8.0,9.0,7.0,9.0,20.00,12.00,16.00,20.00,14.00,18.00,9.0,10.0,8.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,1,9.0,9.0,9.0,9.0,9.0,7.0,8.0,6.0,2.0,1.0,6.0,1.0,3.0,18.18,18.18,18.18,14.55,18.18,12.73,10.0,8.0,8.0,10.0,9.0,9.0,18.87,13.21,15.09,18.87,15.09,18.87,10.0,10.0,10.0,8.0,10.0,NaN,NaN,NaN,NaN,NaN,2003-04-02
7670,520,12,Female,23,2,21,22,9,9,3,19,549,0,-0.10,0,28,European/Caucasian-American,20.00,20.00,20.00,20.00,0.00,20.00,0,2.0,9.0,9.0,8.0,8.0,6.0,5.0,6.0,2.0,28,Social Work/SIPA,11.0,Santa Clara University,Other,2.0,1.0,Hawaii,"96,797","46,280.00",1.0,Almost never,Several times a week,Foreign Service,9.0,4.0,6.0,8.0,8.0,10.0,8.0,5.0,2.0,9.0,10.0,8.0,9.0,8.0,5.0,5.0,8.0,2.0,5.0,25.00,15.00,25.00,15.00,10.00,10.00,40.0,5.0,20.0,10.0,10.0,15.0,40.00,5.00,15.00,20.00,10.00,10.00,8.0,9.0,7.0,8.0,5.0,7.0,9.0,9.0,7.0,7.0,1,7.0,7.0,7.0,8.0,5.0,6.0,7.0,7.0,0.0,4.0,5.0,3.0,2.0,20.00,15.00,20.00,20.00,10.00,15.00,30.0,15.0,10.0,20.0,10.0,15.0,40.00,10.00,5.00,30.00,5.00,10.00,8.0,9.0,7.0,6.0,6.0,7.0,9.0,7.0,7.0,7.0,NaT
7607,517,9,Female,17,2,21,22,1,1,14,22,552,0,0.43,0,25,European/Caucasian-American,70.00,0.00,15.00,15.00,0.00,0.00,1,6.0,9.0,9.0,9.0,8.0,8.0,7.0,6.0,2.0,30,Acting,15.0,Southwestern University,Latino/Hispanic American,1.0,1.0,Mexico,"78,666",NaN,5.0,Once a month,Once a week,Acting,6.0,2.0,1.0,9.0,9.0,6.0,8.0,4.0,1.0,2.0,9.0,3.0,10.0,8.0,4.0,4.0,3.0,9.0,3.0,15.00,20.00,20.00,20.00,5.00,10.00,25.0,30.0,10.0,10.0,15.0,10.0,30.00,20.00,15.00,15.00,10.00,10.00,8.0,9.0,7.0,9.0,7.0,7.0,10.0,10.0,8.0,7.0,0,6.0,5.0,4.0,3.0,6.0,5.0,3.0,6.0,0.0,NaN,2.0,1.0,2.0,20.00,20.00,20.00,10.00,10.00,20.00,20.0,20.0,15.0,25.0,10.0,10.0,20.00,20.00,15.00,25.00,10.00,10.00,8.0,9.0,9.0,7.0,6.0,8.0,8.0,9.0,6.0,6.0,NaT
4846,322,1,Female,1,1,13,9,1,1,4,3,334,0,-0.17,1,29,Asian/Pacific Islander/Asian-American,40.00,10.00,15.00,10.00,10.00,15.00,0,6.0,7.0,6.0,6.0,6.0,6.0,6.0,7.0,2.0,34,Anthropology,3.0,Kunitachi College of Music (in Japan),Asian/Pacific Islander/Asian-American,2.0,1.0,Tokyo and Texas,NaN,NaN,2.0,Twice a week,Twice a week,to get Ph.D and be a professor,2.0,8.0,7.0,7.0,6.0,6.0,6.0,9.0,3.0,6.0,7.0,2.0,8.0,8.0,8.0,8.0,3.0,1.0,9.0,2.00,60.00,15.00,8.00,5.00,10.00,30.0,30.0,20.0,5.0,5.0,10.0,40.00,30.00,10.00,10.00,0.00,10.00,5.0,9.0,8.0,7.0,7.0,4.0,9.0,7.0,7.0,6.0,0,8.0,NaN,10.0,10.0,NaN,10.0,10.0,5.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4981,336,5,Male,10,1,13,10,10,10,4,8,329,0,0.73,0,29,European/Caucasian-American,15.00,22.00,22.00,16.00,15.00,10.00,1,7.0,7.0,9.0,6.0,7.0,6.0,8.0,6.0,2.0,25,Architecture,17.0,Florida International University,Latino/Hispanic American,1.0,5.0,Miami,NaN,NaN,1.0,Once a month,Twice a week,Architecture and design,17.0,5.0,4.0,4.0,5.0,8.0,10.0,4.0,1.0,1.0,9.0,4.0,6.0,10.0,10.0,10.0,3.0,4.0,4.0,20.00,15.00,30.00,10.00,15.00,10.00,30.0,15.0,20.0,10.0,15.0,10.0,30.00,15.00,20.00,10.00,15.00,10.00,5.0,9.0,7.0,7.0,9.0,4.0,6.0,6.0,5.0,10.0,0,2.0,2.0,5.0,1.0,7.0,1.0,1.0,1.0,0.0,0.0,7.0,1.0,3.0,25.00,20.00,25.00,10.00,10.00,10.00,25.0,20.0,25.0,10.0,10.0,10.0,25.00,20.00,25.00,10.00,10.00,10.00,4.0,8.0,6.0,7.0,8.0,5.0,6.0,6.0,5.0,7.0,NaT
3671,256,5,Female,9,2,11,21,7,7,5,18,290,0,0.20,0,34,European/Caucasian-American,30.00,10.00,30.00,10.00,5.00,15.00,1,7.0,8.0,8.0,7.0,6.0,8.0,7.0,5.0,1.0,24,Medicine,4.0,Harvard,Asian/Pacific Islander/Asian-American,6.0,5.0,Northern Virginia,"22,015","62,997.00",2.0,Several times a year,Twice a month,Physician,4.0,5.0,3.0,6.0,7.0,6.0,5.0,6.0,5.0,5.0,5.0,8.0,6.0,8.0,8.0,8.0,9.0,3.0,6.0,15.00,25.00,20.00,20.00,10.00,10.00,20.0,15.0,15.0,20.0,10.0,20.0,30.00,10.00,20.00,25.00,5.00,10.00,6.0,9.0,6.0,8.0,6.0,7.0,7.0,8.0,6.0,7.0,0,7.0,6.0,6.0,6.0,5.0,7.0,7.0,6.0,1.0,2.0,5.0,1.0,3.0,20.00,20.00,20.00,20.00,10.00,10.00,25.0,15.0,15.0,20.0,15.0,10.0,35.00,10.00,15.00,20.00,5.00,15.00,7.0,8.0,8.0,7.0,7.0,7.0,7.0,8.0,6.0,7.0,NaT
5723,377,17,Male,34,2,14,20,1,1,13,20,360,0,-0.21,0,24,Other,20.00,30.00,10.00,10.00,10.00,20.00,1,7.0,6.0,5.0,5.0,5.0,5.0,7.0,6.0,2.0,26,business school,8.0,nyu,Asian/Pacific Islander/Asian-American,3.0,2.0,new york,"7,039",NaN,1.0,Once a month,Several times a week,investment management,7.0,7.0,9.0,6.0,6.0,3.0,3.0,1.0,7.0,8.0,6.0,8.0,5.0,8.0,7.0,8.0,6.0,2.0,6.0,25.00,20.00,10.00,20.00,15.00,10.00,45.0,10.0,5.0,30.0,5.0,5.0,20.00,25.00,20.00,20.00,10.00,5.00,7.0,8.0,8.0,7.0,7.0,7.0,6.0,7.0,8.0,7.0,0,8.0,8.0,8.0,8.0,7.0,8.0,5.0,7.0,NaN,2.0,5.0,3.0,2.0,20.00,20.00,20.00,30.00,20.00,10.00,20.0,20.0,20.0,20.0,20.0,20.0,16.67,16.67,16.67,16.67,16.67,16.67,7.0,9.0,8.0,7.0,8.0,7.0,8.0,8.0,7.0,7.0,NaT
2537,186,3,Male,6,1,8,10,3,4,10,10,183,0,0.40,0,24,European/Caucasian-American,20.00,22.50,17.50,22.50,10.00,7.50,0,8.0,8.0,8.0,7.0,6.0,5.0,8.0,5.0,2.0,24,Medical Informatics,5.0,NaN,Asian/Pacific Islander/Asian-American,4.0,3.0,Kansas,"66,610","44,195.00",1.0,Almost never,Once a week,Professor,2.0,5.0,1.0,4.0,9.0,5.0,3.0,6.0,1.0,1.0,6.0,7.0,4.0,7.0,8.0,8.0,6.0,3.0,7.0,19.44,19.44,22.22,16.67,11.11,11.11,7.0,4.0,6.0,8.0,6.0,4.0,15.79,13.16,21.05,18.42,21.05,10.53,4.0,8.0,4.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,0,7.0,7.0,6.0,6.0,5.0,3.0,4.0,3.0,2.0,2.0,7.0,3.0,3.0,16.67,22.22,25.00,11.11,11.11,13.89,8.0,5.0,5.0,7.0,5.0,8.0,13.16,10.53,21.05,21.05,18.42,15.79,4.0,9.0,7.0,5.0,6.0,NaN,NaN,NaN,NaN,NaN,2003-04-02
861,61,6,Female,11,1,3,10,9,<NA>,3,4,69,0,-0.18,1,28,European/Caucasian-American,50.00,10.00,30.00,10.00,0.00,0.00,0,2.0,8.0,8.0,4.0,6.0,3.0,4.0,4.0,2.0,28,German Literature,7.0,NaN,European/Caucasian-American,1.0,5.0,"Tuscaloosa, Alabama","35,404","23,988.00",1.0,Once a month,Twice a week,Academic,2.0,1.0,1.0,5.0,10.0,10.0,10.0,5.0,1.0,5.0,10.0,6.0,10.0,10.0,8.0,10.0,8.0,7.0,5.0,15.00,15.00,20.00,15.00,15.00,20.00,NaN,NaN,NaN,NaN,NaN,NaN,40.00,12.00,12.00,12.00,12.00,12.00,7.0,10.0,7.0,10.0,7.0,NaN,NaN,NaN,NaN,NaN,1,8.0,8.0,8.0,8.0,8.0,5.0,8.0,4.0,2.0,1.0,5.0,3.0,2.0,10.00,20.00,25.00,10.00,10.00,25.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,9.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,2002-11-12

## 3. Data Mining (descriptive statistics)
**Goal:** \
Understand the distribution of key variables before going any further.

**Actions:**
* Calculate the number of matches and second matches.
* Analyze the distribution of evaluated attributes (attractiveness, sincerity, fun, intelligence, ambition).
* Explore of the perceived importance of race (imprace) and religion (imprelig)
* Identify of overall level of self-confidence

**What I'm looking for:**
* See if certain variables are naturally more valued
* Detect any anomalies or imbalances
* Better understand participants' general behaviors

**Results:**
* Attractiveness and fun are often overrated attributes.
* Shared interests are of significant importance, race less.
* Some participants rate themselves more generously than others perceive them.

In [15]:
df_group_gender_age = round(df.groupby('gender', observed=True)['age'].mean(), 2)
df_group_gender_age

gender
Female    26.11
Male      26.61
Name: age, dtype: Float64

In [16]:
df_group_test = df.groupby(['id', 'gender'], observed=True).size().reset_index(name='count')
df_group_test['percent'] = df_group_test.groupby('id')['count'].transform(lambda x: round(100 * x / x.sum(), 2))

fig = px.bar(
    x= df_group_test['id'],
    y= df_group_test['percent'],
    color = df_group_test['gender'],
    title = 'Gender Distribution by Waves (%)',
)
fig.update_layout(
    xaxis_title='ID',
    yaxis_title='Percentage',
    barmode='group',
)

fig.add_shape(
    type='line',
    x0=0,
    x1=1,
    y0=50,
    y1=50,
    line=dict(color='black', dash='dash'),
    xref='paper',
    yref='y'
)

fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/3a_gender_distribution_by_waves.png)

In [17]:
age_gender_counts = df.groupby(['age', 'gender'], observed=True).size().reset_index(name='count')
age_gender_counts['percent'] = age_gender_counts.groupby('age')['count'].transform(lambda x: 100 * x / x.sum())

fig = px.bar(
    age_gender_counts,
    x='age',
    y='percent',
    color='gender',
    title='Gender distribution by age (%)',
    labels={'percent': 'Percentage', 'age': 'Age', 'gender': 'Gender'}
)

fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/3b_gender_distribution_by_age.png)

In [18]:
df_goal_gender = df.groupby(['gender', 'goal'], observed=True).size().unstack(level=0)
df_goal_gender

gender  Female  Male
goal
1.0       1687  1739
2.0       1647  1365
3.0        197   434
4.0        129   172
5.0        276   234
6.0        189   230

In [19]:
# Assign the real name to the goal labels 
goal_labels = df_goal_gender.index.map({
    1: "Fun night out",
    2: "Meet new people",
    3: "Say I did it",
    4: "Get a date",
    5: "Other",
    6: "Serious relationship"
})

# Configure the subplots as pie charts
fig = make_subplots(rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'domain'}]],
                    subplot_titles=['Female', 'Male'])

fig.add_trace(
    go.Pie(
        labels=goal_labels,
        values=df_goal_gender['Female'],
        name="Female"
    ),
    row=1, col=1
)

fig.add_trace(
    go.Pie(
        labels=goal_labels,
        values=df_goal_gender['Male'],
        name="Male"
    ),
    row=1, col=2
)

fig.update_layout(
    title_text="Primary goals for event – by gender"
)

fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/3c_primary_goals_for_event__by_gender.png)

In [20]:
df_race_relig_gender = df.groupby(['gender', 'imprace', 'imprelig'], observed=True).size().unstack()
df_race_relig_gender

imprelig          1.0    2.0    3.0    4.0    5.0   6.0   7.0   8.0   9.0   \
gender imprace
Female 0.0         8.0    NaN    NaN    NaN    NaN   NaN   NaN   NaN   NaN
       1.0       618.0   84.0  111.0   65.0  137.0  58.0  34.0   NaN   7.0
       2.0       145.0  203.0   32.0  110.0   10.0  14.0  27.0  22.0   NaN
       3.0        70.0   46.0  179.0    NaN   27.0  42.0   NaN  24.0  20.0
       4.0        50.0   19.0    NaN   46.0   37.0  34.0   NaN  70.0   NaN
       5.0        26.0   82.0   16.0    NaN   82.0  39.0  47.0  59.0   NaN
       6.0        25.0   30.0   39.0   16.0   21.0  27.0   NaN  18.0  32.0
       7.0        14.0    NaN   28.0   38.0   10.0  18.0  18.0  26.0   7.0
       8.0        55.0    NaN   56.0   28.0   62.0  25.0  54.0  53.0  44.0
       9.0        34.0    NaN   22.0    NaN   38.0  62.0  32.0  38.0  27.0
       10.0       24.0   34.0    NaN   20.0   19.0   NaN  10.0   NaN  31.0
Male   1.0      1320.0   21.0   93.0   52.0   49.0  28.0   NaN  30.0  16.0
       2.0        65.0  105.0   80.0   14.0   21.0  54.0  19.0  15.0   NaN
       3.0       156.0  102.0   93.0   64.0   41.0  18.0  37.0  22.0   NaN
       4.0        38.0   10.0   35.0   30.0    NaN  38.0  63.0   NaN  20.0
       5.0        84.0    NaN   28.0    NaN   70.0  59.0  32.0   NaN  14.0
       6.0        60.0   36.0   20.0    NaN   15.0  99.0  16.0  70.0   NaN
       7.0       195.0   34.0   55.0   20.0   28.0   NaN  38.0  14.0   NaN
       8.0        45.0   28.0   42.0   21.0    NaN   NaN   NaN  56.0  45.0
       9.0         NaN   29.0    NaN    NaN   20.0  46.0  20.0   NaN   NaN
       10.0        NaN    NaN    NaN    NaN   10.0   NaN  20.0   NaN  19.0

imprelig        10.0
gender imprace
Female 0.0       NaN
       1.0      75.0
       2.0       NaN
       3.0      42.0
       4.0      20.0
       5.0       NaN
       6.0       NaN
       7.0       NaN
       8.0      49.0
       9.0      41.0
       10.0     63.0
Male   1.0       NaN
       2.0      18.0
       3.0       NaN
       4.0       NaN
       5.0      19.0
       6.0       NaN
       7.0       NaN
       8.0       NaN
       9.0       NaN
       10.0      NaN

In [21]:
df_race_relig_gender_reset = df_race_relig_gender.reset_index().melt(
    id_vars=['gender', 'imprace'],
    var_name='imprelig',
    value_name='count'
)

fig = px.density_heatmap(
    df_race_relig_gender_reset,
    x='imprelig',
    y='imprace',
    z='count',
    facet_col='gender',      
    color_continuous_scale='YlGnBu',
    title="Importance of Race vs Religion by Gender"
)
fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/3d_importance_of_race_vs_religion_by_gender.png)

## 4. Exploratory Analyses
### 4.1 Study of the least desirable attribute in a male and female partner

**Goal:** \
Identify which attributes (`attr`, `sinc`, `intel`, `fun`, `amb`, `shar`) are considered least attractive to a male partner. \
Compare whether this perception is different for female partners.

**Actions:** 
* Separate data by gender (`gender` : Male / Female).
* Calculate averages for each attribute (attractiveness, sincerity, intelligence, fun, ambition, interests).
* Visualize with bar charts comparing averages for each gender.

**Results:** 
* For men, the attributes “fun” and “shared interests” are rated slightly lower.
* For women, the attributes “ambition” and “fun” appear to be slightly lower priorities.
* The differences between men and women remain moderate but visible, showing that the criteria valued differ slightly according to gender.

In [22]:
# Get a DataFrame with all the attributs
df_attributes = df.loc[:, df.columns.str.contains('attr|sinc|fun|intel|amb|shar', regex=True)].copy()
df_attributes['gender'] = df['gender']
df_attributes['wave'] = df['wave']
df_attributes

,pf_o_fun,pf_o_amb,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,attr,sinc,intel,fun,amb,shar,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,gender,wave
0,20.0,0.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,6.0,9.0,7.0,7.0,6.0,5.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
1,40.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,7.0,8.0,7.0,8.0,5.0,6.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
2,18.0,14.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,5.0,8.0,9.0,8.0,5.0,7.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
3,40.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,7.0,6.0,8.0,7.0,6.0,8.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
4,10.0,10.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,5.0,6.0,7.0,7.0,6.0,6.0,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,Female,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,20.0,10.0,10.0,5.0,3.0,2.0,6.0,5.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,3.0,5.0,5.0,5.0,NaN,NaN,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21
8374,5.0,10.0,6.0,3.0,7.0,3.0,7.0,2.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,4.0,6.0,8.0,4.0,4.0,NaN,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21
8375,10.0,10.0,2.0,1.0,2.0,2.0,2.0,1.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,4.0,7.0,8.0,8.0,8.0,NaN,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21
8376,10.0,10.0,5.0,7.0,5.0,5.0,3.0,6.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,4.0,6.0,5.0,4.0,NaN,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21
8377,15.0,5.0,8.0,8.0,7.0,7.0,7.0,7.0,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,3.0,7.0,6.0,4.0,8.0,1.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,Male,21

In [23]:
df_attributes[df_attributes['wave'].isin([6,7,8,9])].sample(10)

,pf_o_fun,pf_o_amb,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,attr,sinc,intel,fun,amb,shar,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,gender,wave
2214,18.00,18.00,8.0,9.0,10.0,7.0,9.0,5.0,16.67,18.75,18.75,18.75,18.75,8.33,8.0,8.0,9.0,9.0,9.0,7.0,14.55,18.18,18.18,16.36,18.18,14.55,8.0,7.0,9.0,9.0,7.0,NaN,NaN,NaN,NaN,NaN,7.0,9.0,10.0,8.0,8.0,4.0,16.00,18.00,18.00,20.00,12.00,16.00,8.0,8.0,9.0,9.0,5.0,9.0,14.55,18.18,16.36,18.18,16.36,16.36,8.0,8.0,10.0,10.0,5.0,NaN,NaN,NaN,NaN,NaN,Male,7
3192,19.23,9.62,4.0,4.0,4.0,4.0,4.0,5.0,17.39,17.39,19.57,19.57,10.87,15.22,9.0,5.0,2.0,7.0,2.0,2.0,27.59,6.90,13.79,20.69,24.14,6.90,7.0,8.0,7.0,9.0,6.0,NaN,NaN,NaN,NaN,NaN,6.0,8.0,8.0,3.0,4.0,5.0,19.05,16.67,19.05,19.05,9.52,16.67,8.0,3.0,4.0,8.0,3.0,5.0,21.62,13.51,10.81,21.62,18.92,13.51,7.0,8.0,9.0,7.0,4.0,NaN,NaN,NaN,NaN,NaN,Male,9
3223,17.39,15.22,7.0,7.0,10.0,NaN,8.0,NaN,17.24,17.24,17.24,17.24,13.79,17.24,10.0,10.0,8.0,10.0,5.0,9.0,21.74,19.57,15.22,21.74,4.35,17.39,8.0,10.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN,5.0,8.0,6.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Male,9
2029,20.00,16.00,9.0,9.0,9.0,8.0,8.0,5.0,12.00,20.00,20.00,20.00,14.00,14.00,7.0,7.0,6.0,5.0,5.0,5.0,25.00,15.00,15.00,15.00,15.00,15.00,7.0,9.0,8.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN,7.0,7.0,8.0,8.0,6.0,NaN,14.00,18.00,18.00,18.00,16.00,16.00,9.0,4.0,4.0,7.0,7.0,7.0,23.81,11.90,14.29,16.67,16.67,16.67,6.0,9.0,9.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,Female,7
2258,14.00,18.00,6.0,8.0,8.0,7.0,NaN,9.0,20.51,23.08,20.51,17.95,2.56,15.38,8.0,5.0,5.0,5.0,5.0,5.0,21.88,15.63,15.63,15.63,15.63,15.63,7.0,9.0,6.0,9.0,4.0,NaN,NaN,NaN,NaN,NaN,8.0,9.0,9.0,NaN,NaN,NaN,19.51,21.95,21.95,17.07,7.32,12.20,9.0,7.0,7.0,8.0,6.0,7.0,16.67,16.67,16.67,16.67,16.67,16.67,8.0,9.0,9.0,6.0,3.0,NaN,NaN,NaN,NaN,NaN,Male,7
1857,20.00,6.67,3.0,8.0,8.0,2.0,7.0,1.0,6.67,20.00,20.00,17.78,20.00,15.56,6.0,9.0,9.0,7.0,7.0,6.0,20.51,15.38,12.82,20.51,12.82,17.95,7.0,8.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN,7.0,8.0,9.0,8.0,7.0,8.0,10.00,18.00,18.00,18.00,18.00,18.00,8.0,9.0,7.0,8.0,7.0,5.0,22.50,17.50,12.50,20.00,12.50,15.00,7.0,8.0,9.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,Female,6
2186,18.00,18.00,7.0,8.0,8.0,8.0,8.0,7.0,16.00,18.00,18.00,18.00,14.00,16.00,9.0,7.0,8.0,8.0,7.0,7.0,14.29,20.41,16.33,16.33,18.37,14.29,8.0,8.0,9.0,8.0,9.0,NaN,NaN,NaN,NaN,NaN,6.0,8.0,9.0,9.0,9.0,7.0,17.31,19.23,17.31,15.38,15.38,15.38,8.0,7.0,8.0,7.0,9.0,8.0,13.46,19.23,17.31,15.38,19.23,15.38,8.0,8.0,8.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,Male,7
2093,20.00,16.00,8.0,10.0,8.0,8.0,7.0,5.0,15.38,17.31,17.31,17.31,17.31,15.38,9.0,9.0,9.0,9.0,9.0,9.0,16.67,16.67,16.67,16.67,16.67,16.67,8.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,9.0,8.0,9.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Female,7
1938,17.78,17.78,8.0,8.0,8.0,8.0,8.0,8.0,16.00,16.00,16.00,18.00,18.00,16.00,8.0,7.0,7.0,7.0,6.0,7.0,20.00,15.56,15.56,17.78,15.56,15.56,7.0,8.0,8.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,5.0,5.0,6.0,6.0,5.0,5.0,16.67,16.67,16.67,18.75,16.67,14.58,8.0,7.0,7.0,8.0,6.0,7.0,20.93,16.28,16.28,18.60,13.95,13.95,8.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,Female,7
2080,27.78,2.78,6.0,7.0,7.0,4.0,NaN,NaN,9.76,19.51,19.51,14.63,19.51,17.07,7.0,8.0,8.0,8.0,8.0,7.0,23.53,17.65,14.71,14.71,14.71,14.71,7.0,7.0,6.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,4.0,4.0,5.0,4.0,NaN,NaN,13.95,16.28,18.60,16.28,18.60,16.28,7.0,7.0,8.0,7.0,8.0,7.0,20.51,17.95,15.38,15.38,15.38,15.38,7.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,Female,7

In [24]:
df_attributes[df_attributes['wave'].isin([6,7,8,9])].describe(include='all')

,pf_o_fun,pf_o_amb,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,attr,sinc,intel,fun,amb,shar,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,gender,wave
count,1557.000000,1557.000000,1554.000000,1538.000000,1532.000000,1507.000000,1434.000000,1340.000000,1557.000000,1557.00000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,1557.000000,0.0,0.0,0.0,0.0,0.0,1554.000000,1538.000000,1532.000000,1507.000000,1434.000000,1340.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,0.0,0.0,0.0,0.0,0.0,1562,1562.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Female,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,781,NaN
mean,17.910328,14.733789,6.309524,7.302341,7.519909,6.508295,6.962343,5.694776,16.158304,17.82194,18.990886,17.910328,14.733789,14.386532,8.638407,7.030829,6.872832,8.077714,6.414258,6.886962,19.315883,16.208324,15.823237,18.738163,14.857514,15.060745,7.431599,8.433526,7.833012,8.705202,7.856776,NaN,NaN,NaN,NaN,NaN,6.309524,7.302341,7.519909,6.508295,6.962343,5.694776,17.452725,17.358670,18.793813,17.344857,14.653126,14.399599,8.641631,7.002861,6.840486,8.083691,6.424177,7.183834,18.878026,16.213083,16.328262,17.912690,15.261631,15.407124,7.603720,8.135193,8.707439,7.674535,7.752504,NaN,NaN,NaN,NaN,NaN,NaN,8.120359
std,2.440198,4.180549,1.921448,1.568313,1.481465,1.869701,1.712800,2.010830,3.515382,2.75362,1.993004,2.440198,4.180549,3.946962,1.141478,1.730291,1.789146,1.384266,2.281281,1.918672,4.463158,3.150199,2.793401,2.929037,3.784809,2.940706,1.261952,1.314437,1.481372,1.057379,1.707209,NaN,NaN,NaN,NaN,NaN,1.921448,1.568313,1.481465,1.869701,1.712800,2.010830,2.960726,2.871105,2.037290,2.323435,3.709466,3.377109,1.047018,1.641880,1.514764,1.084546,1.938471,1.282489,3.853213,2.608627,2.685546,2.320384,3.054924,2.219990,1.247606,1.316012,1.032522,1.584398,1.740578,NaN,NaN,NaN,NaN,NaN,NaN,0.976788
min,12.500000,2.330000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,6.670000,5.13000,14.710000,12.500000,2.330000,2.270000,5.000000,3.000000,2.000000,4.000000,1.000000,1.000000,9.090000,6.900000,7.140000,11.900000,2.780000,2.630000,4.000000,5.000000,3.000000,5.000000,2.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,10.000000,5.000000,13.950000,11.110000,2.500000,4.760000,6.000000,2.000000,2.000000,5.000000,2.000000,4.000000,11.540000,7.690000,10.810000,7.690000,4.350000,7.690000,4.000000,4.000000,6.000000,3.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,6.000000
25%,16.670000,13.040000,5.000000,6.000000,7.000000,5.000000,6.000000,4.000000,14.290000,16.67000,17.390000,16.670000,13.040000,12.500000,8.000000,6.000000,6.000000,7.000000,5.000000,6.000000,15.690000,14.630000,14.290000,16.670000,13.640000,13.040000,7.000000,8.000000,7.000000,8.000000,7.000000,NaN,NaN,NaN,NaN,NaN,5.000000,6.000000,7.000000,5.000000,6.000000,4.000000,15.380000,16.070000,17.390000,15.690000,12.770000,12.960000,8.000000,6.000000,6.000000,7.000000,5.000000,6.000000,16.670000,14.290000,14.890000,16.670000,13.950000,13.950000,7.000000,7.000000,8.000000,7.000000,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,7.000000
50%,17.950000,15.690000,6.000000,7.000000,8.000000,7.000000,7.000000,6.000000,16.000000,17.78000,18.870000,17.950000,15.690000,14.890000,9.000000,7.000000,7.000000,8.000000,7.000000,7.000000,18.870000,16.280000,15.690000,18.420000,15.220000,15.560000,7.000000,9.000000,8.000000,9.000000,8.000000,NaN,NaN,NaN,NaN,NaN,6.000000,7.000000,8.000000,7.000000,7.000000,6.000000,16.670000,17.650000,18.520000,17.780000,15.380000,14.580000,9.000000,7.000000,7.000000,8.000000,7.000000,7.000000,18.750000,16.330000,16.220000,18.000000,15.560000,15.790000,7.000000,8.000000,9.000000,8.000000,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,9.000000
75%,19.230000,17.780000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,18.000000,19.44000,20.000000,19.230000,17.780000,17.070000,10.000000,8.000000,8.000000,9.000000,8.000000,8.000000,22.500000,18.420000,18.000000,20.000000,17.310000,17.020000,8.000000,10.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,NaN,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,19.050000,19.150000,20.000000,18.750000,16.670000,16.670000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,20.510000,18.180000,17.370000,18.920000,16.950000,16.670000,8.000000,9.000000,9.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,9.000000
max,27.780000,20.590000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,27.780000,23.81000,23.810000,27.780000,20.590000,23.810000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,31.250000,23.260000,21.050000,31.250000,24.140000,22.220000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,26.320000,23.810000,25.000000,25.000000,22.220000,22.500000,10.000000,10.000000,10.000000,10.000000,9.000000,10.000000,38.460000,20.510000,30.770000,24.390000,22.220000,20.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,9.000000

In [25]:
df_poeple_like = df[['wave', 'gender', 'attr1_1', 'sinc1_1', 'fun1_1', 'intel1_1', 'amb1_1', 'shar1_1']]
df_poeple_like.sample(25)

      wave  gender  attr1_1  sinc1_1  fun1_1  intel1_1  amb1_1  shar1_1
2269     7    Male    16.67    12.50   18.75     20.83   12.50    18.75
7458    21  Female    20.00    10.00   30.00     10.00   15.00    15.00
2457     8  Female    15.22    17.39   17.39     17.39   15.22    17.39
4546    12  Female    15.00    20.00   15.00     25.00   15.00    10.00
1983     7  Female    18.00    18.00   18.00     20.00   16.00    10.00
1634     4    Male    20.00    20.00   15.00     15.00    5.00    25.00
6574    17  Female    20.00    20.00   20.00     20.00   10.00    10.00
2799     9  Female    16.00    20.00   20.00     18.00   18.00     8.00
7181    19    Male    20.00    20.00   15.00     20.00   10.00    15.00
1038     4  Female    15.00    20.00   20.00     20.00   15.00    10.00
3456    10  Female    10.00    25.00   20.00     20.00    5.00    20.00
6446    16  Female    15.00    25.00   15.00     20.00   10.00    15.00
3098     9    Male    20.51     5.13   12.82     23.08   17.95    20.51
1876     6    Male    20.00    20.00   20.00     20.00    6.67    13.33
8261    21    Male    25.00    20.00   20.00     20.00    0.00    15.00
2016     7  Female     8.51    19.15   19.15     19.15   19.15    14.89
4009    11  Female    25.00    20.00   25.00     25.00    5.00     0.00
1584     4    Male    10.00    20.00   20.00     35.00    0.00    15.00
1253     4  Female    25.00    15.00   20.00     20.00   20.00     0.00
3448    10  Female    15.00    20.00   15.00     20.00   15.00    15.00
1174     4  Female    20.00    25.00   15.00     15.00   15.00    10.00
1040     4  Female    15.00    20.00   20.00     20.00   15.00    10.00
1045     4  Female    10.00    25.00   10.00     20.00   20.00    15.00
6746    17    Male    25.00    15.00   25.00     25.00    5.00     5.00
6939    19  Female    10.00    20.00   25.00     25.00   10.00    10.00

In [26]:
# Check the data for the wave 6,7,8,9 to unifomize the data BUT I think the data is already uniform
df_poeple_like.loc[:, 'total'] = df_poeple_like[['attr1_1', 'sinc1_1', 'fun1_1', 'intel1_1', 'amb1_1', 'shar1_1']].sum(axis=1)
df_poeple_like.sample(20)

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_68691/2212302406.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,wave,gender,attr1_1,sinc1_1,fun1_1,intel1_1,amb1_1,shar1_1,total
4318,11,Male,35.00,40.00,5.00,5.00,7.00,8.00,100.00
3156,9,Male,15.56,17.78,17.78,17.78,17.78,13.33,100.01
506,2,Male,25.00,20.00,20.00,25.00,10.00,0.00,100.00
8156,21,Male,25.00,15.00,20.00,20.00,10.00,10.00,100.00
3278,9,Male,20.00,16.00,16.00,18.00,16.00,14.00,100.00
4528,12,Female,10.00,40.00,20.00,10.00,10.00,10.00,100.00
1028,4,Female,15.00,20.00,20.00,20.00,15.00,10.00,100.00
1832,5,Male,80.00,10.00,NaN,10.00,NaN,NaN,100.00
1580,4,Male,19.00,24.00,23.00,21.00,5.00,8.00,100.00
6333,15,Male,20.00,20.00,20.00,20.00,10.00,10.00,100.00
3761,11,Female,15.00,20.00,20.00,20.00,15.00,10.00,100.00
3507,10,Male,18.00,10.00,10.00,30.00,10.00,22.00,100.00
924,3,Male,20.00,15.00,20.00,20.00,5.00,10.00,90.00
6369,15,Male,75.00,5.00,5.00,5.00,5.00,5.00,100.00
1867,6,Female,NaN,NaN,NaN,NaN,NaN,NaN,0.00
4679,12,Male,24.00,15.00,20.00,20.00,8.00,13.00,100.00
3516,10,Male,35.00,20.00,20.00,10.00,10.00,5.00,100.00
6817,18,Female,25.00,20.00,10.00,15.00,15.00,15.00,100.00
2942,9,Female,20.00,15.56,15.56,20.00,11.11,17.78,100.01
6286,15,Male,20.00,10.00,20.00,20.00,10.00,20.00,100.00

In [27]:
df_poeple_like_mean = df_poeple_like.groupby('gender', observed=True).mean(numeric_only=True)

df_poeple_like_mean_chart = df_poeple_like_mean[['attr1_1', 'sinc1_1', 'fun1_1', 'intel1_1', 'amb1_1', 'shar1_1']].round(2)

# renaming my column name for better understanding
renames = {
    'attr1_1'   : 'Attractiveness',
    'sinc1_1'   : 'Sincerity',
    'fun1_1'    : 'Fun',
    'intel1_1'  : 'Intelligence',
    'amb1_1'    : 'Ambition',
    'shar1_1'   : 'Shared interests',
}

# Apply the renames
df_poeple_like_mean_chart.rename(columns=renames, inplace=True)
df_poeple_like_mean_chart = df_poeple_like_mean_chart.reset_index().melt(id_vars='gender', var_name='variable', value_name='value')
df_poeple_like_mean_chart

    gender          variable  value
0   Female    Attractiveness  18.06
1     Male    Attractiveness  26.92
2   Female         Sincerity  18.31
3     Male         Sincerity  16.50
4   Female               Fun  17.15
5     Male               Fun  17.76
6   Female      Intelligence  21.00
7     Male      Intelligence  19.54
8   Female          Ambition  12.83
9     Male          Ambition   8.55
10  Female  Shared interests  12.70
11    Male  Shared interests  11.00

In [28]:
fig = px.bar(
    df_poeple_like_mean_chart,
    x='value',
    y='variable',
    color='gender',
    barmode='group',
    title='Mean score of each attribute by gender'
)
fig.update_layout(
    xaxis_title='Mean Score',
    yaxis_title='Attributes',
)
fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/4_1_mean_score_of_each_attribute_by_gender.png)

### 4.2 Perceived importance of attractiveness vs. actual impact

**Question:** \
How important do people think attractiveness is in potential mate selection vs. its real impact?

**Approach:** \
Comparison between the average importance given to attractiveness (`attr4_1`) and the real impact measured by match and like.

**Result:** \
Attractiveness perceived as critical (~32%), but actual impact slightly lower (~55% to obtain a match based on attractiveness).

In [29]:
df_attractiveness = df[['wave', 'attr1_1', 'attr2_1', 'attr4_1', 'attr', 'match', 'dec', 'like']].copy()
df_attractiveness.sample(10)

# Attr4_1 is 1-10

      wave  attr1_1  attr2_1  attr4_1  attr  match  dec  like
864      3    15.00    40.00      NaN   7.0      0    0   6.0
2460     8    19.15    22.73      7.0   4.0      0    0   3.0
6510    16    20.00    25.00     25.0   6.0      0    0   7.0
2339     7    17.78    20.00     10.0   9.0      0    0   8.0
5589    14    40.00    15.00     30.0   9.0      0    1   7.0
2342     7    17.78    20.00     10.0   8.0      0    0   8.0
1754     5    40.00    50.00      NaN   6.0      0    0   7.0
2198     7    16.00    14.29      9.0   8.0      1    1   8.0
5194    14    12.00    30.00     15.0   5.0      0    0   3.0
6388    15    10.00    25.00     30.0   6.0      0    0   7.0

In [30]:
# Pay attention to the wave 6,7,8,9 
df_attractiveness[df_attractiveness['wave'].isin([6,7,8,9])].describe()

,wave,attr1_1,attr2_1,attr4_1,attr,match,dec,like
count,1562.000000,1557.000000,1557.000000,1557.000000,1554.000000,1562.000000,1562.000000,1534.000000
mean,8.120359,16.158304,19.315883,8.638407,6.309524,0.163892,0.432138,6.177966
std,0.976788,3.515382,4.463158,1.141478,1.921448,0.370296,0.495532,1.843593
min,6.000000,6.670000,9.090000,5.000000,1.000000,0.000000,0.000000,1.000000
25%,7.000000,14.290000,15.690000,8.000000,5.000000,0.000000,0.000000,5.000000
50%,9.000000,16.000000,18.870000,9.000000,6.000000,0.000000,0.000000,6.000000
75%,9.000000,18.000000,22.500000,10.000000,8.000000,0.000000,1.000000,7.000000
max,9.000000,27.780000,31.250000,10.000000,10.000000,1.000000,1.000000,10.000000

In [31]:
# Normalize the data for the wave 6,7,8,9
df_attractiveness['attr4_1'] = df_attractiveness.apply(
    lambda row: row['attr4_1'] * 10 if row['wave'] in [6, 7, 8, 9] else row['attr4_1'],
    axis=1
)
df_attractiveness['attr'] = df_attractiveness['attr'].apply( lambda x : x * 10)
df_attractiveness['like'] = df_attractiveness['like'].apply( lambda x : x * 10)
df_attractiveness['match'] = df_attractiveness['match'].apply( lambda x : x * 100)
df_attractiveness['dec'] = df_attractiveness['dec'].apply( lambda x : x * 100)

In [32]:

df_attractiveness.sample(10)

      wave  attr1_1  attr2_1  attr4_1  attr  match  dec  like
8086    21    30.00    20.00     20.0  60.0      0    0  60.0
863      3    15.00    40.00      NaN  60.0    100  100  60.0
6237    15    30.00    25.00     25.0  50.0      0    0  70.0
4728    12    19.00    20.00     25.0  60.0      0    0  70.0
2274     7    16.67     9.09    100.0  80.0    100  100  70.0
275      2    20.00    30.00      NaN  60.0      0    0  60.0
7592    21    15.00    30.00     25.0  50.0      0    0  40.0
4864    13    40.00    60.00     60.0  20.0      0  100  70.0
3352     9    18.60    18.18     90.0  30.0      0    0  30.0
331      2    20.00    35.00      NaN  50.0      0    0  50.0

In [33]:
print(round(df_attractiveness.mean(), 2))

wave       11.35
attr1_1    22.51
attr2_1    30.36
attr4_1    45.05
attr       61.90
match      16.47
dec        41.99
like       61.34
dtype: float64

In [34]:
# Mean of the importance of the attributes Attractiveness by people
print(round(((df_attractiveness['attr1_1'].mean() + df_attractiveness['attr2_1'].mean() + df_attractiveness['attr4_1'].mean()) / 3),2), '%')

32.64 %

In [35]:
df['attr'].describe()

count    8176.000000
mean        6.189995
std         1.950169
min         0.000000
25%         5.000000
50%         6.000000
75%         8.000000
max        10.000000
Name: attr, dtype: float64

In [36]:
df_attributes_by_match = df.groupby('match')['attr'].mean()
df_pie = df_attributes_by_match.reset_index()
df_pie['match_label'] = df_pie['match'].map({0: "No match", 1: "Match"})

fig = px.pie(
    df_pie,
    values='attr',
    names='match_label',
    title='Attractiveness by Match'
)
fig.update_layout(
    legend_title_text="Match Status"
)
fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/4_2a_attractiveness_by_match.png)

In [37]:
df_attributes_by_like = df.groupby('like')['attr'].mean().reset_index()
df_attributes_by_like

fig = px.scatter(
    x=df_attributes_by_like['like'],
    y=df_attributes_by_like['attr'],
    title='Attractiveness vs Like',
    labels={'like': 'Like', 'attr': 'Attractiveness'},
    trendline='ols',
)
fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/4_2b_attractiveness_vs_like.png)

In [38]:
df_attributes_by_decision = df.groupby('dec')['attr'].mean()
df_pie_dec = df_attributes_by_decision.reset_index()
df_pie_dec['decision_label'] = df_pie_dec['dec'].map({0: "No match", 1: "Match"})

fig = px.pie(
    df_pie_dec,
    values='attr',
    names='decision_label',
    title='Attractiveness by Decision'
)

fig.update_layout(
    legend_title_text="Decision"
)

fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/4_2c_attractiveness_by_decision.png)

In [39]:
df_attractiveness.corr()

,wave,attr1_1,attr2_1,attr4_1,attr,match,dec,like
wave,1.000000,0.075643,0.117865,-0.541099,-0.024282,-0.017404,-0.011598,-0.043057
attr1_1,0.075643,1.000000,0.370598,-0.029771,0.021283,0.014950,-0.021145,0.027599
attr2_1,0.117865,0.370598,1.000000,-0.147775,-0.055613,0.016455,-0.068265,-0.037037
attr4_1,-0.541099,-0.029771,-0.147775,1.000000,0.016407,0.025732,0.007726,-0.010237
attr,-0.024282,0.021283,-0.055613,0.016407,1.000000,0.260676,0.486775,0.667239
match,-0.017404,0.014950,0.016455,0.025732,0.260676,1.000000,0.521943,0.305723
dec,-0.011598,-0.021145,-0.068265,0.007726,0.486775,0.521943,1.000000,0.513463
like,-0.043057,0.027599,-0.037037,-0.010237,0.667239,0.305723,0.513463,1.000000

In [40]:
df[['attr', 'match', 'like', 'dec']].corr()

           attr     match      like       dec
attr   1.000000  0.260676  0.667239  0.486775
match  0.260676  1.000000  0.305723  0.521943
like   0.667239  0.305723  1.000000  0.513463
dec    0.486775  0.521943  0.513463  1.000000

### 4.3 Sharing common interests vs. same racial background
**Question:** \
Are shared interests more important than a shared racial background?

**Approach:** \
Means analysis of `shar` (shared hobbies) vs `imprace` (importance of same race).

**Results:** \
Shared interests influence the match much more than race.

In [41]:
df['imprace'].mean()

3.7847933485962164

In [42]:
df['shar'].mean()

5.474558883873615

In [43]:
# Real impact of shar and imprace on the match
df_share_race_by_match = df.groupby('match')[['shar', 'imprace']].mean()
df_share_race_by_match

           shar   imprace
match
0      5.208230  3.846697
1      6.753571  3.470330

In [44]:

df_impact = df_share_race_by_match.reset_index()
df_impact = df_impact.melt(id_vars='match', var_name='Attribute', value_name='Mean')

fig = px.bar(df_impact, x='Attribute', y='Mean', color='match', barmode='group',
             title='The real impact of shared hobbies vs. race on the match')
fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/4_3_the_real_impact_of_shared_hobbies_vs_race_on_the_match.png)

### 4.4 Predicting one's own perceived value
**Question:**\
Can people accurately predict their own perceived value in the dating market?

**Approach:** 
* Comparison between self-evaluation (`attr3_1`, `sinc3_1`, etc.) and evaluation by others (`attr`, `sinc`, etc.).
* Calculation of the average percentage difference.

**Result:** \
Participants **overestimate_** their attractiveness by about **_8 to 13% on average_**.

In [45]:
df_attributes_me_vs_other = df[['attr', 'sinc', 'fun', 'intel', 'amb', 'attr3_1', 'sinc3_1', 'fun3_1', 'intel3_1', 'amb3_1']].copy()
df_attributes_me_vs_other.sample(10)

,attr,sinc,fun,intel,amb,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1
2920,8.0,7.0,NaN,8.0,7.0,7.0,9.0,8.0,7.0,8.0
5802,6.0,6.0,10.0,6.0,6.0,7.0,7.0,7.0,7.0,10.0
2370,7.0,7.0,5.0,8.0,7.0,10.0,10.0,10.0,10.0,10.0
5300,5.0,9.0,6.0,7.0,NaN,7.0,10.0,8.0,9.0,6.0
7295,7.0,8.0,9.0,9.0,7.0,7.0,7.0,8.0,8.0,8.0
3314,8.0,8.0,6.0,6.0,6.0,8.0,7.0,5.0,10.0,10.0
6233,NaN,NaN,NaN,NaN,NaN,8.0,8.0,10.0,9.0,10.0
6561,8.0,8.0,9.0,9.0,10.0,7.0,8.0,8.0,8.0,8.0
104,6.0,8.0,8.0,8.0,7.0,8.0,9.0,7.0,8.0,5.0
4229,7.0,7.0,7.0,7.0,7.0,9.0,9.0,9.0,9.0,9.0

In [46]:
array = []
df_attributes_me_vs_other['attr_mean'] = df_attributes_me_vs_other['attr'] - df_attributes_me_vs_other['attr3_1']
df_attributes_me_vs_other['sinc_mean'] = df_attributes_me_vs_other['sinc'] - df_attributes_me_vs_other['sinc3_1']
df_attributes_me_vs_other['fun_mean'] = df_attributes_me_vs_other['fun'] - df_attributes_me_vs_other['fun3_1']
df_attributes_me_vs_other['intel_mean'] = df_attributes_me_vs_other['intel'] - df_attributes_me_vs_other['intel3_1']
df_attributes_me_vs_other['amb_mean'] = df_attributes_me_vs_other['amb'] - df_attributes_me_vs_other['amb3_1']

print('Attractiveness difference:', abs(round(df_attributes_me_vs_other['attr_mean'].mean() * 10, 2)), '%')
print('Sincerity difference:', abs(round(df_attributes_me_vs_other['sinc_mean'].mean() * 10, 2)), '%')
print('Fun difference:', abs(round(df_attributes_me_vs_other['fun_mean'].mean() * 10, 2)), '%')
print('Intelligence difference:', abs(round(df_attributes_me_vs_other['intel_mean'].mean() * 10, 2)), '%')
print('Ambition difference:', abs(round(df_attributes_me_vs_other['amb_mean'].mean() * 10, 2)), '%')

Attractiveness difference: 8.96 %
Sincerity difference: 11.25 %
Fun difference: 13.12 %
Intelligence difference: 10.39 %
Ambition difference: 8.15 %

In [47]:
attributes_peers = [
    ('attr', 'attr3_1'),
    ('sinc', 'sinc3_1'),
    ('intel', 'intel3_1'),
    ('fun', 'fun3_1'),
    ('amb', 'amb3_1')
]

fig = make_subplots(rows=1, cols=5, subplot_titles=[f"{a}" for a, _ in attributes_peers])

for i, (col1, col2) in enumerate(attributes_peers):
    fig.add_trace(
        go.Bar(
            name='Others',
            x=['Others'],
            y=[df[col1].mean()],
            marker_color='steelblue',
            showlegend= True if i == 0 else False
        ),
        row=1, col=i+1
    )
    fig.add_trace(
        go.Bar(
            name='Self-rated',
            x=['Self'],
            y=[df[col2].mean()],
            marker_color='orange',
            showlegend= True if i == 0 else False
        ),
        row=1, col=i+1
    )

# Layout
fig.update_layout(
    height=400,
    width=1200,
    title_text='Self vs Perceived Rating Comparison (Mean)',
    barmode='group'
)

fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/4_4_self_vs_perceived_rating_comparison.png)

In [48]:
mean_of_mean_attrributes = abs(round((
    (df_attributes_me_vs_other['attr_mean'].mean() + 
    df_attributes_me_vs_other['sinc_mean'].mean() + 
    df_attributes_me_vs_other['fun_mean'].mean() + 
    df_attributes_me_vs_other['intel_mean'].mean() + 
    df_attributes_me_vs_other['amb_mean'].mean())/5) * 10, 
    2
))
print('The global mean difference of the 5 attributes:', mean_of_mean_attrributes, '%')

The global mean difference of the 5 attributes: 10.37 %

### 4.5 Impact of running order (first or last)
**Question:** \
In terms of getting a second date, is it better to be someone's first speed date of the night or their last?

**Approach:** 
* Use the order variable to identify the first and last speed date.
* Comparison of second date rates by order.

**Results:** \
Little noticeable impact found: order does not seem to significantly influence decisions.

In [49]:
df_first_date = df[df['order'] == 1]
df_pie_first_date = df_first_date['match'].value_counts().reset_index()
df_pie_first_date['match_label'] = df_pie_first_date['match'].map({0: 'No match', 1: 'Match'})


df_last_date = df[df['order'] == df.groupby('iid')['order'].transform('max')]
df_pie_last_date = df_last_date['match'].value_counts().reset_index()
df_pie_last_date['match_label'] = df_pie_last_date['match'].map({0: "No match", 1: "Match"})

fig = make_subplots(rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'domain'}]], subplot_titles=['First date', 'Last date'])

fig.add_trace(
    go.Pie(
        labels=df_pie_first_date['match_label'],
        values=df_pie_first_date['count'],
        name="First date"
    ),
    row=1, col=1
)

fig.add_trace(
    go.Pie(
        labels=df_pie_last_date['match_label'],
        values=df_pie_last_date['count'],
        name="Last date"
    ),
    row=1, col=2
)

fig.update_layout(
    title_text="First date vs Last date - match conversion"
)

fig.show()

![Chart as image](../speed_dating__tinder/charts_as_png/4_5_first_date_vs_last_date___match_conversion.png)