In [1]:
import pandas as pd
import requests
import json
import os
import boto3
import re
from dotenv import load_dotenv

In [2]:
# Villes à analyser
cities = ["Mont Saint Michel",
    "St Malo",
    "Bayeux",
    "Le Havre",
    "Rouen",
    "Paris",
    "Amiens",
    "Lille",
    "Strasbourg",
    "Chateau du Haut Koenigsbourg",
    "Colmar",
    "Eguisheim",
    "Besancon",
    "Dijon",
    "Annecy",
    "Grenoble",
    "Lyon",
    "Rougon",#"Gorges du Verdon", # Probleme avec ce nom de ville
    "Bormes les Mimosas",
    "Cassis",
    "Marseille",
    "Aix en Provence",
    "Avignon",
    "Uzes",
    "Nimes",
    "Aigues Mortes",
    "Saintes Maries de la mer",
    "Collioure",
    "Carcassonne",
    "Ariege",
    "Toulouse",
    "Montauban",
    "Biarritz",
    "Bayonne",
    "La Rochelle"]

In [3]:
# Get the latitude and longitude of the cities
cities_location = []

headers = {
    "User-Agent": "QHA"
}

for city in cities:
    r_location = requests.get(f"https://nominatim.openstreetmap.org/search?format=json&city={city}", headers=headers)
    location_data = r_location.json()

    current_city = {
        "name": location_data[0]['name'],
        "lat": location_data[0]['lat'],
        "lon": location_data[0]['lon'],
    }

    cities_location.append(current_city)
print(cities_location)

[{'name': 'Mont-Saint-Michel', 'lat': '46.7798558', 'lon': '-75.3362610'}, {'name': 'St. Malo', 'lat': '49.3146950', 'lon': '-96.9538228'}, {'name': 'Bayeux', 'lat': '49.2764624', 'lon': '-0.7024738'}, {'name': 'Le Havre', 'lat': '49.4938975', 'lon': '0.1079732'}, {'name': 'Rouen', 'lat': '49.4404591', 'lon': '1.0939658'}, {'name': 'Paris', 'lat': '48.8588897', 'lon': '2.3200410'}, {'name': 'Amiens', 'lat': '49.8941708', 'lon': '2.2956951'}, {'name': 'Lille', 'lat': '50.6365654', 'lon': '3.0635282'}, {'name': 'Strasbourg', 'lat': '48.5846140', 'lon': '7.7507127'}, {'name': 'Château du Haut-Kœnigsbourg', 'lat': '48.2495226', 'lon': '7.3454923'}, {'name': 'Colmar', 'lat': '48.0777517', 'lon': '7.3579641'}, {'name': 'Eguisheim', 'lat': '48.0447968', 'lon': '7.3079618'}, {'name': 'Besançon', 'lat': '47.2380222', 'lon': '6.0243622'}, {'name': 'Dijon', 'lat': '47.3215806', 'lon': '5.0414701'}, {'name': 'Annecy', 'lat': '45.8992348', 'lon': '6.1288847'}, {'name': 'Grenoble', 'lat': '45.1875602', 'lon': '5.7357819'}, {'name': 'Lyon', 'lat': '45.7578137', 'lon': '4.8320114'}, {'name': 'Rougon', 'lat': '43.7989923', 'lon': '6.4021491'}, {'name': 'Bormes-les-Mimosas', 'lat': '43.1506968', 'lon': '6.3419285'}, {'name': 'Cassis', 'lat': '43.2140359', 'lon': '5.5396318'}, {'name': 'Marseille', 'lat': '43.2961743', 'lon': '5.3699525'}, {'name': 'Aix-en-Provence', 'lat': '43.5298424', 'lon': '5.4474738'}, {'name': 'Avignon', 'lat': '43.9492493', 'lon': '4.8059012'}, {'name': 'Uzès', 'lat': '44.0121279', 'lon': '4.4196718'}, {'name': 'Nîmes', 'lat': '43.8374249', 'lon': '4.3600687'}, {'name': 'Aigues-Mortes', 'lat': '43.5661521', 'lon': '4.1915400'}, {'name': 'Saintes-Maries-de-la-Mer', 'lat': '43.4515922', 'lon': '4.4277202'}, {'name': 'Collioure', 'lat': '42.5250500', 'lon': '3.0831554'}, {'name': 'Carcassonne', 'lat': '43.2130358', 'lon': '2.3491069'}, {'name': 'Tarascon-sur-Ariège', 'lat': '42.8458016', 'lon': '1.6067586'}, {'name': 'Toulouse', 'lat': '43.6044622', 'lon': '1.4442469'}, {'name': 'Montauban', 'lat': '44.0175835', 'lon': '1.3549991'}, {'name': 'Biarritz', 'lat': '43.4832523', 'lon': '-1.5592776'}, {'name': 'Bayonne', 'lat': '43.4945144', 'lon': '-1.4736657'}, {'name': 'La Rochelle', 'lat': '46.1597320', 'lon': '-1.1515951'}]

In [4]:
df_location = pd.DataFrame(cities_location)
df_location

                           name         lat          lon
0             Mont-Saint-Michel  46.7798558  -75.3362610
1                      St. Malo  49.3146950  -96.9538228
2                        Bayeux  49.2764624   -0.7024738
3                      Le Havre  49.4938975    0.1079732
4                         Rouen  49.4404591    1.0939658
5                         Paris  48.8588897    2.3200410
6                        Amiens  49.8941708    2.2956951
7                         Lille  50.6365654    3.0635282
8                    Strasbourg  48.5846140    7.7507127
9   Château du Haut-Kœnigsbourg  48.2495226    7.3454923
10                       Colmar  48.0777517    7.3579641
11                    Eguisheim  48.0447968    7.3079618
12                     Besançon  47.2380222    6.0243622
13                        Dijon  47.3215806    5.0414701
14                       Annecy  45.8992348    6.1288847
15                     Grenoble  45.1875602    5.7357819
16                         Lyon  45.7578137    4.8320114
17                       Rougon  43.7989923    6.4021491
18           Bormes-les-Mimosas  43.1506968    6.3419285
19                       Cassis  43.2140359    5.5396318
20                    Marseille  43.2961743    5.3699525
21              Aix-en-Provence  43.5298424    5.4474738
22                      Avignon  43.9492493    4.8059012
23                         Uzès  44.0121279    4.4196718
24                        Nîmes  43.8374249    4.3600687
25                Aigues-Mortes  43.5661521    4.1915400
26     Saintes-Maries-de-la-Mer  43.4515922    4.4277202
27                    Collioure  42.5250500    3.0831554
28                  Carcassonne  43.2130358    2.3491069
29          Tarascon-sur-Ariège  42.8458016    1.6067586
30                     Toulouse  43.6044622    1.4442469
31                    Montauban  44.0175835    1.3549991
32                     Biarritz  43.4832523   -1.5592776
33                      Bayonne  43.4945144   -1.4736657
34                  La Rochelle  46.1597320   -1.1515951

In [5]:
load_dotenv()
api_weather_key = os.getenv("OPENWEATHER_API_KEY")

params = {
    "appid": api_weather_key,
    "units": "metric",
    "lang": "fr",
    "cnt": 5,
}

lat = 44.8333
lon = -0.5667
cnt = 16

url_test = f"https://api.openweathermap.org/data/2.5/forecast?lat=44.8333&lon=-0.5667&units=metric&lang=fr&cnt=7&appid={api_weather_key}"

r = requests.get(url_test)
data = r.json()

data['list']

[{'dt': 1747656000,
  'main': {'temp': 19.19,
   'feels_like': 19.31,
   'temp_min': 19.19,
   'temp_max': 21.31,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 82,
   'temp_kf': -2.12},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'couvert',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 5.29, 'deg': 250, 'gust': 6.92},
  'visibility': 10000,
  'pop': 0.73,
  'sys': {'pod': 'd'},
  'dt_txt': '2025-05-19 12:00:00'},
 {'dt': 1747666800,
  'main': {'temp': 19.85,
   'feels_like': 19.85,
   'temp_min': 19.85,
   'temp_max': 21.18,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 75,
   'temp_kf': -1.33},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'couvert',
    'icon': '04d'}],
  'clouds': {'all': 88},
  'wind': {'speed': 5.47, 'deg': 246, 'gust': 6.07},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2025-05-19 15:00:00'},
 {'dt': 1747677600,
  'main': {'temp': 18.13,
   'feels_like': 17.96,
   'temp_min': 17.6,
   'temp_max': 18.13,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 75,
   'temp_kf': 0.53},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'couvert',
    'icon': '04d'}],
  'clouds': {'all': 89},
  'wind': {'speed': 5.02, 'deg': 243, 'gust': 7.7},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2025-05-19 18:00:00'},
 {'dt': 1747688400,
  'main': {'temp': 16.17,
   'feels_like': 16.06,
   'temp_min': 16.17,
   'temp_max': 16.17,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1009,
   'humidity': 85,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'couvert',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.67, 'deg': 241, 'gust': 8.55},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2025-05-19 21:00:00'},
 {'dt': 1747699200,
  'main': {'temp': 15.09,
   'feels_like': 15.11,
   'temp_min': 15.09,
   'temp_max': 15.09,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1009,
   'humidity': 94,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'légère pluie',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.58, 'deg': 255, 'gust': 5.25},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.27},
  'sys': {'pod': 'n'},
  'dt_txt': '2025-05-20 00:00:00'},
 {'dt': 1747710000,
  'main': {'temp': 14.59,
   'feels_like': 14.64,
   'temp_min': 14.59,
   'temp_max': 14.59,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1010,
   'humidity': 97,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'légère pluie',
    'icon': '10n'}],
  'clouds': {'all': 95},
  'wind': {'speed': 3.5, 'deg': 299, 'gust': 8.41},
  'visibility': 10000,
  'pop': 0.45,
  'rain': {'3h': 0.24},
  'sys': {'pod': 'n'},
  'dt_txt': '2025-05-20 03:00:00'},
 {'dt': 1747720800,
  'main': {'temp': 15.12,
   'feels_like': 15.04,
   'temp_min': 15.12,
   'temp_max': 15.12,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1012,
   'humidity': 90,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'couvert',
    'icon': '04d'}],
  'clouds': {'all': 97},
  'wind': {'speed': 3.59, 'deg': 313, 'gust': 9.09},
  'visibility': 10000,
  'pop': 0.26,
  'sys': {'pod': 'd'},
  'dt_txt': '2025-05-20 06:00:00'}]

In [15]:
all_weather = []
weather_params = {
    "appid": api_weather_key,
    "units": "metric",
    "lang": "fr",
    "cnt": 7,
}

for index,weather in enumerate(cities_location):
    temp_score = 0
    rain = 0
    wind = 0
    wind_score = 0
    rain_score = 0
    
    r_weather = requests.get(f"https://api.openweathermap.org/data/2.5/forecast?lat={weather['lat']}&lon={weather['lon']}", params=weather_params)
    current_weather = r_weather.json()['list']

    for i in range(len(current_weather)):
        temp_score = round(temp_score + (current_weather[i]['main']['feels_like'] / len(current_weather)), 2)
        rain = current_weather[i].get('rain', 0)
        
        if rain != 0:
            rain_key = list(current_weather[i]['rain'].keys())[0]
            match = re.search(r'\d+', rain_key)
            hours = 0

            if match:
                hours = int(match.group())

            rain_daily_score = hours * current_weather[i]['rain'][rain_key]
            rain_score = round(rain_score + (rain_daily_score / len(current_weather)), 2)
        else:
            rain_score = rain_score + 0

        wind = round(wind + (current_weather[i]['wind']['speed'] / len(current_weather)), 2)

        beaufort_score = 0 # Beaufort scale
        if current_weather[i]['wind']['speed'] == 0:
            beaufort_score = 0
        elif current_weather[i]['wind']['speed'] < 5:
            beaufort_score = 1
        elif current_weather[i]['wind']['speed'] < 11:
            beaufort_score = 2
        elif current_weather[i]['wind']['speed'] < 19:
            beaufort_score = 3
        elif current_weather[i]['wind']['speed'] < 28:
            beaufort_score = 4
        elif current_weather[i]['wind']['speed'] < 38:
            beaufort_score = 5
        elif current_weather[i]['wind']['speed'] < 49:
            beaufort_score = 6
        elif current_weather[i]['wind']['speed'] < 61:
            beaufort_score = 7
        elif current_weather[i]['wind']['speed'] < 74:
            beaufort_score = 8
        elif current_weather[i]['wind']['speed'] < 88:
            beaufort_score = 9
        elif current_weather[i]['wind']['speed'] < 102:
            beaufort_score = 10
        elif current_weather[i]['wind']['speed'] < 117:
            beaufort_score = 11
        elif current_weather[i]['wind']['speed'] > 117:
            beaufort_score = 12

        if current_weather[i]['main']['feels_like'] < 25 or current_weather[i]['wind']['speed'] > 30:
            wind_penalty = beaufort_score
        else:
            wind_penalty = 0

        wind_score = round(wind_score + (wind_penalty / len(current_weather)), 2)

    weather_score = round(temp_score - rain_score - wind_score, 3)


    current_weather_data = {
        "index" : index,
        "name" : weather['name'],
        "temperature_mean" : temp_score,
        "rain_mean" : rain_score,
        "wind_score" : wind_score,
        "score" : weather_score,
    }
    all_weather.append(current_weather_data)
       
all_weather

[{'index': 0,
  'name': 'Mont-Saint-Michel',
  'temperature_mean': 3.98,
  'rain_mean': 0,
  'wind_score': 1.58,
  'score': 2.4},
 {'index': 1,
  'name': 'St. Malo',
  'temperature_mean': 5.16,
  'rain_mean': 1.06,
  'wind_score': 1.73,
  'score': 2.37},
 {'index': 2,
  'name': 'Bayeux',
  'temperature_mean': 13.37,
  'rain_mean': 0,
  'wind_score': 1.58,
  'score': 11.79},
 {'index': 3,
  'name': 'Le Havre',
  'temperature_mean': 14.17,
  'rain_mean': 0,
  'wind_score': 1.58,
  'score': 12.59},
 {'index': 4,
  'name': 'Rouen',
  'temperature_mean': 15.07,
  'rain_mean': 0,
  'wind_score': 1.13,
  'score': 13.94},
 {'index': 5,
  'name': 'Paris',
  'temperature_mean': 15.89,
  'rain_mean': 0,
  'wind_score': 0.98,
  'score': 14.91},
 {'index': 6,
  'name': 'Amiens',
  'temperature_mean': 14.05,
  'rain_mean': 0,
  'wind_score': 1.13,
  'score': 12.92},
 {'index': 7,
  'name': 'Lille',
  'temperature_mean': 14.84,
  'rain_mean': 0,
  'wind_score': 0.98,
  'score': 13.86},
 {'index': 8,
  'name': 'Strasbourg',
  'temperature_mean': 17.04,
  'rain_mean': 0,
  'wind_score': 0.98,
  'score': 16.06},
 {'index': 9,
  'name': 'Château du Haut-Kœnigsbourg',
  'temperature_mean': 14.74,
  'rain_mean': 0.57,
  'wind_score': 0.98,
  'score': 13.19},
 {'index': 10,
  'name': 'Colmar',
  'temperature_mean': 17.75,
  'rain_mean': 1.2,
  'wind_score': 0.98,
  'score': 15.57},
 {'index': 11,
  'name': 'Eguisheim',
  'temperature_mean': 17.54,
  'rain_mean': 1.26,
  'wind_score': 0.98,
  'score': 15.3},
 {'index': 12,
  'name': 'Besançon',
  'temperature_mean': 18.13,
  'rain_mean': 0.54,
  'wind_score': 0.98,
  'score': 16.61},
 {'index': 13,
  'name': 'Dijon',
  'temperature_mean': 16.7,
  'rain_mean': 0.95,
  'wind_score': 0.98,
  'score': 14.77},
 {'index': 14,
  'name': 'Annecy',
  'temperature_mean': 16.89,
  'rain_mean': 2.86,
  'wind_score': 0.98,
  'score': 13.05},
 {'index': 15,
  'name': 'Grenoble',
  'temperature_mean': 19.7,
  'rain_mean': 3.38,
  'wind_score': 0.98,
  'score': 15.34},
 {'index': 16,
  'name': 'Lyon',
  'temperature_mean': 17.72,
  'rain_mean': 0.45,
  'wind_score': 1.28,
  'score': 15.99},
 {'index': 17,
  'name': 'Rougon',
  'temperature_mean': 13.55,
  'rain_mean': 1.22,
  'wind_score': 0.98,
  'score': 11.35},
 {'index': 18,
  'name': 'Bormes-les-Mimosas',
  'temperature_mean': 17.92,
  'rain_mean': 1.07,
  'wind_score': 1.43,
  'score': 15.42},
 {'index': 19,
  'name': 'Cassis',
  'temperature_mean': 18.87,
  'rain_mean': 2.79,
  'wind_score': 1.88,
  'score': 14.2},
 {'index': 20,
  'name': 'Marseille',
  'temperature_mean': 19.92,
  'rain_mean': 3.06,
  'wind_score': 1.73,
  'score': 15.13},
 {'index': 21,
  'name': 'Aix-en-Provence',
  'temperature_mean': 18.67,
  'rain_mean': 1.81,
  'wind_score': 1.13,
  'score': 15.73},
 {'index': 22,
  'name': 'Avignon',
  'temperature_mean': 19.17,
  'rain_mean': 2.39,
  'wind_score': 1.28,
  'score': 15.5},
 {'index': 23,
  'name': 'Uzès',
  'temperature_mean': 17.81,
  'rain_mean': 3.34,
  'wind_score': 1.28,
  'score': 13.19},
 {'index': 24,
  'name': 'Nîmes',
  'temperature_mean': 18.37,
  'rain_mean': 4.91,
  'wind_score': 1.43,
  'score': 12.03},
 {'index': 25,
  'name': 'Aigues-Mortes',
  'temperature_mean': 18.52,
  'rain_mean': 4.53,
  'wind_score': 1.88,
  'score': 12.11},
 {'index': 26,
  'name': 'Saintes-Maries-de-la-Mer',
  'temperature_mean': 18.18,
  'rain_mean': 4.01,
  'wind_score': 2.03,
  'score': 12.14},
 {'index': 27,
  'name': 'Collioure',
  'temperature_mean': 18.91,
  'rain_mean': 0.89,
  'wind_score': 1.28,
  'score': 16.74},
 {'index': 28,
  'name': 'Carcassonne',
  'temperature_mean': 16.42,
  'rain_mean': 12.58,
  'wind_score': 1.43,
  'score': 2.41},
 {'index': 29,
  'name': 'Tarascon-sur-Ariège',
  'temperature_mean': 15.66,
  'rain_mean': 8.45,
  'wind_score': 0.98,
  'score': 6.23},
 {'index': 30,
  'name': 'Toulouse',
  'temperature_mean': 16.14,
  'rain_mean': 10.72,
  'wind_score': 1.73,
  'score': 3.69},
 {'index': 31,
  'name': 'Montauban',
  'temperature_mean': 16.51,
  'rain_mean': 11.85,
  'wind_score': 1.73,
  'score': 2.93},
 {'index': 32,
  'name': 'Biarritz',
  'temperature_mean': 15.29,
  'rain_mean': 3.63,
  'wind_score': 2.03,
  'score': 9.63},
 {'index': 33,
  'name': 'Bayonne',
  'temperature_mean': 14.92,
  'rain_mean': 4.88,
  'wind_score': 2.03,
  'score': 8.01},
 {'index': 34,
  'name': 'La Rochelle',
  'temperature_mean': 17.08,
  'rain_mean': 1.75,
  'wind_score': 1.58,
  'score': 13.75}]

In [16]:
df_weather = pd.DataFrame(all_weather)
df_weather = df_weather.sort_values(by='score', ascending=False)
df_weather

,index,name,temperature_mean,rain_mean,wind_score,score
27,27,Collioure,18.91,0.89,1.28,16.74
12,12,Besançon,18.13,0.54,0.98,16.61
8,8,Strasbourg,17.04,0.00,0.98,16.06
16,16,Lyon,17.72,0.45,1.28,15.99
21,21,Aix-en-Provence,18.67,1.81,1.13,15.73
10,10,Colmar,17.75,1.20,0.98,15.57
22,22,Avignon,19.17,2.39,1.28,15.50
18,18,Bormes-les-Mimosas,17.92,1.07,1.43,15.42
15,15,Grenoble,19.70,3.38,0.98,15.34
11,11,Eguisheim,17.54,1.26,0.98,15.30
20,20,Marseille,19.92,3.06,1.73,15.13
5,5,Paris,15.89,0.00,0.98,14.91
13,13,Dijon,16.70,0.95,0.98,14.77
19,19,Cassis,18.87,2.79,1.88,14.20
4,4,Rouen,15.07,0.00,1.13,13.94
7,7,Lille,14.84,0.00,0.98,13.86
34,34,La Rochelle,17.08,1.75,1.58,13.75
9,9,Château du Haut-Kœnigsbourg,14.74,0.57,0.98,13.19
23,23,Uzès,17.81,3.34,1.28,13.19
14,14,Annecy,16.89,2.86,0.98,13.05
6,6,Amiens,14.05,0.00,1.13,12.92
3,3,Le Havre,14.17,0.00,1.58,12.59
26,26,Saintes-Maries-de-la-Mer,18.18,4.01,2.03,12.14
25,25,Aigues-Mortes,18.52,4.53,1.88,12.11
24,24,Nîmes,18.37,4.91,1.43,12.03
2,2,Bayeux,13.37,0.00,1.58,11.79
17,17,Rougon,13.55,1.22,0.98,11.35
32,32,Biarritz,15.29,3.63,2.03,9.63
33,33,Bayonne,14.92,4.88,2.03,8.01
29,29,Tarascon-sur-Ariège,15.66,8.45,0.98,6.23
30,30,Toulouse,16.14,10.72,1.73,3.69
31,31,Montauban,16.51,11.85,1.73,2.93
28,28,Carcassonne,16.42,12.58,1.43,2.41
0,0,Mont-Saint-Michel,3.98,0.00,1.58,2.40
1,1,St. Malo,5.16,1.06,1.73,2.37

In [18]:
df_weather.to_csv("export/weather.csv", index=False)