In [1]:
import pandas as pd
import requests
import json
import os
import boto3
import re
from dotenv import load_dotenv

In [2]:
# Villes à analyser
cities = ["Mont Saint Michel",
    "St Malo",
    "Bayeux",
    "Le Havre",
    "Rouen",
    "Paris",
    "Amiens",
    "Lille",
    "Strasbourg",
    "Chateau du Haut Koenigsbourg",
    "Colmar",
    "Eguisheim",
    "Besancon",
    "Dijon",
    "Annecy",
    "Grenoble",
    "Lyon",
    "Rougon",#"Gorges du Verdon", # Probleme avec ce nom de ville
    "Bormes les Mimosas",
    "Cassis",
    "Marseille",
    "Aix en Provence",
    "Avignon",
    "Uzes",
    "Nimes",
    "Aigues Mortes",
    "Saintes Maries de la mer",
    "Collioure",
    "Carcassonne",
    "Ariege",
    "Toulouse",
    "Montauban",
    "Biarritz",
    "Bayonne",
    "La Rochelle"]

In [3]:
# Get the latitude and longitude of the cities
cities_location = []

headers = {
    "User-Agent": "QHA"
}

for city in cities:
    r_location = requests.get(f"https://nominatim.openstreetmap.org/search?format=json&city={city}", headers=headers)
    location_data = r_location.json()

    current_city = {
        "name": location_data[0]['name'],
        "lat": location_data[0]['lat'],
        "lon": location_data[0]['lon'],
    }

    cities_location.append(current_city)
print(cities_location)

[{'name': 'Mont-Saint-Michel', 'lat': '46.7798558', 'lon': '-75.3362610'}, {'name': 'St. Malo', 'lat': '49.3146950', 'lon': '-96.9538228'}, {'name': 'Bayeux', 'lat': '49.2764624', 'lon': '-0.7024738'}, {'name': 'Le Havre', 'lat': '49.4938975', 'lon': '0.1079732'}, {'name': 'Rouen', 'lat': '49.4404591', 'lon': '1.0939658'}, {'name': 'Paris', 'lat': '48.8588897', 'lon': '2.3200410'}, {'name': 'Amiens', 'lat': '49.8941708', 'lon': '2.2956951'}, {'name': 'Lille', 'lat': '50.6365654', 'lon': '3.0635282'}, {'name': 'Strasbourg', 'lat': '48.5846140', 'lon': '7.7507127'}, {'name': 'Château du Haut-Kœnigsbourg', 'lat': '48.2495226', 'lon': '7.3454923'}, {'name': 'Colmar', 'lat': '48.0777517', 'lon': '7.3579641'}, {'name': 'Eguisheim', 'lat': '48.0447968', 'lon': '7.3079618'}, {'name': 'Besançon', 'lat': '47.2380222', 'lon': '6.0243622'}, {'name': 'Dijon', 'lat': '47.3215806', 'lon': '5.0414701'}, {'name': 'Annecy', 'lat': '45.8992348', 'lon': '6.1288847'}, {'name': 'Grenoble', 'lat': '45.1875602', 'lon': '5.7357819'}, {'name': 'Lyon', 'lat': '45.7578137', 'lon': '4.8320114'}, {'name': 'Rougon', 'lat': '43.7989923', 'lon': '6.4021491'}, {'name': 'Bormes-les-Mimosas', 'lat': '43.1506968', 'lon': '6.3419285'}, {'name': 'Cassis', 'lat': '43.2140359', 'lon': '5.5396318'}, {'name': 'Marseille', 'lat': '43.2961743', 'lon': '5.3699525'}, {'name': 'Aix-en-Provence', 'lat': '43.5298424', 'lon': '5.4474738'}, {'name': 'Avignon', 'lat': '43.9492493', 'lon': '4.8059012'}, {'name': 'Uzès', 'lat': '44.0121279', 'lon': '4.4196718'}, {'name': 'Nîmes', 'lat': '43.8374249', 'lon': '4.3600687'}, {'name': 'Aigues-Mortes', 'lat': '43.5661521', 'lon': '4.1915400'}, {'name': 'Saintes-Maries-de-la-Mer', 'lat': '43.4515922', 'lon': '4.4277202'}, {'name': 'Collioure', 'lat': '42.5250500', 'lon': '3.0831554'}, {'name': 'Carcassonne', 'lat': '43.2130358', 'lon': '2.3491069'}, {'name': 'Tarascon-sur-Ariège', 'lat': '42.8458016', 'lon': '1.6067586'}, {'name': 'Toulouse', 'lat': '43.6044622', 'lon': '1.4442469'}, {'name': 'Montauban', 'lat': '44.0175835', 'lon': '1.3549991'}, {'name': 'Biarritz', 'lat': '43.4832523', 'lon': '-1.5592776'}, {'name': 'Bayonne', 'lat': '43.4945144', 'lon': '-1.4736657'}, {'name': 'La Rochelle', 'lat': '46.1597320', 'lon': '-1.1515951'}]

In [4]:
df_location = pd.DataFrame(cities_location)
df_location

                           name         lat          lon
0             Mont-Saint-Michel  46.7798558  -75.3362610
1                      St. Malo  49.3146950  -96.9538228
2                        Bayeux  49.2764624   -0.7024738
3                      Le Havre  49.4938975    0.1079732
4                         Rouen  49.4404591    1.0939658
5                         Paris  48.8588897    2.3200410
6                        Amiens  49.8941708    2.2956951
7                         Lille  50.6365654    3.0635282
8                    Strasbourg  48.5846140    7.7507127
9   Château du Haut-Kœnigsbourg  48.2495226    7.3454923
10                       Colmar  48.0777517    7.3579641
11                    Eguisheim  48.0447968    7.3079618
12                     Besançon  47.2380222    6.0243622
13                        Dijon  47.3215806    5.0414701
14                       Annecy  45.8992348    6.1288847
15                     Grenoble  45.1875602    5.7357819
16                         Lyon  45.7578137    4.8320114
17                       Rougon  43.7989923    6.4021491
18           Bormes-les-Mimosas  43.1506968    6.3419285
19                       Cassis  43.2140359    5.5396318
20                    Marseille  43.2961743    5.3699525
21              Aix-en-Provence  43.5298424    5.4474738
22                      Avignon  43.9492493    4.8059012
23                         Uzès  44.0121279    4.4196718
24                        Nîmes  43.8374249    4.3600687
25                Aigues-Mortes  43.5661521    4.1915400
26     Saintes-Maries-de-la-Mer  43.4515922    4.4277202
27                    Collioure  42.5250500    3.0831554
28                  Carcassonne  43.2130358    2.3491069
29          Tarascon-sur-Ariège  42.8458016    1.6067586
30                     Toulouse  43.6044622    1.4442469
31                    Montauban  44.0175835    1.3549991
32                     Biarritz  43.4832523   -1.5592776
33                      Bayonne  43.4945144   -1.4736657
34                  La Rochelle  46.1597320   -1.1515951

In [5]:
load_dotenv()
api_weather_key = os.getenv("OPENWEATHER_API_KEY")

params = {
    "appid": api_weather_key,
    "units": "metric",
    "lang": "fr",
    "cnt": 5,
}

lat = 44.8333
lon = -0.5667
cnt = 16

url_test = f"https://api.openweathermap.org/data/2.5/forecast?lat=44.8333&lon=-0.5667&units=metric&lang=fr&cnt=7&appid={api_weather_key}"

r = requests.get(url_test)
data = r.json()

data['list']

[{'dt': 1747645200,
  'main': {'temp': 16.19,
   'feels_like': 16.32,
   'temp_min': 16.19,
   'temp_max': 17.66,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 94,
   'temp_kf': -1.47},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'légère pluie',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.01, 'deg': 224, 'gust': 7.53},
  'visibility': 10000,
  'pop': 0.96,
  'rain': {'3h': 0.69},
  'sys': {'pod': 'd'},
  'dt_txt': '2025-05-19 09:00:00'},
 {'dt': 1747656000,
  'main': {'temp': 17.43,
   'feels_like': 17.5,
   'temp_min': 17.43,
   'temp_max': 19.91,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 87,
   'temp_kf': -2.48},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'couvert',
    'icon': '04d'}],
  'clouds': {'all': 97},
  'wind': {'speed': 5.81, 'deg': 250, 'gust': 7.91},
  'visibility': 10000,
  'pop': 0.85,
  'sys': {'pod': 'd'},
  'dt_txt': '2025-05-19 12:00:00'},
 {'dt': 1747666800,
  'main': {'temp': 19.41,
   'feels_like': 19.29,
   'temp_min': 19.41,
   'temp_max': 21.02,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1007,
   'humidity': 72,
   'temp_kf': -1.61},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'nuageux',
    'icon': '04d'}],
  'clouds': {'all': 73},
  'wind': {'speed': 5.05, 'deg': 261, 'gust': 6.07},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2025-05-19 15:00:00'},
 {'dt': 1747677600,
  'main': {'temp': 17.77,
   'feels_like': 17.72,
   'temp_min': 17.77,
   'temp_max': 17.77,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 81,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'légère pluie',
    'icon': '10d'}],
  'clouds': {'all': 76},
  'wind': {'speed': 3.91, 'deg': 262, 'gust': 6.36},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.13},
  'sys': {'pod': 'd'},
  'dt_txt': '2025-05-19 18:00:00'},
 {'dt': 1747688400,
  'main': {'temp': 16.01,
   'feels_like': 16.02,
   'temp_min': 16.01,
   'temp_max': 16.01,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1009,
   'humidity': 90,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'légère pluie',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.6, 'deg': 265, 'gust': 9.28},
  'visibility': 10000,
  'pop': 0.31,
  'rain': {'3h': 0.23},
  'sys': {'pod': 'n'},
  'dt_txt': '2025-05-19 21:00:00'},
 {'dt': 1747699200,
  'main': {'temp': 16.07,
   'feels_like': 16.16,
   'temp_min': 16.07,
   'temp_max': 16.07,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1009,
   'humidity': 93,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'légère pluie',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.73, 'deg': 279, 'gust': 8.99},
  'visibility': 10000,
  'pop': 0.6,
  'rain': {'3h': 0.52},
  'sys': {'pod': 'n'},
  'dt_txt': '2025-05-20 00:00:00'},
 {'dt': 1747710000,
  'main': {'temp': 15.47,
   'feels_like': 15.53,
   'temp_min': 15.47,
   'temp_max': 15.47,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1010,
   'humidity': 94,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'légère pluie',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.35, 'deg': 294, 'gust': 9.86},
  'visibility': 10000,
  'pop': 0.72,
  'rain': {'3h': 0.38},
  'sys': {'pod': 'n'},
  'dt_txt': '2025-05-20 03:00:00'}]

In [16]:
all_weather = []
weather_params = {
    "appid": api_weather_key,
    "units": "metric",
    "lang": "fr",
    "cnt": 7,
}

for weather in cities_location:
    temp_score = 0
    rain = 0
    wind = 0
    wind_score = 0
    rain_score = 0

    r_weather = requests.get(f"https://api.openweathermap.org/data/2.5/forecast?lat={weather['lat']}&lon={weather['lon']}", params=weather_params)
    current_weather = r_weather.json()['list']

    for i in range(len(current_weather)):
        temp_score = round(temp_score + (current_weather[i]['main']['feels_like'] / len(current_weather)), 2)
        rain = current_weather[i].get('rain', 0)
        #print("rain", rain)
        
        if rain != 0:
            rain_key = list(current_weather[i]['rain'].keys())[0]
            match = re.search(r'\d+', rain_key)
            hours = 0

            if match:
                hours = int(match.group())

            rain_daily_score = hours * current_weather[i]['rain'][rain_key]
            rain_score = round(rain_score + (rain_daily_score / len(current_weather)), 2)
        else:
            rain_score = rain_score + 0

        wind = round(wind + (current_weather[i]['wind']['speed'] / len(current_weather)), 2)

        beaufort_score = 0 # Beaufort scale
        if current_weather[i]['wind']['speed'] == 0:
            beaufort_score = 0
        elif current_weather[i]['wind']['speed'] < 5:
            beaufort_score = 1
        elif current_weather[i]['wind']['speed'] < 11:
            beaufort_score = 2
        elif current_weather[i]['wind']['speed'] < 19:
            beaufort_score = 3
        elif current_weather[i]['wind']['speed'] < 28:
            beaufort_score = 4
        elif current_weather[i]['wind']['speed'] < 38:
            beaufort_score = 5
        elif current_weather[i]['wind']['speed'] < 49:
            beaufort_score = 6
        elif current_weather[i]['wind']['speed'] < 61:
            beaufort_score = 7
        elif current_weather[i]['wind']['speed'] < 74:
            beaufort_score = 8
        elif current_weather[i]['wind']['speed'] < 88:
            beaufort_score = 9
        elif current_weather[i]['wind']['speed'] < 102:
            beaufort_score = 10
        elif current_weather[i]['wind']['speed'] < 117:
            beaufort_score = 11
        elif current_weather[i]['wind']['speed'] > 117:
            beaufort_score = 12

        if current_weather[i]['main']['feels_like'] < 25 or current_weather[i]['wind']['speed'] > 30:
            wind_penalty = beaufort_score
        else:
            wind_penalty = 0

        wind_score = round(wind_score + (wind_penalty / len(current_weather)), 2)

    weather_score = round(temp_score - rain_score - wind_score, 3)


    current_weather_data = {
        "name" : weather['name'],
        "temperature" : temp_score,
        "rain" : rain_score,
        "wind" : wind,
        "score" : weather_score,
    }
    all_weather.append(current_weather_data)
       
all_weather

[{'name': 'Mont-Saint-Michel',
  'temperature': 4.48,
  'rain': 0,
  'wind': 5.49,
  'score': 2.75},
 {'name': 'St. Malo',
  'temperature': 5.59,
  'rain': 0.5,
  'wind': 6.43,
  'score': 3.36},
 {'name': 'Bayeux',
  'temperature': 12.59,
  'rain': 0,
  'wind': 5.03,
  'score': 11.01},
 {'name': 'Le Havre',
  'temperature': 13.5,
  'rain': 0,
  'wind': 5.49,
  'score': 11.77},
 {'name': 'Rouen',
  'temperature': 13.45,
  'rain': 0,
  'wind': 3.89,
  'score': 12.47},
 {'name': 'Paris',
  'temperature': 14.93,
  'rain': 0,
  'wind': 2.91,
  'score': 13.95},
 {'name': 'Amiens',
  'temperature': 13.94,
  'rain': 0,
  'wind': 4.01,
  'score': 12.96},
 {'name': 'Lille',
  'temperature': 12.93,
  'rain': 0,
  'wind': 4.07,
  'score': 11.95},
 {'name': 'Strasbourg',
  'temperature': 16.17,
  'rain': 0.05,
  'wind': 2.64,
  'score': 15.14},
 {'name': 'Château du Haut-Kœnigsbourg',
  'temperature': 13.36,
  'rain': 0.1,
  'wind': 1.78,
  'score': 12.28},
 {'name': 'Colmar',
  'temperature': 16.53,
  'rain': 0.06,
  'wind': 2.08,
  'score': 15.49},
 {'name': 'Eguisheim',
  'temperature': 16.43,
  'rain': 0.08,
  'wind': 2.07,
  'score': 15.37},
 {'name': 'Besançon',
  'temperature': 17.07,
  'rain': 3.82,
  'wind': 2.35,
  'score': 12.27},
 {'name': 'Dijon',
  'temperature': 15.24,
  'rain': 2.99,
  'wind': 1.56,
  'score': 11.27},
 {'name': 'Annecy',
  'temperature': 16.26,
  'rain': 2.05,
  'wind': 1.46,
  'score': 13.23},
 {'name': 'Grenoble',
  'temperature': 18.64,
  'rain': 1.08,
  'wind': 1.18,
  'score': 16.58},
 {'name': 'Lyon',
  'temperature': 17.22,
  'rain': 0.38,
  'wind': 2.94,
  'score': 15.56},
 {'name': 'Rougon',
  'temperature': 13.76,
  'rain': 0.2,
  'wind': 2.74,
  'score': 12.58},
 {'name': 'Bormes-les-Mimosas',
  'temperature': 18.25,
  'rain': 0.23,
  'wind': 4.23,
  'score': 16.74},
 {'name': 'Cassis',
  'temperature': 19.46,
  'rain': 0.45,
  'wind': 6.52,
  'score': 16.98},
 {'name': 'Marseille',
  'temperature': 20.34,
  'rain': 0.66,
  'wind': 6.53,
  'score': 17.8},
 {'name': 'Aix-en-Provence',
  'temperature': 19.17,
  'rain': 0.47,
  'wind': 4.01,
  'score': 17.57},
 {'name': 'Avignon',
  'temperature': 18.23,
  'rain': 0.85,
  'wind': 3.68,
  'score': 16.1},
 {'name': 'Uzès',
  'temperature': 17.21,
  'rain': 1.58,
  'wind': 3.67,
  'score': 14.35},
 {'name': 'Nîmes',
  'temperature': 18.3,
  'rain': 2.28,
  'wind': 4.72,
  'score': 14.59},
 {'name': 'Aigues-Mortes',
  'temperature': 18.94,
  'rain': 3.99,
  'wind': 7.34,
  'score': 13.07},
 {'name': 'Saintes-Maries-de-la-Mer',
  'temperature': 18.84,
  'rain': 2.09,
  'wind': 8.62,
  'score': 14.72},
 {'name': 'Collioure',
  'temperature': 19.0,
  'rain': 0.52,
  'wind': 4.14,
  'score': 17.2},
 {'name': 'Carcassonne',
  'temperature': 17.17,
  'rain': 11.67,
  'wind': 4.88,
  'score': 3.92},
 {'name': 'Tarascon-sur-Ariège',
  'temperature': 16.48,
  'rain': 16.39,
  'wind': 1.28,
  'score': -0.89},
 {'name': 'Toulouse',
  'temperature': 16.52,
  'rain': 26.48,
  'wind': 5.17,
  'score': -11.39},
 {'name': 'Montauban',
  'temperature': 17.09,
  'rain': 23.48,
  'wind': 5.71,
  'score': -7.97},
 {'name': 'Biarritz',
  'temperature': 15.87,
  'rain': 4.83,
  'wind': 7.61,
  'score': 9.01},
 {'name': 'Bayonne',
  'temperature': 15.77,
  'rain': 5.55,
  'wind': 6.58,
  'score': 8.19},
 {'name': 'La Rochelle',
  'temperature': 16.06,
  'rain': 2.74,
  'wind': 5.7,
  'score': 11.74}]

In [20]:
df_weather = pd.DataFrame(all_weather)
df_weather = df_weather.sort_values(by='score', ascending=False)
df_weather

                           name  temperature   rain  wind  score
20                    Marseille        20.34   0.66  6.53  17.80
21              Aix-en-Provence        19.17   0.47  4.01  17.57
27                    Collioure        19.00   0.52  4.14  17.20
19                       Cassis        19.46   0.45  6.52  16.98
18           Bormes-les-Mimosas        18.25   0.23  4.23  16.74
15                     Grenoble        18.64   1.08  1.18  16.58
22                      Avignon        18.23   0.85  3.68  16.10
16                         Lyon        17.22   0.38  2.94  15.56
10                       Colmar        16.53   0.06  2.08  15.49
11                    Eguisheim        16.43   0.08  2.07  15.37
8                    Strasbourg        16.17   0.05  2.64  15.14
26     Saintes-Maries-de-la-Mer        18.84   2.09  8.62  14.72
24                        Nîmes        18.30   2.28  4.72  14.59
23                         Uzès        17.21   1.58  3.67  14.35
5                         Paris        14.93   0.00  2.91  13.95
14                       Annecy        16.26   2.05  1.46  13.23
25                Aigues-Mortes        18.94   3.99  7.34  13.07
6                        Amiens        13.94   0.00  4.01  12.96
17                       Rougon        13.76   0.20  2.74  12.58
4                         Rouen        13.45   0.00  3.89  12.47
9   Château du Haut-Kœnigsbourg        13.36   0.10  1.78  12.28
12                     Besançon        17.07   3.82  2.35  12.27
7                         Lille        12.93   0.00  4.07  11.95
3                      Le Havre        13.50   0.00  5.49  11.77
34                  La Rochelle        16.06   2.74  5.70  11.74
13                        Dijon        15.24   2.99  1.56  11.27
2                        Bayeux        12.59   0.00  5.03  11.01
32                     Biarritz        15.87   4.83  7.61   9.01
33                      Bayonne        15.77   5.55  6.58   8.19
28                  Carcassonne        17.17  11.67  4.88   3.92
1                      St. Malo         5.59   0.50  6.43   3.36
0             Mont-Saint-Michel         4.48   0.00  5.49   2.75
29          Tarascon-sur-Ariège        16.48  16.39  1.28  -0.89
31                    Montauban        17.09  23.48  5.71  -7.97
30                     Toulouse        16.52  26.48  5.17 -11.39