In [26]:
import pandas as pd 
import numpy as np
import plotly.express as px

In [2]:
data = pd.read_excel('../data/get_around_delay_analysis.xlsx')
data.head()

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
0,505000,363965,mobile,canceled,NaN,NaN,NaN
1,507750,269550,mobile,ended,-81.0,NaN,NaN
2,508131,359049,connect,ended,70.0,NaN,NaN
3,508865,299063,connect,canceled,NaN,NaN,NaN
4,511440,313932,mobile,ended,NaN,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21310 entries, 0 to 21309
Data columns (total 7 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   rental_id                                   21310 non-null  int64
 1   car_id                                      21310 non-null  int64
 2   checkin_type                                21310 non-null  object
 3   state                                       21310 non-null  object
 4   delay_at_checkout_in_minutes                16346 non-null  float64
 5   previous_ended_rental_id                    1841 non-null   float64
 6   time_delta_with_previous_rental_in_minutes  1841 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.1+ MB

In [4]:
data.shape

(21310, 7)

In [5]:
data.isnull().sum()/len(data)*100

rental_id                                      0.000000
car_id                                         0.000000
checkin_type                                   0.000000
state                                          0.000000
delay_at_checkout_in_minutes                  23.294228
previous_ended_rental_id                      91.360863
time_delta_with_previous_rental_in_minutes    91.360863
dtype: float64

In [6]:
data.describe()

,rental_id,car_id,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
count,21310.000000,21310.000000,16346.000000,1841.000000,1841.000000
mean,549712.880338,350030.603426,59.701517,550127.411733,279.288430
std,13863.446964,58206.249765,1002.561635,13184.023111,254.594486
min,504806.000000,159250.000000,-22433.000000,505628.000000,0.000000
25%,540613.250000,317639.000000,-36.000000,540896.000000,60.000000
50%,550350.000000,368717.000000,9.000000,550567.000000,180.000000
75%,560468.500000,394928.000000,67.000000,560823.000000,540.000000
max,576401.000000,417675.000000,71084.000000,575053.000000,720.000000

In [7]:
data['car_id'].value_counts()

car_id
334190    33
392479    29
241021    29
342699    27
300505    24
          ..
372160     1
297623     1
403246     1
267750     1
408598     1
Name: count, Length: 8143, dtype: int64

In [8]:
data['rental_id'].value_counts()

rental_id
505000    1
558908    1
558830    1
558767    1
558746    1
         ..
568143    1
568065    1
568035    1
567994    1
575056    1
Name: count, Length: 21310, dtype: int64

In [9]:
data['delay_at_checkout_in_minutes'].mean()

59.70151719075003

In [10]:
data['checkin_type'].value_counts()

checkin_type
mobile     17003
connect     4307
Name: count, dtype: int64

In [11]:
data['state'].value_counts()

state
ended       18045
canceled     3265
Name: count, dtype: int64

In [13]:
data_clean = data[
    (data['delay_at_checkout_in_minutes'] >= -2880) &
    (data['delay_at_checkout_in_minutes'] <= 2880)
]

len(data_clean)/len(data)

0.7632097606757391

In [20]:
data_clean[data_clean["time_delta_with_previous_rental_in_minutes"].notna()]

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
6,511639,370585,connect,ended,-15.0,563782.0,570.0
19,519491,312389,mobile,ended,58.0,545639.0,420.0
40,528808,181625,connect,ended,-76.0,557404.0,330.0
64,533670,320824,connect,ended,-6.0,556563.0,630.0
74,534827,404169,mobile,ended,-7.0,531158.0,90.0
...,...,...,...,...,...,...,...
21249,571823,353425,connect,ended,-276.0,569556.0,240.0
21253,573274,298117,connect,ended,-7.0,571227.0,210.0
21266,567741,294059,mobile,ended,111.0,567708.0,120.0
21275,568523,297973,mobile,ended,12.0,567121.0,240.0
21286,569717,377312,mobile,ended,230.0,545045.0,90.0